// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System;
using System.Threading.Tasks;

namespace Migrator.PublicDemo.Playwright.NUnit;

// WARNING: some actions need manual review. See TODO comments below.

public class LoginSmokeTestPlaywright : PageTest
{
    [SetUp]
    public async Task SetUp()
    {
        // TODO: UNSUPPORTED [MIGRATOR:UNSUPPORTED_ACTION] page = Navigation.OpenLoginPage();
        // TODO: UNSUPPORTED [MIGRATOR:UNSUPPORTED_ACTION] page.Loader.ValidateLoading();
        // Safe next action: add a navigation/setup mapping or target PageObject fixture.
        await Task.CompletedTask;
    }

    [Category("Smoke")]
    [Test]
    public async Task LoginWithValidCredentials()
    {
        await Page.GetByTestId("login-username").FillAsync("admin@example.test");
        await Page.GetByTestId("login-password").FillAsync("correct-horse-battery-staple");
        await Page.GetByTestId("login-submit").ClickAsync();
        await Expect(Page.GetByTestId("login-success-toast")).ToBeVisibleAsync();
    }
}
