// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System;
using System.Threading.Tasks;

namespace Golden.Tests.Playwright;

public class BasicActionsPlaywright : PageTest
{

	[Category("QuickRunning")]
	[Test]
	public async Task ClickFillAndAssert()
	{
		await Page.GetByTestId("save-button").ClickAsync(); // line 10
		await Page.GetByTestId("name-input").FillAsync("Alex"); // line 11
		await Expect(Page.GetByTestId("toast")).ToHaveTextAsync("Saved"); // line 12
		await Expect(Page.GetByTestId("loader")).ToBeHiddenAsync(); // line 13
	}

}
