using System;
using System.Collections.Generic;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Text;
using System.Text.Json;
using Migrator.Core;

internal static class EvidencePackCommand
{
    static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        PropertyNamingPolicy = JsonNamingPolicy.CamelCase
    };

    static readonly HashSet<string> TextExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".json", ".md", ".txt", ".csv", ".html", ".htm", ".xml", ".trx", ".log", ".patch", ".diff", ".csproj", ".sln", ".props", ".targets", ".config", ".yml", ".yaml"
    };

    static readonly HashSet<string> SourceLikeExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".cs", ".ts", ".tsx", ".js", ".jsx", ".java", ".py"
    };

    static readonly HashSet<string> BinaryEvidenceExtensions = new(StringComparer.OrdinalIgnoreCase)
    {
        ".zip", ".png", ".jpg", ".jpeg", ".webp", ".gif", ".webm", ".mp4", ".har", ".trace"
    };

    static readonly string[] ExcludedSegments =
    {
        ".git", ".vs", ".idea", "bin", "obj", "node_modules", ".playwright", "playwright/.cache"
    };

    public static int RunEvidencePack(string inputPath, string outPath, string format, bool includeSourceFiles)
    {
        _ = format; // Evidence pack is always a zip; manifest files inside the zip cover text/json consumers.

        if (!Directory.Exists(inputPath))
        {
            Console.Error.WriteLine($"evidence pack expects a migration artifact directory: {inputPath}");
            return 1;
        }

        var artifactRoot = Path.GetFullPath(inputPath);
        var zipPath = ResolveZipPath(outPath);
        Directory.CreateDirectory(Path.GetDirectoryName(zipPath) ?? ".");

        var files = CollectEvidenceFiles(artifactRoot, zipPath, includeSourceFiles).ToArray();
        var entries = new List<EvidencePackManifestEntry>();
        var checksums = new List<EvidencePackChecksum>();

        if (File.Exists(zipPath))
            File.Delete(zipPath);

        using (var zip = ZipFile.Open(zipPath, ZipArchiveMode.Create))
        {
            foreach (var file in files)
            {
                var relative = NormalizeZipEntry(SafeRelativePath(artifactRoot, file));
                if (string.IsNullOrWhiteSpace(relative) || relative.StartsWith("../", StringComparison.Ordinal) || Path.IsPathRooted(relative))
                    continue;

                var entryPath = NormalizeZipEntry(Path.Combine("artifacts", relative));
                var packed = ReadEvidenceFileBytes(file, artifactRoot, out var redaction, out var note);
                var checksum = ComputeSha256(packed);
                WriteZipEntry(zip, entryPath, packed);

                entries.Add(new EvidencePackManifestEntry(
                    EntryPath: entryPath,
                    OriginalPath: RedactEvidencePath(file, artifactRoot),
                    RelativePath: relative,
                    SizeBytes: packed.Length,
                    Sha256: checksum,
                    Redaction: redaction,
                    SensitiveHint: SensitiveHint(file, note),
                    SourceIncluded: IsSourceLike(file) && !IsGeneratedMigrationSource(file)));
                checksums.Add(new EvidencePackChecksum(entryPath, checksum));
            }

            var manifest = new EvidencePackManifest(
                SchemaVersion: "evidence-pack/v1",
                GeneratedAtUtc: DateTimeOffset.UtcNow,
                ArtifactRoot: "<ARTIFACT_ROOT>",
                IncludeSourceFiles: includeSourceFiles,
                Redaction: new EvidencePackRedactionSummary(
                    AbsoluteUserPaths: "redacted in text artifacts and manifest paths using <USER_HOME>",
                    ArtifactRootPaths: "redacted in text artifacts using <ARTIFACT_ROOT>",
                    BinaryArtifacts: "included as-is and marked binary-not-redacted"),
                Safety: new[]
                {
                    includeSourceFiles
                        ? "Source-like files were explicitly included by --include-source. Review the pack before sharing."
                        : "Source-like files are excluded unless they look generated by Migrator.",
                    "The command never modifies source or artifact files.",
                    "Binary artifacts such as traces, screenshots, and videos are not content-redacted."
                },
                Entries: entries.OrderBy(x => x.EntryPath, StringComparer.OrdinalIgnoreCase).ToArray());

            var manifestJsonBytes = Encoding.UTF8.GetBytes(JsonSerializer.Serialize(manifest, JsonOptions) + Environment.NewLine);
            WriteZipEntry(zip, "evidence-manifest.json", manifestJsonBytes);
            checksums.Add(new EvidencePackChecksum("evidence-manifest.json", ComputeSha256(manifestJsonBytes)));

            var manifestMdBytes = Encoding.UTF8.GetBytes(RenderManifestMarkdown(manifest));
            WriteZipEntry(zip, "evidence-manifest.md", manifestMdBytes);
            checksums.Add(new EvidencePackChecksum("evidence-manifest.md", ComputeSha256(manifestMdBytes)));

            var checksumsText = RenderChecksums(checksums);
            WriteZipEntry(zip, "checksums.sha256", Encoding.UTF8.GetBytes(checksumsText));
        }

        Console.WriteLine("=== Evidence Pack ===");
        Console.WriteLine($"Source: {artifactRoot}");
        Console.WriteLine($"Zip: {zipPath}");
        Console.WriteLine($"Entries: {entries.Count}");
        Console.WriteLine($"Source-like files: {(includeSourceFiles ? "included by request" : "excluded unless generated")}");
        Console.WriteLine("Manifest: evidence-manifest.json / evidence-manifest.md");
        return 0;
    }

    public static EvidencePackPreview BuildPreview(string inputPath, bool includeSourceFiles)
    {
        var artifactRoot = Path.GetFullPath(inputPath);
        var files = CollectEvidenceFiles(artifactRoot, Path.Combine(artifactRoot, "__preview__.zip"), includeSourceFiles).ToArray();
        return new EvidencePackPreview(
            ArtifactRoot: artifactRoot,
            IncludeSourceFiles: includeSourceFiles,
            Files: files.Select(file => SafeRelativePath(artifactRoot, file)).OrderBy(x => x, StringComparer.OrdinalIgnoreCase).ToArray());
    }

    static IEnumerable<string> CollectEvidenceFiles(string artifactRoot, string zipPath, bool includeSourceFiles)
    {
        foreach (var file in Directory.EnumerateFiles(artifactRoot, "*", SearchOption.AllDirectories))
        {
            var full = Path.GetFullPath(file);
            if (string.Equals(full, Path.GetFullPath(zipPath), StringComparison.OrdinalIgnoreCase))
                continue;
            if (IsExcludedPath(artifactRoot, full))
                continue;
            if (Path.GetFileName(full).Equals("checksums.sha256", StringComparison.OrdinalIgnoreCase)
                && IsInsideDirectory(Path.GetDirectoryName(full) ?? artifactRoot, Path.GetDirectoryName(zipPath) ?? artifactRoot))
                continue;

            var ext = Path.GetExtension(full);
            if (SourceLikeExtensions.Contains(ext))
            {
                if (includeSourceFiles || IsGeneratedMigrationSource(full))
                    yield return full;
                continue;
            }

            if (TextExtensions.Contains(ext) || BinaryEvidenceExtensions.Contains(ext) || LooksLikeTextArtifact(full) || LooksLikeMigrationArtifact(full))
                yield return full;
        }
    }

    static byte[] ReadEvidenceFileBytes(string file, string artifactRoot, out string redaction, out string note)
    {
        var ext = Path.GetExtension(file);
        if (TextExtensions.Contains(ext) || SourceLikeExtensions.Contains(ext) || LooksLikeTextArtifact(file))
        {
            try
            {
                var original = File.ReadAllText(file);
                var redacted = RedactEvidenceText(original, artifactRoot);
                redaction = string.Equals(original, redacted, StringComparison.Ordinal) ? "not-needed" : "applied";
                note = "text";
                return Encoding.UTF8.GetBytes(redacted);
            }
            catch
            {
                // Fall through to binary handling if text reading fails.
            }
        }

        redaction = "binary-not-redacted";
        note = "binary";
        return File.ReadAllBytes(file);
    }

    static string RedactEvidenceText(string text, string artifactRoot)
    {
        var result = PathRedaction.Redact(text);
        var fullRoot = Path.GetFullPath(artifactRoot);
        result = result.Replace(fullRoot, "<ARTIFACT_ROOT>", StringComparison.OrdinalIgnoreCase);
        result = result.Replace(fullRoot.Replace('\\', '/'), "<ARTIFACT_ROOT>", StringComparison.OrdinalIgnoreCase);
        result = result.Replace(fullRoot.Replace('/', '\\'), "<ARTIFACT_ROOT>", StringComparison.OrdinalIgnoreCase);
        return result;
    }

    static string RedactEvidencePath(string path, string artifactRoot)
    {
        return RedactEvidenceText(Path.GetFullPath(path), artifactRoot);
    }

    static string SensitiveHint(string file, string note)
    {
        var name = Path.GetFileName(file);
        var lower = name.ToLowerInvariant();
        if (lower.Contains("trace") || lower.Contains("video") || lower.Contains("screenshot") || lower.EndsWith(".har", StringComparison.Ordinal))
            return "may contain UI state, URLs, screenshots, or network data";
        if (lower.Contains("config") || lower.Contains("profile") || lower.Contains("settings") || lower.Contains("secret") || lower.Contains("token"))
            return "review config/profile values before external sharing";
        if (note == "binary")
            return "binary content was not redacted";
        return "none";
    }

    static bool LooksLikeMigrationArtifact(string file)
    {
        var name = Path.GetFileName(file);
        return name.Contains("report", StringComparison.OrdinalIgnoreCase)
            || name.Contains("classification", StringComparison.OrdinalIgnoreCase)
            || name.Contains("dashboard", StringComparison.OrdinalIgnoreCase)
            || name.Contains("manifest", StringComparison.OrdinalIgnoreCase)
            || name.Contains("ledger", StringComparison.OrdinalIgnoreCase)
            || name.Contains("next-ticket", StringComparison.OrdinalIgnoreCase)
            || name.Contains("next-commands", StringComparison.OrdinalIgnoreCase)
            || name.Contains("adapter-config", StringComparison.OrdinalIgnoreCase);
    }

    static bool LooksLikeTextArtifact(string file)
    {
        var name = Path.GetFileName(file);
        return name.EndsWith(".jsonl", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith(".out", StringComparison.OrdinalIgnoreCase)
            || name.EndsWith(".err", StringComparison.OrdinalIgnoreCase);
    }

    static bool IsGeneratedMigrationSource(string file)
    {
        try
        {
            var text = File.ReadAllText(file);
            return text.Contains("Generated by Migrator", StringComparison.Ordinal)
                || text.Contains("MIGRATOR:", StringComparison.Ordinal);
        }
        catch
        {
            return false;
        }
    }

    static bool IsSourceLike(string file) => SourceLikeExtensions.Contains(Path.GetExtension(file));

    static bool IsExcludedPath(string root, string file)
    {
        var relative = NormalizeZipEntry(SafeRelativePath(root, file));
        foreach (var segment in ExcludedSegments)
        {
            var normalized = NormalizeZipEntry(segment).Trim('/');
            if (relative.Equals(normalized, StringComparison.OrdinalIgnoreCase)
                || relative.StartsWith(normalized + "/", StringComparison.OrdinalIgnoreCase)
                || relative.Contains("/" + normalized + "/", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    static string ResolveZipPath(string outPath)
    {
        if (outPath.EndsWith(".zip", StringComparison.OrdinalIgnoreCase))
            return Path.GetFullPath(outPath);

        return Path.GetFullPath(Path.Combine(outPath, "evidence-pack.zip"));
    }

    static void WriteZipEntry(ZipArchive zip, string entryPath, byte[] bytes)
    {
        var entry = zip.CreateEntry(NormalizeZipEntry(entryPath), CompressionLevel.Optimal);
        using var stream = entry.Open();
        stream.Write(bytes, 0, bytes.Length);
    }

    static string RenderManifestMarkdown(EvidencePackManifest manifest)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Evidence Pack Manifest");
        sb.AppendLine();
        sb.AppendLine($"Generated: `{manifest.GeneratedAtUtc:O}`");
        sb.AppendLine($"Artifact root: `{manifest.ArtifactRoot}`");
        sb.AppendLine($"Source-like files included: `{manifest.IncludeSourceFiles}`");
        sb.AppendLine();
        sb.AppendLine("## Safety notes");
        foreach (var note in manifest.Safety)
            sb.AppendLine($"- {note}");
        sb.AppendLine();
        sb.AppendLine("## Entries");
        sb.AppendLine();
        sb.AppendLine("| Entry | SHA-256 | Redaction | Sensitive hint |");
        sb.AppendLine("|---|---|---|---|");
        foreach (var entry in manifest.Entries)
            sb.AppendLine($"| `{entry.EntryPath}` | `{entry.Sha256}` | {entry.Redaction} | {entry.SensitiveHint} |");
        return sb.ToString();
    }

    static string RenderChecksums(IEnumerable<EvidencePackChecksum> checksums)
    {
        var sb = new StringBuilder();
        foreach (var item in checksums.OrderBy(x => x.EntryPath, StringComparer.OrdinalIgnoreCase))
            sb.AppendLine($"{item.Sha256}  {item.EntryPath}");
        return sb.ToString();
    }

    static string SafeRelativePath(string root, string file)
    {
        try
        {
            return Path.GetRelativePath(Path.GetFullPath(root), Path.GetFullPath(file));
        }
        catch
        {
            return Path.GetFileName(file);
        }
    }

    static bool IsInsideDirectory(string file, string directory)
    {
        var fullFile = Path.GetFullPath(file).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        var fullDir = Path.GetFullPath(directory).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;
        return fullFile.StartsWith(fullDir, StringComparison.OrdinalIgnoreCase)
            || string.Equals(fullFile, fullDir.TrimEnd(Path.DirectorySeparatorChar), StringComparison.OrdinalIgnoreCase);
    }

    static string NormalizeZipEntry(string path) => path.Replace(Path.DirectorySeparatorChar, '/').Replace(Path.AltDirectorySeparatorChar, '/');

    static string ComputeSha256(byte[] bytes) => Convert.ToHexString(System.Security.Cryptography.SHA256.HashData(bytes)).ToLowerInvariant();
}

internal sealed record EvidencePackPreview(string ArtifactRoot, bool IncludeSourceFiles, string[] Files);
internal sealed record EvidencePackChecksum(string EntryPath, string Sha256);
internal sealed record EvidencePackManifest(string SchemaVersion, DateTimeOffset GeneratedAtUtc, string ArtifactRoot, bool IncludeSourceFiles, EvidencePackRedactionSummary Redaction, string[] Safety, EvidencePackManifestEntry[] Entries);
internal sealed record EvidencePackRedactionSummary(string AbsoluteUserPaths, string ArtifactRootPaths, string BinaryArtifacts);
internal sealed record EvidencePackManifestEntry(string EntryPath, string OriginalPath, string RelativePath, long SizeBytes, string Sha256, string Redaction, string SensitiveHint, bool SourceIncluded);
