using System.Diagnostics;
using System.Reflection;
using Xunit;

namespace Migrator.Tests;

[Collection("CliProcess")]
public class ArtifactLookupTests
{
    [Fact]
    public void ExplainTodo_DefaultLookup_RejectsParentDirectoryWithNestedRunArtifacts()
    {
        var temp = CreateTempDir();
        try
        {
            Directory.CreateDirectory(Path.Combine(temp, "run-old"));
            Directory.CreateDirectory(Path.Combine(temp, "run-new"));
            File.WriteAllText(Path.Combine(temp, "run-old", "report.json"), "{}");
            File.WriteAllText(Path.Combine(temp, "run-new", "report.json"), "{}");

            var result = RunCli($"--mode explain-todo --input \"{temp}\" --out \"{Path.Combine(temp, "out")}\" --format both");

            Assert.Equal(2, result.ExitCode);
            Assert.Contains("does not look like a single run directory", result.StdErr);
            Assert.Contains("run-old", result.StdErr);
            Assert.Contains("run-new", result.StdErr);
            Assert.Contains("--recursive-artifacts", result.StdErr);
        }
        finally
        {
            TryDelete(temp);
        }
    }

    [Fact]
    public void ExplainTodo_RecursiveLookup_FailsFastWhenMultipleCandidatesExist()
    {
        var temp = CreateTempDir();
        try
        {
            Directory.CreateDirectory(Path.Combine(temp, "run-old"));
            Directory.CreateDirectory(Path.Combine(temp, "run-new"));
            File.WriteAllText(Path.Combine(temp, "run-old", "report.json"), "{}");
            File.WriteAllText(Path.Combine(temp, "run-new", "report.json"), "{}");

            var result = RunCli($"--mode explain-todo --recursive-artifacts --input \"{temp}\" --out \"{Path.Combine(temp, "out")}\" --format both");

            Assert.Equal(2, result.ExitCode);
            Assert.Contains("Multiple artifact candidates found for report.json", result.StdErr);
            Assert.Contains("run-old", result.StdErr);
            Assert.Contains("run-new", result.StdErr);
        }
        finally
        {
            TryDelete(temp);
        }
    }

    [Fact]
    public void ExplainTodo_DirectRunDirectory_WritesDirectOnlyLookupMetadata()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":0}");
            var outDir = Path.Combine(temp, "out");

            var result = RunCli($"--mode explain-todo --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "explain-todo.md"));
            Assert.Contains("Artifact lookup", markdown);
            Assert.Contains("direct-only", markdown);
        }
        finally
        {
            TryDelete(temp);
        }
    }


    [Fact]
    public void MigrationBoard_WritesQualityGatesForSuppressionSafety()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":2}");
            File.WriteAllText(Path.Combine(temp, "GeneratedTest.cs"), """
            // Generated by Migrator — Selenium C# → Playwright .NET
            // TODO: empty [MIGRATOR:EMPTY_TEST_AFTER_SUPPRESSION]
            // TODO: depends [MIGRATOR:DEPENDS_ON_SUPPRESSED_SIDE_EFFECT]
            """);
            File.WriteAllText(Path.Combine(temp, "config-validate-report.json"), """
            {
              "Status": "passed",
              "Metrics": [
                { "Name": "SuppressedMethodPatterns", "Value": 71 }
              ],
              "Issues": [
                { "Severity": "warning", "Code": "REGEX_LIKE_SUPPRESSION_PATTERN", "Message": "regex-like", "Location": "SuppressedMethodPatterns", "SuggestedAction": "Run helper inventory" }
              ]
            }
            """);
            var outDir = Path.Combine(temp, "board");

            var result = RunCli($"--mode migration-board --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "migration-board.md"));
            Assert.Contains("## Quality gates", markdown);
            Assert.Contains("EMPTY_TEST_AFTER_SUPPRESSION", markdown);
            Assert.Contains("DEPENDS_ON_SUPPRESSED_SIDE_EFFECT", markdown);
            Assert.Contains("SuppressedMethodPatterns", markdown);
            Assert.Contains("Regex-looking suppressions", markdown);
            Assert.Contains("Project verify is not-run", markdown);
            Assert.Contains("Safety-gate batch", markdown);
        }
        finally
        {
            TryDelete(temp);
        }
    }


    [Fact]
    public void AgentNextTask_NotRunVerify_PrioritizesFreshVerifyProjectAndConcreteRun()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":1}");
            File.WriteAllText(Path.Combine(temp, "GeneratedTest.cs"), """
            // Generated by Migrator — Selenium C# → Playwright .NET
            // TODO: missing mapping [MIGRATOR:MISSING_MAPPING]
            """);
            var outDir = Path.Combine(temp, "out");

            var result = RunCli($"--mode explain-todo --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "agent-next-task.md"));
            Assert.Contains("## Run context", markdown);
            Assert.Contains("Artifact lookup", markdown);
            Assert.Contains("direct-only", markdown);
            Assert.Contains("P0_VERIFY_PROJECT", markdown);
            Assert.Contains("Project verify is not-run", markdown);
            Assert.Contains("--mode verify-project", markdown);
            Assert.Contains("runtime-ready claims are not trustworthy", markdown);
            Assert.True(markdown.Contains("Do not point report commands at a parent folder", StringComparison.OrdinalIgnoreCase), markdown);
        }
        finally
        {
            TryDelete(temp);
        }
    }

    [Fact]
    public void AgentNextTask_PassedVerifyWithSuppressedSideEffect_PrioritizesSafetyAndHelperInventory()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":1}");
            File.WriteAllText(Path.Combine(temp, "project-verify-report.json"), """
            {
              "Status": "passed",
              "ExitCode": 0,
              "Diagnostics": [],
              "ClassifiedDiagnostics": []
            }
            """);
            File.WriteAllText(Path.Combine(temp, "GeneratedTest.cs"), """
            // Generated by Migrator — Selenium C# → Playwright .NET
            // TODO: depends on suppressed side-effect at line 10: page.BillNumber.InputAndAccept("219") [MIGRATOR:DEPENDS_ON_SUPPRESSED_SIDE_EFFECT]
            """);
            var outDir = Path.Combine(temp, "out");

            var result = RunCli($"--mode explain-todo --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "agent-next-task.md"));
            Assert.Contains("P1_SUPPRESSION_SAFETY", markdown);
            Assert.Contains("DEPENDS_ON_SUPPRESSED_SIDE_EFFECT", markdown);
            Assert.Contains("--mode helper-inventory", markdown);
            Assert.Contains("InputAndAccept", markdown);
            Assert.Contains("No new broad suppressions", markdown);
            Assert.Contains("Do not guess selectors or helper semantics", markdown);
        }
        finally
        {
            TryDelete(temp);
        }
    }


    [Fact]
    public void ExplainTodo_WritesNormalizedRootCauseGroups()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":4}");
            File.WriteAllText(Path.Combine(temp, "GeneratedTest.cs"), """
            // Generated by Migrator — Selenium C# → Playwright .NET
            // TODO: depends on suppressed side-effect at line 10: page.BillNumber.InputAndAccept("219") [MIGRATOR:DEPENDS_ON_SUPPRESSED_SIDE_EFFECT]
            // TODO: depends on suppressed side-effect at line 20: page.Date.InputAndAccept("2025") [MIGRATOR:DEPENDS_ON_SUPPRESSED_SIDE_EFFECT]
            // TODO: table mapping required: page.RegistryHead.Rows.ElementAt(2).Text.Should("219") [MIGRATOR:TABLE_MAPPING_REQUIRED]
            // TODO: source-only identifier: Urls.BaseUrlPartners [MIGRATOR:SOURCE_ONLY_IDENTIFIER]
            """);
            var outDir = Path.Combine(temp, "out");

            var result = RunCli($"--mode explain-todo --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "explain-todo.md"));
            Assert.Contains("## Top normalized root causes", markdown);
            Assert.Contains("Suppressed side-effect family `InputAndAccept`", markdown);
            Assert.Contains("Table/list mapping", markdown);
            Assert.Contains("source-only root `Urls`", markdown);
            var json = File.ReadAllText(Path.Combine(outDir, "explain-todo.json"));
            Assert.Contains("NormalizedRootCauses", json);
            Assert.Contains("TableMappingCandidates", json);
            Assert.Contains("page.RegistryHead", json);
            Assert.Contains("Rows.ElementAt", json);
            Assert.Contains("suppressed-side-effect:InputAndAccept", json);
        }
        finally
        {
            TryDelete(temp);
        }
    }

    [Fact]
    public void MigrationBoard_WritesNormalizedRootCauseSection()
    {
        var temp = CreateTempDir();
        try
        {
            File.WriteAllText(Path.Combine(temp, "report.json"), "{\"FilesProcessed\":1,\"TestsFound\":1,\"TodoComments\":2}");
            File.WriteAllText(Path.Combine(temp, "GeneratedTest.cs"), """
            // Generated by Migrator — Selenium C# → Playwright .NET
            // TODO: manual review needed: CreateDopCalc(lightbox) [MIGRATOR:MANUAL_REVIEW]
            // TODO: manual review needed: CreateDopCalc(lightbox) [MIGRATOR:MANUAL_REVIEW]
            // TODO: table mapping required: page.RegistryHead.Rows.ElementAt(2).Text.Should("219") [MIGRATOR:TABLE_MAPPING_REQUIRED]
            """);
            var outDir = Path.Combine(temp, "board");

            var result = RunCli($"--mode migration-board --input \"{temp}\" --out \"{outDir}\" --format both");

            AssertCliSuccess(result);
            var markdown = File.ReadAllText(Path.Combine(outDir, "migration-board.md"));
            Assert.Contains("## Top normalized root causes", markdown);
            Assert.Contains("method family `CreateDopCalc`", markdown);
            Assert.Contains("## Table/list mapping candidates", markdown);
            Assert.Contains("page.RegistryHead", markdown);
            var html = File.ReadAllText(Path.Combine(outDir, "migration-board.html"));
            Assert.Contains("Top normalized root causes", html);
            Assert.Contains("Table/list mapping candidates", html);
            Assert.Contains("CreateDopCalc", html);
            Assert.Contains("page.RegistryHead", html);
        }
        finally
        {
            TryDelete(temp);
        }
    }

    static void AssertCliSuccess(CliResult result)
    {
        Assert.True(
            result.ExitCode == 0,
            $"Expected CLI exit code 0, got {result.ExitCode}.\nSTDOUT:\n{result.StdOut}\nSTDERR:\n{result.StdErr}");
    }

    static CliResult RunCli(string arguments)
    {
        var repoRoot = GetRepoRoot();
        if (repoRoot == null)
            throw new InvalidOperationException("Could not find repo root (Migrator.sln not found)");

        var cliProject = Path.Combine(repoRoot, "Migrator.Cli", "Migrator.Cli.csproj");
        var psi = new ProcessStartInfo
        {
            FileName = "dotnet",
            Arguments = $"run --project \"{cliProject}\" -- {arguments}",
            WorkingDirectory = repoRoot,
            RedirectStandardOutput = true,
            RedirectStandardError = true,
            UseShellExecute = false,
            CreateNoWindow = true
        };

        using var process = Process.Start(psi)!;
        var stdout = process.StandardOutput.ReadToEnd();
        var stderr = process.StandardError.ReadToEnd();
        process.WaitForExit();
        return new CliResult(process.ExitCode, stdout, stderr);
    }

    static string? GetRepoRoot()
    {
        var dir = new DirectoryInfo(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location)!);
        for (var i = 0; i < 10; i++)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Migrator.sln")))
                return dir.FullName;
            dir = dir.Parent;
            if (dir == null)
                break;
        }

        return null;
    }

    static string CreateTempDir()
    {
        var path = Path.Combine(Path.GetTempPath(), "migrator-artifact-lookup-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(path);
        return path;
    }

    static void TryDelete(string path)
    {
        try
        {
            if (Directory.Exists(path))
                Directory.Delete(path, recursive: true);
        }
        catch
        {
            // best effort cleanup
        }
    }

    record CliResult(int ExitCode, string StdOut, string StdErr);
}
