using Xunit;

namespace Migrator.Tests;

public class EvidencePackProductTests
{
    [Fact]
    public void EvidencePack_CommandIsPublicAndDirectCommandIsNormalized()
    {
        var program = File.ReadAllText(FindRepositoryFile("Migrator.Cli/Program.cs"));
        var catalog = File.ReadAllText(FindRepositoryFile("Migrator.Cli/Commands/CliCommandCatalog.cs"));

        Assert.Contains("mode == \"evidence-pack\"", program);
        Assert.Contains("EvidencePackCommand.RunEvidencePack", program);
        Assert.Contains("string.Equals(args[0], \"evidence\"", program);
        Assert.Contains("string.Equals(args[1], \"pack\"", program);
        Assert.Contains("StableCommand(\"evidence-pack\"", catalog);
        Assert.Contains("selenium-pw-migrator evidence pack --input migration/runs/run-042 --out evidence/run-042.zip", catalog);
    }

    [Fact]
    public void EvidencePack_WritesManifestChecksumsAndRedactionMetadata()
    {
        var command = File.ReadAllText(FindRepositoryFile("Migrator.Cli/Commands/EvidencePackCommand.cs"));

        Assert.Contains("evidence-manifest.json", command);
        Assert.Contains("evidence-manifest.md", command);
        Assert.Contains("checksums.sha256", command);
        Assert.Contains("ComputeSha256", command);
        Assert.Contains("EvidencePackRedactionSummary", command);
        Assert.Contains("PathRedaction.Redact", command);
        Assert.Contains("<ARTIFACT_ROOT>", command);
        Assert.Contains("binary-not-redacted", command);
    }

    [Fact]
    public void EvidencePack_ExcludesSourceLikeFilesUnlessExplicitlyRequested()
    {
        var command = File.ReadAllText(FindRepositoryFile("Migrator.Cli/Commands/EvidencePackCommand.cs"));
        var program = File.ReadAllText(FindRepositoryFile("Migrator.Cli/Program.cs"));

        Assert.Contains("SourceLikeExtensions", command);
        Assert.Contains("--include-source", program);
        Assert.Contains("IncludeSourceFiles", program);
        Assert.Contains("includeSourceFiles || IsGeneratedMigrationSource", command);
        Assert.Contains("Generated by Migrator", command);
        Assert.Contains("MIGRATOR:", command);
        Assert.Contains("Source-like files are excluded unless they look generated by Migrator", command);
    }

    [Fact]
    public void Docs_DescribeEvidencePackSharingWorkflow()
    {
        var docs = File.ReadAllText(FindRepositoryFile("docs/evidence-pack.md"));
        var readme = File.ReadAllText(FindRepositoryFile("README.md"));
        var docsIndex = File.ReadAllText(FindRepositoryFile("docs/README.md"));

        Assert.Contains("selenium-pw-migrator evidence pack", docs);
        Assert.Contains("evidence-manifest.json", docs);
        Assert.Contains("checksums.sha256", docs);
        Assert.Contains("--include-source", docs);
        Assert.Contains("Binary artifacts are included as-is", docs);
        Assert.Contains("docs/evidence-pack.md", readme);
        Assert.Contains("evidence-pack.md", docsIndex);
    }

    static string FindRepositoryFile(string relativePath)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (File.Exists(candidate))
                return candidate;
            dir = dir.Parent;
        }

        throw new FileNotFoundException($"Could not find repository file: {relativePath}");
    }
}
