using System.Text.Json;
using Migrator.Lab.Contracts;
using Migrator.Lab.Execution;
using Migrator.Lab.Reports;

namespace Migrator.Tests;

[Trait("Layer", "Unit")]
public sealed class LabBaselineDiffTests
{
    [Fact]
    public void GeneratedFingerprint_IgnoresFormattingGeneratedCommentsAndLineTrivia()
    {
        var root = TempRoot();
        try
        {
            var firstDirectory = Path.Combine(root, "first");
            var secondDirectory = Path.Combine(root, "second");
            Directory.CreateDirectory(firstDirectory);
            Directory.CreateDirectory(secondDirectory);
            var first = Path.Combine(firstDirectory, "Sample.cs");
            var second = Path.Combine(secondDirectory, "Sample.cs");
            File.WriteAllText(first, """
            // Generated by Migrator at 2026-07-30T10:00:00Z
            public class Sample
            {
                public void Run() { } // line 12
            }
            """);
            File.WriteAllText(second, """
            // a different generated comment
            public class Sample
            {
            public void Run() { }
            }
            """);

            Assert.Equal(
                LabComparisonNormalizer.ComputeGeneratedSemanticHash(new[] { first }),
                LabComparisonNormalizer.ComputeGeneratedSemanticHash(new[] { second }));
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [Fact]
    public void DiagnosticNormalization_RemovesRunRootsTempGuidsAndTimestamps()
    {
        var firstRoot = Path.Combine(Path.GetTempPath(), "run-one");
        var secondRoot = Path.Combine(Path.GetTempPath(), "run-two");
        var first = $"{firstRoot}/projects/{Guid.NewGuid()}/Sample.cs at 2026-07-30T10:00:00Z";
        var second = $"{secondRoot}/projects/{Guid.NewGuid()}/Sample.cs at 2026-07-30T11:00:00Z";

        Assert.Equal(
            LabComparisonNormalizer.NormalizeText(first, firstRoot),
            LabComparisonNormalizer.NormalizeText(second, secondRoot));
    }

    [Fact]
    public void Diff_DetectsQualityDiagnosticAndPerformanceRegression()
    {
        var root = TempRoot();
        try
        {
            var baselineRun = CreateRun(root, "baseline", todo: 0, durationMs: 10_000, actualStatus: ScenarioStatus.Pass, diagnostic: null);
            var currentRun = CreateRun(root, "current", todo: 1, durationMs: 13_000, actualStatus: ScenarioStatus.Pass, diagnostic: "missing-type-or-namespace");
            var baseline = LabBaselineService.Create(baselineRun, "main");

            var diff = LabDiffEngine.Compare(baseline, currentRun, root, root, durationRegressionPercent: 20);

            var project = Assert.Single(diff.Projects);
            Assert.Equal(LabDiffKind.Regressed, project.Kind);
            Assert.True(project.IsRegression);
            Assert.Equal(1, project.TodoComments.Delta);
            Assert.Contains("missing-type-or-namespace", project.AddedDiagnostics);
            Assert.Contains(project.Reasons, reason => reason.Contains("Duration increased", StringComparison.Ordinal));
            Assert.Equal(1, diff.Summary.Regressions);
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [Fact]
    public void Diff_ReportsImprovementAndDoesNotFailOnTriviaOnlyGeneratedChange()
    {
        var root = TempRoot();
        try
        {
            var baselineRun = CreateRun(root, "baseline", todo: 2, durationMs: 12_000, actualStatus: ScenarioStatus.Regression, diagnostic: "unmapped");
            var currentRun = CreateRun(root, "current", todo: 0, durationMs: 8_000, actualStatus: ScenarioStatus.Pass, diagnostic: null, alternateFormatting: true);
            var baseline = LabBaselineService.Create(baselineRun, "main");

            var diff = LabDiffEngine.Compare(baseline, currentRun, root, root, durationRegressionPercent: 20);

            var project = Assert.Single(diff.Projects);
            Assert.Equal(LabDiffKind.Improved, project.Kind);
            Assert.False(project.IsRegression);
            Assert.True(project.IsImprovement);
            Assert.False(project.GeneratedSemanticChanged);
            Assert.Equal(1, diff.Summary.Improvements);
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    [Fact]
    public void BaselineAndDiffWriters_CreateMachineMarkdownAndHtmlArtifacts()
    {
        var root = TempRoot();
        try
        {
            var run = CreateRun(root, "run", todo: 0, durationMs: 100, actualStatus: ScenarioStatus.Pass, diagnostic: null);
            var runRoot = Path.Combine(root, "run-report");
            run = run with { ArtifactsRoot = runRoot };
            LabRunReportWriter.Write(run);
            Assert.True(File.Exists(Path.Combine(runRoot, "lab-summary.html")));
            Assert.Contains("p01", File.ReadAllText(Path.Combine(runRoot, "lab-summary.html")));

            var baseline = LabBaselineService.Create(run, "main");
            var baselineRoot = Path.Combine(root, "baseline-report");
            LabBaselineReportWriter.Write(baseline, baselineRoot);
            Assert.True(File.Exists(Path.Combine(baselineRoot, "lab-baseline.json")));
            Assert.True(File.Exists(Path.Combine(baselineRoot, "lab-baseline.md")));

            var loaded = LabRunArtifactLoader.LoadBaseline(baselineRoot);
            Assert.Equal("main", loaded.Label);
            Assert.Single(loaded.Projects);

            var diff = LabDiffEngine.Compare(loaded, run, baselineRoot, runRoot, 20);
            var diffRoot = Path.Combine(root, "diff-report");
            LabDiffReportWriter.Write(diff, diffRoot);
            Assert.True(File.Exists(Path.Combine(diffRoot, "lab-diff.json")));
            Assert.True(File.Exists(Path.Combine(diffRoot, "lab-diff.md")));
            Assert.True(File.Exists(Path.Combine(diffRoot, "lab-diff.html")));

            using var document = JsonDocument.Parse(File.ReadAllText(Path.Combine(diffRoot, "lab-diff.json")));
            Assert.Equal(0, document.RootElement.GetProperty("summary").GetProperty("regressions").GetInt32());
        }
        finally
        {
            Directory.Delete(root, recursive: true);
        }
    }

    static LabSuiteRunResult CreateRun(
        string root,
        string name,
        int todo,
        long durationMs,
        ScenarioStatus actualStatus,
        string? diagnostic,
        bool alternateFormatting = false)
    {
        var generatedRoot = Path.Combine(root, name, "generated");
        Directory.CreateDirectory(generatedRoot);
        var generated = Path.Combine(generatedRoot, "Sample.cs");
        File.WriteAllText(generated, alternateFormatting
            ? "// another comment\npublic class Sample\n{\npublic void Run() { }\n}\n"
            : "// Generated by Migrator\npublic class Sample\n{\n    public void Run() { } // line 10\n}\n");

        var projectArtifacts = Path.Combine(root, name, "projects", "p01");
        return new LabSuiteRunResult
        {
            StartedAtUtc = DateTimeOffset.Parse("2026-07-30T10:00:00Z"),
            CompletedAtUtc = DateTimeOffset.Parse("2026-07-30T10:01:00Z"),
            Suite = "vertical",
            CorpusRoot = Path.Combine(root, name, "corpus"),
            ArtifactsRoot = Path.Combine(root, name),
            Summary = new LabSuiteSummary { Projects = 1 },
            Projects = new[]
            {
                new LabScenarioRunResult
                {
                    Id = "p01",
                    ExpectedStatus = ScenarioStatus.Pass,
                    ActualStatus = actualStatus,
                    ArtifactsDirectory = projectArtifacts,
                    DurationMs = durationMs,
                    SourceTests = new LabSourceTestSummary { Passed = 1, ExpectedPassed = 1 },
                    TargetTests = new LabSourceTestSummary { Passed = actualStatus == ScenarioStatus.Pass ? 1 : 0, ExpectedPassed = 1 },
                    Migration = new LabMigrationSummary
                    {
                        TodoComments = todo,
                        GeneratedFiles = new[] { generated }
                    },
                    ProjectVerify = new LabProjectVerifySummary
                    {
                        Status = diagnostic == null ? "passed" : "failed",
                        DiagnosticCategories = diagnostic == null ? Array.Empty<string>() : new[] { diagnostic },
                        Diagnostics = diagnostic == null ? Array.Empty<string>() : new[] { $"C:/temp/{Guid.NewGuid()}/Sample.cs: {diagnostic}" }
                    },
                    Quality = new LabQualityEvaluation { Passed = todo == 0 },
                    Oracle = new LabSemanticOracleSummary
                    {
                        Passed = actualStatus == ScenarioStatus.Pass,
                        Checks = new[]
                        {
                            new LabSemanticCheck { Kind = "dom-text", Expected = "ok", Actual = actualStatus == ScenarioStatus.Pass ? "ok" : "missing", Passed = actualStatus == ScenarioStatus.Pass }
                        }
                    }
                }
            }
        };
    }

    static string TempRoot()
    {
        var root = Path.Combine(Path.GetTempPath(), "migrator-lab-diff-tests-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(root);
        return root;
    }
}
