using Xunit;

namespace Migrator.Tests;

public class PublicLaunchPackTests
{
    [Fact]
    public void PublicLaunchPack_HasDemoWalkthroughRoadmapAndReleaseNotes()
    {
        var required = new[]
        {
            "docs/public-launch/README.md",
            "docs/public-launch/launch-checklist.md",
            "docs/public-launch/walkthrough.md",
            "docs/public-roadmap.md",
            "docs/release-notes/v0.6.0-preview.1.md",
            "examples/public-launch-demo/README.md",
            "examples/public-launch-demo/selenium-tests/LoginSmokeTest.cs",
            "examples/public-launch-demo/adapter-config.json",
            "examples/public-launch-demo/playwright-migrated/LoginSmokePlaywright.generated.cs",
            "examples/public-launch-demo/reports/before-after-report.md",
            "examples/github-actions/migration-pilot.yml",
        };

        foreach (var path in required)
            Assert.True(File.Exists(FindRepositoryFile(path)), $"Missing public launch asset: {path}");
    }

    [Fact]
    public void PublicLaunchPack_HasIssueTemplatesForExternalTriage()
    {
        var required = new[]
        {
            ".github/ISSUE_TEMPLATE/bug_report.yml",
            ".github/ISSUE_TEMPLATE/migration_gap.yml",
            ".github/ISSUE_TEMPLATE/profile_request.yml",
            ".github/ISSUE_TEMPLATE/config.yml",
        };

        foreach (var path in required)
            Assert.True(File.Exists(FindRepositoryFile(path)), $"Missing issue template: {path}");

        var migrationGap = File.ReadAllText(FindRepositoryFile(".github/ISSUE_TEMPLATE/migration_gap.yml"));
        Assert.Contains("unsupported-actions", migrationGap);
        Assert.Contains("unmapped-targets", migrationGap);

        var profileRequest = File.ReadAllText(FindRepositoryFile(".github/ISSUE_TEMPLATE/profile_request.yml"));
        Assert.Contains("Source-truth evidence", profileRequest);
        Assert.Contains("adapter config", profileRequest, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void PublicLaunchWalkthrough_ShowsInstallDoctorMigrateVerifyReportPath()
    {
        var walkthrough = File.ReadAllText(FindRepositoryFile("docs/public-launch/walkthrough.md"));

        Assert.Contains("dotnet tool install", walkthrough);
        Assert.Contains("--mode doctor", walkthrough);
        Assert.Contains("--mode migrate", walkthrough);
        Assert.Contains("--mode verify", walkthrough);
        Assert.Contains("before-after-report.md", walkthrough);
        Assert.Contains("assets/walkthrough/01-cli-help.svg", walkthrough);
        Assert.Contains("assets/walkthrough/04-report.svg", walkthrough);
    }

    [Fact]
    public void PublicLaunchDemo_UsesVersionedConfigAndReviewableGeneratedOutput()
    {
        var config = File.ReadAllText(FindRepositoryFile("examples/public-launch-demo/adapter-config.json"));
        var generated = File.ReadAllText(FindRepositoryFile("examples/public-launch-demo/playwright-migrated/LoginSmokePlaywright.generated.cs"));
        var report = File.ReadAllText(FindRepositoryFile("examples/public-launch-demo/reports/before-after-report.md"));

        Assert.Contains("adapter-config/v1", config);
        Assert.Contains("login-username", config);
        Assert.Contains("Generated by Migrator", generated);
        Assert.Contains("GetByTestId(\"login-username\")", generated);
        Assert.Contains("TODO", generated);
        Assert.Contains("no selector was invented", report, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("next safe action", report, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void PublicReadmesAndDocsIndex_LinkLaunchPack()
    {
        var readme = File.ReadAllText(FindRepositoryFile("README.md"));
        var readmeRu = File.ReadAllText(FindRepositoryFile("README.ru.md"));
        var docsIndex = File.ReadAllText(FindRepositoryFile("docs/README.md"));

        foreach (var text in new[] { readme, readmeRu })
        {
            Assert.Contains("examples/public-launch-demo/README.md", text);
            Assert.Contains("docs/public-launch/walkthrough.md", text);
            Assert.Contains("docs/public-roadmap.md", text);
        }

        Assert.Contains("public-launch/README.md", docsIndex);
        Assert.Contains("public-roadmap.md", docsIndex);
        Assert.Contains("release-notes/v0.6.0-preview.1.md", docsIndex);
    }

    static string FindRepositoryFile(string relativePath)
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir != null)
        {
            var candidate = Path.Combine(dir.FullName, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (File.Exists(candidate))
                return candidate;
            dir = dir.Parent;
        }

        throw new FileNotFoundException($"Could not find repository file: {relativePath}");
    }
}
