using Migrator.Core;
using Migrator.Core.Models;

namespace Migrator.Tests;

/// <summary>
/// Regression coverage for the honest conversion metrics on MigrationReport.
/// SuccessfullyConvertedTests keeps its legacy "no UnsupportedAction" definition (false
/// green: a test whose actions all fall back to TODOs still counts as converted).
/// GeneratedTests / FullyConvertedTests provide the formal, conservative signal built on
/// ExecutableTargetSemantics: a test is fully converted only when every source action
/// (and the shared setup) is provably emitted as executable target code.
/// </summary>
public sealed class SuccessfullyConvertedMetricsTests
{
    [Fact]
    public void CleanExecutableBody_IsGeneratedAndFullyConverted()
    {
        var model = File(
            Test("Clean", new ClickAction(
                10,
                TargetExpression.Mapped("page.Save", "#save", TargetKind.CssSelector))));

        var report = ReportBuilder.Build(model, GeneratedFrom("Clean"));

        Assert.Equal(1, report.GeneratedTests);
        Assert.Equal(1, report.FullyConvertedTests);
        Assert.Equal(1, report.SuccessfullyConvertedTests);
    }

    [Fact]
    public void ReviewRequiredWait_IsGeneratedAndSuccessfullyConvertedButNotFullyConverted()
    {
        // The legacy metric (no UnsupportedAction) reports this as converted even though
        // ExecutableTargetSemantics proves the renderer emits the wait as TODO/comment only.
        // FullyConvertedTests must not credit it.
        var wait = new WaitForAction(
            10,
            TargetExpression.Mapped("page.Loader", "#loader", TargetKind.CssSelector),
            sourceMethod: "WaitLoaderFinished",
            kind: WaitForKind.ReviewRequired);

        var model = File(Test("TodoOnly", wait));

        var report = ReportBuilder.Build(model, GeneratedFrom("TodoOnly", withTodo: true));

        Assert.Equal(1, report.GeneratedTests);
        Assert.Equal(0, report.FullyConvertedTests);
        Assert.Equal(1, report.SuccessfullyConvertedTests);
    }

    [Fact]
    public void EmptyBodyTest_IsNotGeneratedAndNotFullyConverted()
    {
        var model = File(new TestModel(
            "Empty",
            Category: null,
            CaseData: Array.Empty<TestCaseData>(),
            Parameters: Array.Empty<MethodParameterModel>(),
            BodyActions: Array.Empty<TestAction>()));

        var report = ReportBuilder.Build(model, GeneratedFrom("Empty"));

        Assert.Equal(0, report.GeneratedTests);
        Assert.Equal(0, report.FullyConvertedTests);
    }

    [Fact]
    public void MixedFile_CountsGeneratedAndFullyConvertedIndependently()
    {
        var model = new TestFileModel(
            FilePath: "Mixed.cs",
            Namespace: "Sample.Tests",
            ClassName: "MixedTests",
            BaseClassName: null,
            SetUpActions: Array.Empty<TestAction>(),
            Tests: new[]
            {
                Test("Clean", new ClickAction(
                    10,
                    TargetExpression.Mapped("page.Save", "#save", TargetKind.CssSelector))),
                Test("TodoOnly", new WaitForAction(
                    11,
                    TargetExpression.Mapped("page.Loader", "#loader", TargetKind.CssSelector),
                    sourceMethod: "WaitLoaderFinished",
                    kind: WaitForKind.ReviewRequired))
            });

        var report = ReportBuilder.Build(model, "// Generated by Migrator");

        Assert.Equal(2, report.GeneratedTests);
        Assert.Equal(1, report.FullyConvertedTests);
        Assert.Equal(2, report.SuccessfullyConvertedTests);
    }

    [Fact]
    public void SetupWithReviewRequiredWait_BlocksFullyConvertedForAllTests()
    {
        var model = new TestFileModel(
            FilePath: "SetupBlocked.cs",
            Namespace: "Sample.Tests",
            ClassName: "SetupBlockedTests",
            BaseClassName: null,
            SetUpActions: new TestAction[]
            {
                new WaitForAction(
                    5,
                    TargetExpression.Mapped("page.Busy", "#busy", TargetKind.CssSelector),
                    sourceMethod: "WaitBusinessState",
                    kind: WaitForKind.ReviewRequired)
            },
            Tests: new[]
            {
                Test("Clean", new ClickAction(
                    10,
                    TargetExpression.Mapped("page.Save", "#save", TargetKind.CssSelector)))
            });

        var report = ReportBuilder.Build(model, "// Generated by Migrator");

        Assert.Equal(1, report.GeneratedTests);
        Assert.Equal(0, report.FullyConvertedTests);
    }

    static TestFileModel File(TestModel test) =>
        new(
            FilePath: "Metrics.cs",
            Namespace: "Sample.Tests",
            ClassName: "MetricsTests",
            BaseClassName: null,
            SetUpActions: Array.Empty<TestAction>(),
            Tests: new[] { test });

    static TestModel Test(string name, TestAction action) =>
        new(
            name,
            Category: null,
            CaseData: Array.Empty<TestCaseData>(),
            Parameters: Array.Empty<MethodParameterModel>(),
            BodyActions: new[] { action });

    static string GeneratedFrom(string testName, bool withTodo = false) =>
        "// Generated by Migrator\n"
        + (withTodo ? "// TODO: await Page.Locator(\"#loader\").WaitForAsync(); // ReviewRequired\n" : string.Empty)
        + $"public class MetricsTests {{ public void {testName}() {{ }} }}";
}
