using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;

namespace Migrator.Core;

public sealed class DoctorFixPlanner
{
    readonly DoctorFixOptions _options;
    readonly List<DoctorFixAction> _actions = new();
    readonly List<string> _manualRecommendations = new();
    readonly List<string> _appliedFiles = new();
    readonly List<string> _skippedReasons = new();
    readonly List<PlannedWrite> _plannedWrites = new();

    public DoctorFixPlanner(DoctorFixOptions options)
    {
        _options = options;
    }

    public DoctorFixPlan BuildAndMaybeApply()
    {
        PlanWorkspaceFolders();
        PlanWorkspaceGitIgnore();
        PlanStarterConfigWhenMissing();
        PlanConfigNewFiles();
        PlanManualRecommendations();

        if (_options.Apply)
            ApplyWrites();
        else
            _skippedReasons.Add("Dry-run mode: no project/config files were written. Re-run with --fix --apply to write safe fixes.");

        var actionable = _actions.Count(a => !a.Mode.Equals("Recommendation", StringComparison.OrdinalIgnoreCase));
        var status = _options.Apply
            ? (_skippedReasons.Count == 0 ? "applied" : "partial")
            : actionable > 0 ? "planned" : "no-fixes";

        return new DoctorFixPlan(
            GeneratedAtUtc: DateTimeOffset.UtcNow,
            Status: status,
            Apply: _options.Apply,
            DryRun: !_options.Apply,
            InputPath: FullPathOrOriginal(_options.InputPath),
            WorkspacePath: FullPathOrOriginal(_options.WorkspacePath),
            ConfigPaths: _options.ConfigPaths.Select(FullPathOrOriginal).ToArray(),
            Actions: _actions.ToArray(),
            ManualRecommendations: _manualRecommendations.ToArray(),
            AppliedFiles: _appliedFiles.ToArray(),
            SkippedReasons: _skippedReasons.ToArray());
    }

    public static void WriteArtifacts(DoctorFixPlan plan, string outPath, string format)
    {
        Directory.CreateDirectory(outPath);
        var json = JsonSerializer.Serialize(plan, new JsonSerializerOptions { WriteIndented = true });
        var markdown = ToMarkdown(plan);
        var patch = ToPatch(plan);
        var report = ToReportMarkdown(plan);

        if (format is "json" or "both")
            File.WriteAllText(Path.Combine(outPath, "doctor-fix-plan.json"), json);
        if (format is "text" or "both")
        {
            File.WriteAllText(Path.Combine(outPath, "doctor-fix-plan.md"), markdown);
            File.WriteAllText(Path.Combine(outPath, "doctor-fix.patch"), patch);
            File.WriteAllText(Path.Combine(outPath, "doctor-fix-report.md"), report);
        }
    }

    void PlanWorkspaceFolders()
    {
        var workspace = FullPathOrOriginal(_options.WorkspacePath);
        foreach (var relative in new[] { "profiles", "state", "runs" })
        {
            var path = Path.Combine(workspace, relative);
            if (Directory.Exists(path))
                continue;

            AddAction(
                id: $"create-{relative}-folder",
                category: "workspace",
                safety: "safe",
                mode: "Automatic",
                path: path,
                description: $"Create missing migration workspace folder `{relative}`.",
                before: "missing",
                after: "directory exists",
                content: null,
                isDirectory: true);
        }
    }

    void PlanWorkspaceGitIgnore()
    {
        var path = Path.Combine(FullPathOrOriginal(_options.WorkspacePath), ".gitignore");
        if (File.Exists(path))
            return;

        var content = """
# Generated by selenium-pw-migrator doctor --fix.
# Keep reports and profiles reviewable, but ignore heavy transient run outputs.
runs/
*/bin/
*/obj/
*.tmp
*.bak
*.log
""";
        AddAction(
            id: "create-workspace-gitignore",
            category: "workspace",
            safety: "safe",
            mode: "Automatic",
            path: path,
            description: "Create `.gitignore` for generated migration artifacts.",
            before: "missing",
            after: content,
            content: content,
            isDirectory: false);
    }

    void PlanStarterConfigWhenMissing()
    {
        if (_options.ConfigPaths.Length > 0)
            return;

        var path = Path.Combine(FullPathOrOriginal(_options.WorkspacePath), "profiles", "adapter-config.json");
        if (File.Exists(path))
            return;

        var targetFramework = NormalizeTargetFramework(_options.TargetTestFramework);
        var content = CreateStarterConfigJson(targetFramework);
        AddAction(
            id: "create-starter-adapter-config",
            category: "config",
            safety: "safe",
            mode: "Automatic",
            path: path,
            description: "Create starter adapter config because no --config layer was provided.",
            before: "missing",
            after: content,
            content: content,
            isDirectory: false);
    }

    void PlanConfigNewFiles()
    {
        foreach (var configPath in _options.ConfigPaths.Where(File.Exists))
        {
            var originalText = File.ReadAllText(configPath);
            JsonObject? obj;
            try
            {
                obj = JsonNode.Parse(originalText) as JsonObject;
            }
            catch (Exception ex)
            {
                _manualRecommendations.Add($"Config `{configPath}` is not valid JSON for auto-fix planning: {ex.Message}. Fix it manually, then run doctor again.");
                continue;
            }

            if (obj == null)
            {
                _manualRecommendations.Add($"Config `{configPath}` is not a JSON object. Replace it manually with adapter-config object shape.");
                continue;
            }

            var changed = false;
            changed |= EnsureString(obj, "$schema", "./adapter-config.schema.json");
            changed |= EnsureString(obj, "SchemaVersion", ProjectAdapterConfig.CurrentSchemaVersion);
            changed |= EnsureTestHost(obj, NormalizeTargetFramework(_options.TargetTestFramework));
            changed |= EnsureVerificationDefaults(obj);

            if (!changed)
                continue;

            var newPath = configPath + ".doctor.new";
            var newText = ToIndentedJson(obj);
            AddAction(
                id: "write-config-doctor-new",
                category: "config",
                safety: "safe-new-file",
                mode: "Automatic",
                path: newPath,
                description: "Write reviewed config repair candidate as `.doctor.new` without overwriting the original config.",
                before: originalText,
                after: newText,
                content: newText,
                isDirectory: false);
        }
    }

    void PlanManualRecommendations()
    {
        var input = _options.InputPath;
        if (Directory.Exists(input))
        {
            var pomCandidates = SafeEnumerateFiles(input, "*.cs")
                .Where(path => path.Contains("Page", StringComparison.OrdinalIgnoreCase)
                            || path.Contains("Pom", StringComparison.OrdinalIgnoreCase)
                            || path.Contains("PageObject", StringComparison.OrdinalIgnoreCase))
                .Take(3)
                .ToArray();

            if (pomCandidates.Length > 0)
            {
                _manualRecommendations.Add("POM/source-truth mappings are intentionally recommendation-only. Run `--mode index-pom` or `--mode helper-inventory`, review evidence, then add selector/method mappings manually.");
            }
        }

        _manualRecommendations.Add("Doctor fix mode never edits Selenium source tests and never invents selectors. Selector/POM mappings stay manual unless backed by explicit source truth.");
    }

    void ApplyWrites()
    {
        foreach (var write in _plannedWrites)
        {
            try
            {
                if (!IsAllowedWritePath(write.Path))
                {
                    _skippedReasons.Add($"Skipped unsafe write outside workspace/config paths: {write.Path}");
                    continue;
                }

                if (write.IsDirectory)
                {
                    Directory.CreateDirectory(write.Path);
                    _appliedFiles.Add(write.Path);
                    MarkApplied(write.Path);
                    continue;
                }

                if (File.Exists(write.Path) && !write.Path.EndsWith(".doctor.new", StringComparison.OrdinalIgnoreCase))
                {
                    _skippedReasons.Add($"Skipped existing file without .doctor.new suffix: {write.Path}");
                    continue;
                }

                var dir = Path.GetDirectoryName(write.Path);
                if (!string.IsNullOrWhiteSpace(dir))
                    Directory.CreateDirectory(dir);
                File.WriteAllText(write.Path, write.Content ?? string.Empty);
                _appliedFiles.Add(write.Path);
                MarkApplied(write.Path);
            }
            catch (Exception ex)
            {
                _skippedReasons.Add($"Failed to apply {write.Path}: {ex.Message}");
            }
        }
    }

    bool IsAllowedWritePath(string path)
    {
        var full = FullPathOrOriginal(path);
        var workspace = FullPathOrOriginal(_options.WorkspacePath).TrimEnd(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar) + Path.DirectorySeparatorChar;
        if (full.Equals(FullPathOrOriginal(_options.WorkspacePath), StringComparison.OrdinalIgnoreCase)
            || full.StartsWith(workspace, StringComparison.OrdinalIgnoreCase))
            return true;

        foreach (var configPath in _options.ConfigPaths)
        {
            var configFull = FullPathOrOriginal(configPath);
            if (full.Equals(configFull + ".doctor.new", StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    void AddAction(string id, string category, string safety, string mode, string path, string description, string before, string after, string? content, bool isDirectory)
    {
        _actions.Add(new DoctorFixAction(
            Id: id,
            Category: category,
            Safety: safety,
            Mode: mode,
            Status: _options.Apply ? "planned" : "dry-run",
            Path: FullPathOrOriginal(path),
            Description: description,
            Before: before,
            After: after,
            RequiresApply: true));
        _plannedWrites.Add(new PlannedWrite(FullPathOrOriginal(path), content, isDirectory));
    }

    void MarkApplied(string path)
    {
        for (var i = 0; i < _actions.Count; i++)
        {
            if (_actions[i].Path.Equals(path, StringComparison.OrdinalIgnoreCase))
                _actions[i] = _actions[i] with { Status = "applied" };
        }
    }

    static bool EnsureString(JsonObject obj, string key, string value)
    {
        if (obj.TryGetPropertyValue(key, out var existing)
            && existing is JsonValue existingValue
            && existingValue.TryGetValue<string>(out var s)
            && !string.IsNullOrWhiteSpace(s))
            return false;
        obj[key] = value;
        return true;
    }

    static bool EnsureTestHost(JsonObject obj, string targetFramework)
    {
        var changed = false;
        var testHost = obj["TestHost"] as JsonObject;
        if (testHost == null)
        {
            testHost = new JsonObject();
            obj["TestHost"] = testHost;
            changed = true;
        }

        if (!testHost.TryGetPropertyValue("TargetTestFramework", out var existing)
            || existing == null
            || existing.GetValueKind() == JsonValueKind.Null
            || string.IsNullOrWhiteSpace(existing.ToString()))
        {
            testHost["TargetTestFramework"] = targetFramework;
            changed = true;
        }

        return changed;
    }

    static bool EnsureVerificationDefaults(JsonObject obj)
    {
        var changed = false;
        var verification = obj["Verification"] as JsonObject;
        if (verification == null)
        {
            verification = new JsonObject();
            obj["Verification"] = verification;
            changed = true;
        }

        changed |= EnsureString(verification, "TargetFramework", "net8.0");
        changed |= EnsureString(verification, "BaseDirectory", ".");
        changed |= EnsureString(verification, "BuildWorkingDirectory", ".");
        changed |= EnsureBool(verification, "AutoDiscoverNearestProject", true);
        changed |= EnsureBool(verification, "AutoDiscoverProjectReferences", true);
        changed |= EnsureBool(verification, "AutoDiscoverBuildFiles", true);
        changed |= EnsureBool(verification, "DisableDefaultPackageReferences", false);
        return changed;
    }

    static bool EnsureBool(JsonObject obj, string key, bool value)
    {
        if (obj.TryGetPropertyValue(key, out var existing) && existing != null && existing.GetValueKind() is JsonValueKind.True or JsonValueKind.False)
            return false;
        obj[key] = value;
        return true;
    }

    static string CreateStarterConfigJson(string targetFramework)
    {
        var knownTestIdAttributes = new JsonArray();
        knownTestIdAttributes.Add("data-testid");
        knownTestIdAttributes.Add("data-test-id");
        knownTestIdAttributes.Add("data-test");
        knownTestIdAttributes.Add("data-tid");

        var obj = new JsonObject
        {
            ["$schema"] = "./adapter-config.schema.json",
            ["SchemaVersion"] = ProjectAdapterConfig.CurrentSchemaVersion,
            ["SourceProjectName"] = "SeleniumTests",
            ["LocatorSettings"] = new JsonObject
            {
                ["DefaultTestIdAttribute"] = "data-testid",
                ["KnownTestIdAttributes"] = knownTestIdAttributes
            },
            ["TestHost"] = new JsonObject
            {
                ["TargetTestFramework"] = targetFramework,
                ["BaseClass"] = "PageTest",
                ["TargetPageVariable"] = "Page"
            },
            ["Verification"] = new JsonObject
            {
                ["TargetFramework"] = "net8.0",
                ["BaseDirectory"] = ".",
                ["BuildWorkingDirectory"] = ".",
                ["AutoDiscoverNearestProject"] = true,
                ["AutoDiscoverProjectReferences"] = true,
                ["AutoDiscoverBuildFiles"] = true,
                ["DisableDefaultPackageReferences"] = false
            },
            ["UiTargets"] = new JsonArray(),
            ["PageObjects"] = new JsonArray(),
            ["Methods"] = new JsonArray()
        };

        return ToIndentedJson(obj);
    }

    static string ToIndentedJson(JsonNode node)
    {
        using var stream = new MemoryStream();
        using (var writer = new Utf8JsonWriter(stream, new JsonWriterOptions { Indented = true }))
        {
            node.WriteTo(writer);
        }

        return Encoding.UTF8.GetString(stream.ToArray()) + Environment.NewLine;
    }

    static string NormalizeTargetFramework(string? value)
    {
        if (value != null && value.Equals("xunit", StringComparison.OrdinalIgnoreCase))
            return "xunit";
        return "nunit";
    }

    static string[] SafeEnumerateFiles(string inputPath, string pattern)
    {
        try
        {
            return Directory.EnumerateFiles(inputPath, pattern, SearchOption.AllDirectories)
                .Where(path => !path.Replace('\\', '/').Contains("/bin/", StringComparison.OrdinalIgnoreCase)
                            && !path.Replace('\\', '/').Contains("/obj/", StringComparison.OrdinalIgnoreCase)
                            && !path.Replace('\\', '/').Contains("/.git/", StringComparison.OrdinalIgnoreCase))
                .ToArray();
        }
        catch
        {
            return Array.Empty<string>();
        }
    }

    static string FullPathOrOriginal(string path)
    {
        if (string.IsNullOrWhiteSpace(path))
            return path;
        try { return Path.GetFullPath(path); }
        catch { return path; }
    }

    static string ToMarkdown(DoctorFixPlan plan)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Doctor Fix Plan");
        sb.AppendLine();
        sb.AppendLine($"- **Generated**: {plan.GeneratedAtUtc:yyyy-MM-dd HH:mm:ss zzz}");
        sb.AppendLine($"- **Status**: `{plan.Status}`");
        sb.AppendLine($"- **Mode**: {(plan.Apply ? "apply" : "dry-run")}");
        sb.AppendLine($"- **Input**: `{plan.InputPath}`");
        sb.AppendLine($"- **Workspace**: `{plan.WorkspacePath}`");
        sb.AppendLine();
        sb.AppendLine("## Safe automatic actions");
        sb.AppendLine();
        sb.AppendLine("| Status | Category | Safety | Path | Description |");
        sb.AppendLine("|---|---|---|---|---|");
        foreach (var action in plan.Actions)
            sb.AppendLine($"| {Escape(action.Status)} | {Escape(action.Category)} | {Escape(action.Safety)} | `{Escape(action.Path)}` | {Escape(action.Description)} |");
        if (plan.Actions.Length == 0)
            sb.AppendLine("| no-fixes | - | - | - | No safe automatic fixes were needed. |");
        sb.AppendLine();
        sb.AppendLine("## Manual recommendations");
        foreach (var item in plan.ManualRecommendations)
            sb.AppendLine($"- {item}");
        if (plan.ManualRecommendations.Length == 0)
            sb.AppendLine("- None.");
        return sb.ToString();
    }

    static string ToReportMarkdown(DoctorFixPlan plan)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Doctor Fix Report");
        sb.AppendLine();
        sb.AppendLine(plan.Apply
            ? "Safe fixes were applied only inside the selected workspace or as `.doctor.new` config candidates."
            : "Dry-run only: no project/config files were written except doctor report artifacts.");
        sb.AppendLine();
        sb.AppendLine("## Applied files");
        foreach (var file in plan.AppliedFiles)
            sb.AppendLine($"- `{file}`");
        if (plan.AppliedFiles.Length == 0)
            sb.AppendLine("- None.");
        sb.AppendLine();
        sb.AppendLine("## Skipped / notes");
        foreach (var reason in plan.SkippedReasons)
            sb.AppendLine($"- {reason}");
        if (plan.SkippedReasons.Length == 0)
            sb.AppendLine("- None.");
        return sb.ToString();
    }

    static string ToPatch(DoctorFixPlan plan)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# doctor-fix.patch");
        sb.AppendLine("# Review-only summary. Config edits are emitted as .doctor.new files; originals are not overwritten.");
        foreach (var action in plan.Actions)
        {
            sb.AppendLine();
            sb.AppendLine($"# {action.Id}: {action.Description}");
            sb.AppendLine($"--- {action.Path}.before");
            sb.AppendLine($"+++ {action.Path}.after");
            sb.AppendLine("@@");
            if (action.Before == "missing")
                sb.AppendLine("-<missing>");
            else
                AppendLimited(sb, action.Before, '-');
            if (action.After == "directory exists")
                sb.AppendLine("+<directory exists>");
            else
                AppendLimited(sb, action.After, '+');
        }
        return sb.ToString();
    }

    static void AppendLimited(StringBuilder sb, string text, char prefix)
    {
        var lines = text.Replace("\r\n", "\n").Split('\n').Take(160).ToArray();
        foreach (var line in lines)
            sb.Append(prefix).AppendLine(line);
        if (text.Count(c => c == '\n') > lines.Length)
            sb.Append(prefix).AppendLine("... truncated ...");
    }

    static string Escape(string value) => value.Replace("|", "\\|").Replace("\r", " ").Replace("\n", " ");

    sealed record PlannedWrite(string Path, string? Content, bool IsDirectory);
}
