// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace PublicLaunchDemo.SeleniumTests.Playwright;

// WARNING: 1 unsupported setup action found. See TODO comments below.

public class LoginSmokeTestPlaywright : PageTest
{
    [SetUp]
    public async Task SetUp()
    {
        // TODO: UNSUPPORTED [Statement type not yet supported by extractor]
        //   page = Navigation.OpenLoginPage();
        // [ValidateLoading] page.Loader.ValidateLoading()
        // TODO: add project navigation mapping or target PageObject setup.
    }

    [Test]
    public async Task LoginWithValidCredentials()
    {
        await Page.GetByTestId("login-username").FillAsync("admin@example.test");
        await Page.GetByTestId("login-password").FillAsync("correct-horse-battery-staple");
        await Page.GetByRole(AriaRole.Button, new() { Name = "Sign in" }).ClickAsync();
        await Expect(Page.GetByTestId("login-success-toast")).ToBeVisibleAsync();
    }
}
