// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System;
using System.Threading.Tasks;

namespace Example.E2ETests.Tests.NonCategory.Playwright;

// WARNING: some actions need manual review. See TODO comments below.

public class ButtonTestsPlaywright : PageTest
{

	[SetUp]
	public async Task SetUp()
	{
		// TODO: raw statement — review: var pagef = Navigation.OpenRegistryAgentPage()
		// TODO: references unavailable symbol(s) 'Navigation' — verify in target
		// TODO: depends on unresolved symbol 'pagef'
		//   page = pagef
		// TODO: map product-state wait target: page.Loader
		// await Expect((locator)).ToBeHiddenAsync(); // line 17
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckSearchButton()
	{
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SideMenuButtonSearch.Click()
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SearchTextArea.Visible.Should()
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SearchTextArea.Visible.Should()
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckFeedBackButton()
	{
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SideMenuButtonFeedback.Visible.Should()
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SideMenuButtonFeedback.Text.Should("Leave feedback")
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckButtonCatalogsPartners()
	{
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SideMenuCatalogs.Click()
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.SideMenuCatalogsPartners.Click()
		// await Expect(Page).ToHaveURLAsync(Urls.BaseUrlCatalogPartners); // line 43
		// TODO: URL assertion uses external variable — verify and uncomment
		// TODO: depends on unresolved symbol 'page'
		//   page.MenuItems.Error.Visible.Should()
	}

}
