// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace ArBilling.E2ETests.Tests.NonCategory.Playwright;

// WARNING: 2 unsupported action(s) found. See TODO comments below.

public class ButtonTestsPlaywright : PageTest
{

	[SetUp]
	public async Task SetUp()
	{
		// TODO: UNSUPPORTED [Statement type not yet supported by extractor]
		//   var pagef = Navigation.OpenRegistryAgentPage();
		// TODO: UNSUPPORTED [Statement type not yet supported by extractor]
		//   page = pagef;
		// [ValidateLoading] page.Loader.ValidateLoading() // line 17
		// TODO: manual review needed
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckSearchButton()
	{
		await Page.GetByTestId("side-menu-search").ClickAsync(); // line 24
		// [EqualTo] page.MenuItems.SearchTextArea.Visible.Wait().EqualTo(true) // line 25
		// TODO: manual review needed
		// [EqualTo] page.MenuItems.SearchTextArea.Visible.Wait().EqualTo(false) // line 26
		// TODO: manual review needed
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckFeedBackButton()
	{
		// [EqualTo] page.MenuItems.SideMenuButtonFeedback.Visible.Wait().EqualTo(true) // line 33
		// TODO: manual review needed
		// [Be] page.MenuItems.SideMenuButtonFeedback.Text.Get().Should().Be("Оставить отзыв") // line 34
		// TODO: manual review needed
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckButtonCatalogsPartners()
	{
		await Page.GetByTestId("side-menu-catalogs").ClickAsync(); // line 41
		await Page.GetByTestId("side-menu-catalogs-partners").ClickAsync(); // line 42
		// [Be] WebDriver.Url.Should().Be(Urls.BaseUrlCatalogPartners) // line 43
		// TODO: manual review needed
		// [EqualTo] page.MenuItems.Error.Visible.Wait().EqualTo(false) // line 44
		// TODO: manual review needed
	}

}
