// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace ArBilling.E2ETests.Tests.Functional.Playwright;

// WARNING: 3 unsupported action(s) found. See TODO comments below.

public class WidgetPlaywright : PageTest
{

	[SetUp]
	public async Task SetUp()
	{
		// TODO: UNSUPPORTED [Statement type not yet supported by extractor]
		//   var pagef = Navigation.OpenSearchPage();
		// [ValidateLoading] pagef.Loader.ValidateLoading() // line 18
		// TODO: manual review needed
		// TODO: UNSUPPORTED [Statement type not yet supported by extractor]
		//   var lightbox = pagef.WidgetButton.ClickAndOpen<WidgetPage>();
		// TODO: UNSUPPORTED [Statement type not yet supported by extractor]
		//   page = lightbox;
		// [EqualTo] page.User.Visible.Wait().EqualTo(true) // line 21
		// TODO: manual review needed
		// [EqualTo] page.FuterUser.Visible.Wait().EqualTo(true) // line 22
		// TODO: manual review needed
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckUserToWidget()
	{
		await Page.GetByTestId("widget-user").ClickAsync(); // line 29
		// [InputTextAndSelectValue] page.UserInput.InputTextAndSelectValue("Selenium-администатор") // line 30
		// TODO: manual review needed
		// [EqualTo] page.FuterUser.Visible.Wait().EqualTo(true) // line 31
		// TODO: manual review needed
		// [NotBeEmpty] page.FuterUser.Text.Get().Should().NotBeEmpty() // line 32
		// TODO: manual review needed
	}

	[Test]
	public async Task CheckDateToWidget()
	{
		// [ManualInputValue] page.WidgetDate.ManualInputValue("Март", "2025", 22) // line 38
		// TODO: manual review needed
		// [ValidateLoading] page.Loader.ValidateLoading() // line 39
		// TODO: manual review needed
		// [EqualTo] page.FuterUser.Visible.Wait().EqualTo(true) // line 40
		// TODO: manual review needed
		// [NotBeEmpty] page.FuterUser.Text.Get().Should().NotBeEmpty() // line 41
		// TODO: manual review needed
	}

	[Test]
	public async Task CheckSearchToWidget()
	{
		await Page.GetByTestId("widget-search").FillAsync("Отправка в Диадок АНО ДПО 12.2022 (СЦ 0669)"); // line 47
		await Page.GetByTestId("widget-search").PressAsync("Enter"); // line 48
		// [ValidateLoading] page.Loader.ValidateLoading() // line 49
		// TODO: manual review needed
		// [WaitPresence] page.FuterUser.WaitPresence() // line 50
		// TODO: manual review needed
		// [NotBeEmpty] page.FuterUser.Text.Get().Should().NotBeEmpty() // line 51
		// TODO: manual review needed
	}

}
