// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright;
using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System;
using System.Threading.Tasks;

namespace MyProduct.E2ETests.Tests.Playwright;

// Teaching-demo expected output. Keep this file small and readable: it is meant
// to explain AST action recognition and source-truth locator mapping, not to be
// a complete production fixture scaffold.

public class LoginTeachingTestPlaywright : PageTest
{
    [SetUp]
    public async Task SetUp()
    {
        await Page.GotoAsync("/login"); // line 13
        // MIGRATOR: source statement suppressed by adapter-config // line 14
        // source suppressed: page.WaitUntilReady()
    }

    [Test]
    public async Task ValidUserCanSignIn()
    {
        await Page.GetByTestId("login-email").FillAsync("alex@example.com"); // line 20
        await Page.GetByTestId("login-password").FillAsync("correct horse battery staple"); // line 21
        await Page.GetByTestId("sign-in").ClickAsync(); // line 22

        await Expect(Page.GetByTestId("dashboard-title")).ToBeVisibleAsync(); // line 24
        await Expect(Page.GetByTestId("dashboard-title")).ToContainTextAsync("Dashboard"); // line 25
    }

    [Test]
    public async Task EmptyPasswordShowsValidation()
    {
        await Page.GetByTestId("login-email").FillAsync("alex@example.com"); // line 31
        await Page.GetByTestId("sign-in").ClickAsync(); // line 32

        await Expect(Page.GetByTestId("password-error")).ToContainTextAsync("Password is required"); // line 34
    }
}
