// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace MyProduct.E2ETests.Tests.Playwright;

// Teaching-demo expected output. Keep this file small and readable: it is meant
// to explain AST action recognition and source-truth locator mapping, not to be
// a complete production fixture scaffold.

public class LoginTeachingTestPlaywright : PageTest
{
    [SetUp]
    public async Task SetUp()
    {
        // TODO: source setup preserved for review.
        //   page = Navigation.OpenLoginPage();
        // [SuppressedMethods] page.WaitUntilReady() / Loader.ValidateLoading()
        // Prefer moving this to a Playwright fixture or explicit navigation step.
    }

    [Test]
    public async Task ValidUserCanSignIn()
    {
        await Page.GetByTestId("login-email").FillAsync("alex@example.com");
        await Page.GetByTestId("login-password").FillAsync("correct horse battery staple");
        await Page.GetByTestId("sign-in").ClickAsync();

        await Expect(Page.GetByTestId("dashboard-title")).ToBeVisibleAsync();
        await Expect(Page.GetByTestId("dashboard-title")).ToContainTextAsync("Dashboard");
    }

    [Test]
    public async Task EmptyPasswordShowsValidation()
    {
        await Page.GetByTestId("login-email").FillAsync("alex@example.com");
        await Page.GetByTestId("sign-in").ClickAsync();

        await Expect(Page.GetByTestId("password-error")).ToContainTextAsync("Password is required");
    }
}
