using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Migrator.Core;
using Migrator.Core.Models;

namespace Migrator.PlaywrightDotNet;

internal enum DotNetTargetTestFramework
{
    NUnit,
    XUnit
}

internal sealed record DotNetTestFileClassLayout(
    string? TargetNamespace,
    string ClassName,
    string BaseClass,
    string Inheritance);

/// <summary>
/// Renders language/test-framework scaffold around the generated Playwright .NET test body.
///
/// This component intentionally owns only file/class wrapper concerns: banner, usings,
/// namespace, class attributes, class declaration, and target test framework resolution.
/// Action rendering stays in <see cref="PlaywrightDotNetRenderer"/> for now and will be
/// extracted in later MIG-XL-03 slices.
/// </summary>
internal static class DotNetTestFileScaffoldRenderer
{
    public static DotNetTargetTestFramework ResolveTargetTestFramework(TestHostConfig? testHost)
    {
        var configured = testHost?.TargetTestFramework;
        if (!string.IsNullOrWhiteSpace(configured))
        {
            var normalized = configured.Trim().ToLowerInvariant();
            if (normalized is "xunit" or "x-unit")
                return DotNetTargetTestFramework.XUnit;
            if (normalized is "nunit" or "n-unit")
                return DotNetTargetTestFramework.NUnit;
        }

        if (testHost?.Usings?.Any(u =>
                u.Contains("Xunit", StringComparison.OrdinalIgnoreCase)) == true)
            return DotNetTargetTestFramework.XUnit;

        return DotNetTargetTestFramework.NUnit;
    }

    public static DotNetTestFileClassLayout CreateClassLayout(
        TestFileModel model,
        DotNetTargetTestFramework targetTestFramework,
        bool hasGeneratedSetup)
    {
        var testHost = model.TestHost;
        var targetNamespace = testHost?.Namespace ?? model.Namespace;
        var className = testHost?.ClassName ?? (model.ClassName + "Playwright");
        var baseClass = testHost?.BaseClass ?? "PageTest";
        var inheritance = targetTestFramework == DotNetTargetTestFramework.XUnit && hasGeneratedSetup
            ? $"{baseClass}, IAsyncLifetime"
            : baseClass;

        return new DotNetTestFileClassLayout(targetNamespace, className, baseClass, inheritance);
    }

    public static bool HasTodoWarning(TestFileModel model) =>
        model.Tests.SelectMany(t => t.BodyActions)
            .Concat(model.SetUpActions)
            .Any(a => a is UnsupportedAction or RawStatementAction or (MappedMethodInvocationAction { RequiresReview: true }));

    public static void AppendFilePreamble(
        StringBuilder sb,
        TestFileModel model,
        DotNetTargetTestFramework targetTestFramework,
        DotNetTestFileClassLayout classLayout)
    {
        sb.AppendLine("// Generated by Migrator — Selenium C# → Playwright .NET");
        sb.AppendLine();

        if (string.IsNullOrEmpty(classLayout.TargetNamespace))
            return;

        var testHost = model.TestHost;
        var renderedUsings = new HashSet<string>(StringComparer.Ordinal);
        void AppendUsing(string usingName)
        {
            if (renderedUsings.Add(usingName))
                sb.AppendLine($"using {usingName};");
        }

        // Playwright renderer always needs these core usings. Test-framework-specific
        // usings are selected by TestHost.TargetTestFramework instead of being
        // hardcoded to NUnit.
        var configuredUsings = testHost?.Usings ?? Array.Empty<string>();
        var hasConfiguredPlaywrightXunitUsing = configuredUsings.Any(u =>
            u.Contains("Playwright", StringComparison.OrdinalIgnoreCase) &&
            u.Contains("Xunit", StringComparison.OrdinalIgnoreCase));

        AppendUsing("Microsoft.Playwright");
        if (targetTestFramework == DotNetTargetTestFramework.XUnit)
        {
            if (!hasConfiguredPlaywrightXunitUsing)
                AppendUsing("Microsoft.Playwright.Extensions.Xunit");
            AppendUsing("Xunit");
        }
        else
        {
            AppendUsing("Microsoft.Playwright.NUnit");
            AppendUsing("NUnit.Framework");
        }

        AppendUsing("System");
        AppendUsing("System.Threading.Tasks");

        // Additional host-specific usings from config
        if (configuredUsings.Length > 0)
        {
            foreach (var @using in configuredUsings)
                AppendUsing(@using);
        }

        sb.AppendLine();
        // Backward compatibility: without TestHost, use .Playwright suffix
        var nsSuffix = testHost != null ? string.Empty : ".Playwright";
        sb.AppendLine($"namespace {classLayout.TargetNamespace}{nsSuffix};");
        sb.AppendLine();
    }

    public static void AppendTodoWarning(StringBuilder sb)
    {
        sb.AppendLine("// WARNING: some actions need manual review. See TODO comments below.");
        sb.AppendLine();
    }

    public static void AppendClassDeclaration(
        StringBuilder sb,
        TestHostConfig? testHost,
        DotNetTestFileClassLayout classLayout)
    {
        // Class attributes
        if (testHost?.ClassAttributes != null && testHost.ClassAttributes.Length > 0)
        {
            foreach (var attr in testHost.ClassAttributes)
                sb.AppendLine($"[{attr}]");
        }

        sb.AppendLine($"public class {classLayout.ClassName} : {classLayout.Inheritance}");
        sb.AppendLine("{");
        sb.AppendLine();
    }
}
