using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Migrator.Core;
using Migrator.Core.Models;

namespace Migrator.PlaywrightDotNet;

public class PlaywrightDotNetRenderer : IRenderer
{
    readonly string _indent;
    int _tempVarCounter = 0;
    readonly HashSet<string> _methodScopeVars = new();
    readonly Dictionary<string, string> _sourceVarMap = new();
    readonly HashSet<string> _blockedSymbols = new(StringComparer.Ordinal);
    HashSet<string> _sourceOnlyIdentifiers = new(StringComparer.Ordinal);
    HashSet<string> _setupBlockedSymbols = new(StringComparer.Ordinal);
    HashSet<string> _setupDeclaredVars = new(StringComparer.Ordinal);
    readonly HashSet<string> _localAliases = new(StringComparer.Ordinal);
    readonly HashSet<string> _targetLocals = new(StringComparer.Ordinal);
    HashSet<string> _targetKnownTypes = new(StringComparer.Ordinal);
    HashSet<string> _targetKnownIdentifiers = new(StringComparer.Ordinal);
    bool _useAssertionsExpect = false;

    public PlaywrightDotNetRenderer(string indent = "\t")
    {
        _indent = indent;
    }

    public string Render(TestFileModel model)
    {
        _tempVarCounter = 0;
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Migrator — Selenium C# → Playwright .NET");
        sb.AppendLine();

        var testHost = model.TestHost;
        _sourceOnlyIdentifiers = new HashSet<string>(
            model.SourceOnlyIdentifiers ?? Array.Empty<string>(),
            StringComparer.Ordinal);
        _targetKnownTypes = new HashSet<string>(
            model.TargetKnownTypes ?? Array.Empty<string>(),
            StringComparer.Ordinal);
        _targetKnownIdentifiers = new HashSet<string>(
            model.TargetKnownIdentifiers ?? Array.Empty<string>(),
            StringComparer.Ordinal);
        var targetNamespace = testHost?.Namespace ?? model.Namespace;
        var className = testHost?.ClassName ?? (model.ClassName + "Playwright");
        var baseClass = testHost?.BaseClass ?? "PageTest";
        _useAssertionsExpect = baseClass != "PageTest";
        var hasTestHostSetup = testHost?.SetUpStatements != null && testHost.SetUpStatements.Length > 0;

        // Usings
        if (!string.IsNullOrEmpty(targetNamespace))
        {
            // Playwright renderer always needs these core usings
            sb.AppendLine("using Microsoft.Playwright;");
            sb.AppendLine("using Microsoft.Playwright.NUnit;");
            sb.AppendLine("using NUnit.Framework;");
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Threading.Tasks;");
            // Additional host-specific usings from config
            if (testHost?.Usings != null && testHost.Usings.Length > 0)
            {
                var coreUsings = new HashSet<string> { "Microsoft.Playwright", "Microsoft.Playwright.NUnit", "NUnit.Framework", "System", "System.Threading.Tasks" };
                foreach (var @using in testHost.Usings)
                {
                    if (!coreUsings.Contains(@using))
                        sb.AppendLine($"using {@using};");
                }
            }
            sb.AppendLine();
            // Backward compatibility: without TestHost, use .Playwright suffix
            var nsSuffix = testHost != null ? string.Empty : ".Playwright";
            sb.AppendLine($"namespace {targetNamespace}{nsSuffix};");
            sb.AppendLine();
        }

        var hasTodoActions = model.Tests.SelectMany(t => t.BodyActions)
            .Concat(model.SetUpActions)
            .Any(a => a is UnsupportedAction or RawStatementAction or (MappedMethodInvocationAction { RequiresReview: true }));

        if (hasTodoActions)
        {
            sb.AppendLine("// WARNING: some actions need manual review. See TODO comments below.");
            sb.AppendLine();
        }

        // Class attributes
        if (testHost?.ClassAttributes != null && testHost.ClassAttributes.Length > 0)
        {
            foreach (var attr in testHost.ClassAttributes)
                sb.AppendLine($"[{attr}]");
        }

        sb.AppendLine($"public class {className} : {baseClass}");
        sb.AppendLine("{");
        sb.AppendLine();

        // Setup method — collect fixture-scoped blocked symbols for downstream test body blocking
        _setupBlockedSymbols.Clear();
        _setupDeclaredVars.Clear();
        if (hasTestHostSetup)
        {
            ResetMethodScope();
            RenderHostSetUp(sb, testHost!.SetUpStatements!, model.SetUpActions);
            sb.AppendLine();
        }
        else if (model.SetUpActions.Any())
        {
            ResetMethodScope();
            RenderSetUp(sb, model.SetUpActions);
            // After rendering setup, transfer blocked symbols to a fixture-level set
            foreach (var symbol in _blockedSymbols)
                _setupBlockedSymbols.Add(symbol);
            sb.AppendLine();
        }

        foreach (var test in model.Tests)
        {
            RenderTest(sb, test);
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    void RenderHostSetUp(StringBuilder sb, string[] hostStatements, IEnumerable<TestAction> originalActions)
    {
        sb.AppendLine($"{_indent}[SetUp]");
        sb.AppendLine($"{_indent}public async Task SetUp()");
        sb.AppendLine($"{_indent}{{");

        // Render configured setup statements
        foreach (var stmt in hostStatements)
            sb.AppendLine($"{_indent}{_indent}{stmt}");

        // Analyze original setup actions for blocked symbols — even though they are not
        // rendered as active code, variables declared/assigned in unresolved original actions
        // must be blocked so downstream test body actions are not left active.
        _blockedSymbols.Clear();
        foreach (var action in originalActions)
        {
            AnalyzeSetupActionForBlocking(action);
        }
        // Transfer to fixture-level blocked symbols for downstream test body blocking
        foreach (var symbol in _blockedSymbols)
            _setupBlockedSymbols.Add(symbol);

        // Preserve original mapped setup actions as comments for reference
        if (originalActions.Any())
        {
            sb.AppendLine();
            sb.AppendLine($"{_indent}{_indent}// Original Selenium setup (mapped):");
            foreach (var action in originalActions)
                RenderActionAsComment(sb, action);
        }

        sb.AppendLine($"{_indent}}}");
    }

    /// <summary>
    /// Analyzes a setup action for declared/assigned variables that should be blocked.
    /// Used by RenderSetUp (active rendering) and RenderHostSetUp (comment-only rendering).
    /// </summary>
    void AnalyzeSetupActionForBlocking(TestAction action)
    {
        var sourceText = GetActionSourceText(action);
        var declaredVariables = ExtractVariableNames(sourceText).ToArray();

        var sourceOnlyIdentifier = FindReferencedSymbol(sourceText, _sourceOnlyIdentifiers);
        if (sourceOnlyIdentifier != null)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
            foreach (var refName in declaredVariables)
                BlockSymbol(refName);
            return;
        }

        var blockedSymbol = FindReferencedSymbol(sourceText, _blockedSymbols);
        if (blockedSymbol != null)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
            return;
        }

        // If action is raw/unsupported, declared variables are blocked (not resolved)
        if (action is RawStatementAction or UnsupportedAction)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
        }

        // Check for unavailable symbols
        var unavailableRefs = FindUnavailableSymbolsForAction(action, sourceText, declaredVariables);
        if (unavailableRefs.Count > 0)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
            foreach (var refName in unavailableRefs)
                BlockSymbol(refName);
        }
    }

    void RenderActionAsComment(StringBuilder sb, TestAction action)
    {
        switch (action)
        {
            case MethodInvocationAction mi:
                AppendCommentBlock(sb, _indent + _indent, mi.FullSourceText, "  ");
                break;
            case MappedMethodInvocationAction mm:
                AppendCommentBlock(sb, _indent + _indent, mm.FullSourceText, "  ");
                break;
            case ClickAction click:
                AppendCommentBlock(sb, _indent + _indent, $"click: {click.Target.SourceExpression}", "  ");
                break;
            case SendKeysAction sk:
                AppendCommentBlock(sb, _indent + _indent, $"sendKeys: {sk.Target.SourceExpression} = {sk.TextExpression}", "  ");
                break;
            case RawStatementAction raw:
                AppendCommentBlock(sb, _indent + _indent, $"raw: {raw.SourceText}", "  ");
                break;
            case UnsupportedAction unsupported:
                AppendCommentBlock(sb, _indent + _indent, $"unsupported: {unsupported.SourceText}", "  ");
                break;
            case LocalDeclarationAction lds:
                AppendCommentBlock(sb, _indent + _indent, $"var: {lds.VariableType} {lds.VariableName} = {lds.InitializationValue}", "  ");
                break;
            default:
                sb.AppendLine($"{_indent}{_indent}//   [{action.GetType().Name}]");
                break;
        }
    }

    void RenderSetUp(StringBuilder sb, IEnumerable<TestAction> actions)
    {
        sb.AppendLine($"{_indent}[SetUp]");
        sb.AppendLine($"{_indent}public async Task SetUp()");
        sb.AppendLine($"{_indent}{{");

        foreach (var action in actions)
            RenderActionWithSafety(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    void RenderTest(StringBuilder sb, TestModel test)
    {
        if (!string.IsNullOrEmpty(test.Category))
            sb.AppendLine($"{_indent}[Category(\"{test.Category}\")]");

        foreach (var caseData in test.CaseData)
        {
            if (!string.IsNullOrEmpty(caseData.RawSourceText))
            {
                var raw = NormalizeAttribute(caseData.RawSourceText);
                sb.AppendLine($"{_indent}{raw}");
            }
            else
            {
                var args = string.Join(", ", caseData.Arguments.Select(a =>
                {
                    if (a.All(char.IsDigit) || (a.Contains('.') && a.Replace(".", "").Replace("-", "").All(char.IsDigit)))
                        return a;

                    return $"\"{a}\"";
                }));
                sb.AppendLine($"{_indent}[TestCase({args})]");
            }
        }

        if (!test.CaseData.Any())
            sb.AppendLine($"{_indent}[Test]");

        var paramList = RenderParameters(test.Parameters);
        sb.AppendLine($"{_indent}public async Task {test.Name}({paramList})");
        sb.AppendLine($"{_indent}{{");
        ResetMethodScope();

        // Carry over fixture-scoped blocked symbols from setup
        foreach (var symbol in _setupBlockedSymbols)
            _blockedSymbols.Add(symbol);

        foreach (var action in test.BodyActions)
            RenderActionWithSafety(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    string RenderParameters(IEnumerable<MethodParameterModel> parameters)
    {
        if (parameters == null || !parameters.Any())
            return string.Empty;

        return string.Join(", ", parameters.Select(p =>
        {
            var param = $"{p.Type} {p.Name}";
            if (p.DefaultValue != null)
                param += $" = {p.DefaultValue}";
            return param;
        }));
    }

    string NextTempVar(string hint)
    {
        return $"{hint}_{_tempVarCounter++}";
    }

    void RenderAction(StringBuilder sb, TestAction action)
    {
        switch (action)
        {
            case ClickAction click:
                RenderClick(sb, click);
                break;
            case SendKeysAction sendKeys:
                RenderSendKeys(sb, sendKeys);
                break;
            case PressAction press:
                RenderPress(sb, press);
                break;
            case AssertThatAction assertThat:
                RenderAssertThat(sb, assertThat);
                break;
            case AssertAreEqualAction assertEqual:
                RenderAssertAreEqual(sb, assertEqual);
                break;
            case TextAssertionAction textAssert:
                RenderTextAssertion(sb, textAssert);
                break;
            case VisibilityAssertionAction visAssert:
                RenderVisibilityAssertion(sb, visAssert);
                break;
            case WaitForAction wait:
                RenderWaitFor(sb, wait);
                break;
            case UrlAssertionAction urlAssert:
                RenderUrlAssertion(sb, urlAssert);
                break;
            case MethodInvocationAction methodInv:
                RenderMethodInvocation(sb, methodInv);
                break;
            case MappedMethodInvocationAction mappedInv:
                RenderMappedMethodInvocation(sb, mappedInv);
                break;
            case UnsupportedAction unsupported:
                RenderUnsupported(sb, unsupported);
                break;
            case RawStatementAction raw:
                RenderRawStatement(sb, raw);
                break;
            case LocalDeclarationAction localDecl:
                RenderLocalDeclaration(sb, localDecl);
                break;
            case LocatorDeclarationAction locatorDecl:
                RenderLocatorDeclaration(sb, locatorDecl);
                break;
            case NavigationAction nav:
                RenderNavigation(sb, nav);
                break;
            case ConditionalBlockAction condBlock:
                RenderConditionalBlock(sb, condBlock);
                break;
            case TableRowTextAccessAction tableTextAccess:
                RenderTableRowTextAccess(sb, tableTextAccess);
                break;
            case TableCountAssertionAction tableCountAssert:
                RenderTableCountAssertion(sb, tableCountAssert);
                break;
            case TableRowAccessAction tableRowAccess:
                RenderTableRowAccess(sb, tableRowAccess);
                break;
            default:
                sb.AppendLine($"{_indent}{_indent}// [unknown action: {action.GetType().Name}]");
                break;
        }
    }

    void RenderActionWithSafety(StringBuilder sb, TestAction action)
    {
        var sourceText = GetActionSourceText(action);
        var declaredVariables = ExtractVariableNames(sourceText).ToArray();

        // WaitPolicy must run before source-root safety. A mapped wait such as
        // page.Loader.ValidateLoading() still has a Selenium/POM root (page),
        // but the meaningful target is page.Loader and can be rendered safely.
        // Actionability waits are intentionally elided because Playwright actions/assertions auto-wait.
        if (action is WaitForAction wait && TryRenderWaitPolicyBeforeSafety(sb, wait, sourceText))
            return;

        // Method mappings are explicit adapter/profile decisions. Their source text often
        // starts with a Selenium-only root such as Browser/page/pagef, but the TargetStatements
        // are already target-side code. Do not block them by source-root safety; unresolved
        // placeholders are handled safely inside RenderMappedMethodInvocation.
        if (action is MappedMethodInvocationAction mappedMethod)
        {
            RenderMappedMethodInvocation(sb, mappedMethod);
            return;
        }

        // Source-level blocked check: extract root symbol from original source expression.
        // If the root symbol is blocked (from unresolved setup/source-only), the action
        // must be commented regardless of whether the target has a valid Playwright mapping.
        var sourceRootSymbol = ExtractRootSymbol(sourceText);
        if (sourceRootSymbol != null)
        {
            var rootSourceOnly = _sourceOnlyIdentifiers.Contains(sourceRootSymbol)
                ? sourceRootSymbol
                : null;

            if (rootSourceOnly != null)
            {
                foreach (var variable in declaredVariables)
                    BlockSymbol(variable);

                RenderBlockedActionAsComment(
                    sb,
                    action,
                    $"uses source-only identifier '{rootSourceOnly}'",
                    sourceText);
                return;
            }

            var rootBlocked = _blockedSymbols.Contains(sourceRootSymbol)
                ? sourceRootSymbol
                : null;

            if (rootBlocked != null)
            {
                foreach (var variable in declaredVariables)
                    BlockSymbol(variable);

                RenderBlockedActionAsComment(
                    sb,
                    action,
                    $"depends on unresolved symbol '{rootBlocked}'",
                    sourceText);
                return;
            }
        }

        // For semantic actions with resolved targets, use rendered Playwright locator for
        // remaining symbol checks (e.g. secondary identifiers in assertion expressions).
        var checkText = GetCheckableSourceText(action, sourceText);

        var sourceOnlyIdentifier = FindReferencedSymbol(checkText, _sourceOnlyIdentifiers);
        if (sourceOnlyIdentifier != null)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);

            RenderBlockedActionAsComment(
                sb,
                action,
                $"uses source-only identifier '{sourceOnlyIdentifier}'",
                sourceText);
            return;
        }

        var blockedSymbol = FindReferencedSymbol(checkText, _blockedSymbols);
        if (blockedSymbol != null)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);

            RenderBlockedActionAsComment(
                sb,
                action,
                $"depends on unresolved symbol '{blockedSymbol}'",
                sourceText);
            return;
        }

        // Target-safe declaration: render as active code, register variables, skip blocking.
        if (action is RawStatementAction rawSafe && IsTargetSafeDeclaration(rawSafe.SourceText))
        {
            var safeRoot = ExtractTargetSafeRootSymbol(rawSafe.SourceText);
            if (safeRoot != null && safeRoot != "Page")
            {
                // Alias chain (e.g. "table.Locator(...)"): only allowed if alias is known
                // — previously declared as a local alias or in method scope.
                // Blocked aliases and unknown aliases are both rejected.
                if (_blockedSymbols.Contains(safeRoot) || !_localAliases.Contains(safeRoot))
                {
                    foreach (var variable in declaredVariables)
                        BlockSymbol(variable);
                    RenderBlockedActionAsComment(
                        sb,
                        action,
                        $"depends on unresolved symbol '{safeRoot}'",
                        sourceText);
                    return;
                }
            }

            RenderTargetSafeDeclaration(sb, rawSafe);

            // Register declared variables as local aliases
            foreach (var variable in declaredVariables)
                _localAliases.Add(variable);

            // No unavailable symbols check needed — the statement is target-safe
            return;
        }

        // Resolved raw statement: if a raw statement only references known symbols
        // (local aliases, framework built-ins, known types, etc.), render as active code
        // instead of TODO. This covers usages like `await Expect(loader).ToBeHiddenAsync()`
        // where `loader` is a known local alias.
        if (action is RawStatementAction rawResolved
            && !HasLineBreak(rawResolved.SourceText)
            && AllSymbolsResolved(rawResolved.SourceText, declaredVariables))
        {
            RenderResolvedRawStatement(sb, rawResolved);
            return;
        }

        RenderAction(sb, action);

        if (action is RawStatementAction raw && IsResolvedRawLocatorAssignment(raw.SourceText))
            return;

        if (action is RawStatementAction or UnsupportedAction)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
        }

        // Detect references to unavailable symbols: identifiers in sourceText that are
        // not declared in current scope, not known types, and not framework built-ins.
        // Only applies to RawStatement, MethodInvocation, MappedMethodInvocation, LocalDeclaration,
        // Navigation — i.e. actions where sourceText carries real identifiers.
        // Semantic actions like ClickAction/SendKeys have synthetic sourceText and are handled
        // by their own target resolution logic.
        var unavailableRefs = FindUnavailableSymbolsForAction(action, sourceText, declaredVariables);
        if (unavailableRefs.Count > 0)
        {
            foreach (var variable in declaredVariables)
                BlockSymbol(variable);
            foreach (var refName in unavailableRefs)
                BlockSymbol(refName);

            var refList = string.Join(", ", unavailableRefs.Select(r => $"'{r}'"));
            AppendSmartTodo(
                sb,
                $"references unavailable symbol(s) {refList} — verify in target",
                "UNAVAILABLE_SYMBOLS",
                "The statement contains identifiers that are not known in the generated target method/project context.",
                "Add target-known identifiers/types only when they are real target symbols; otherwise map or comment the source expression.");
        }
    }

    /// <summary>
    /// Returns the text to use for symbol safety checks.
    /// For semantic actions with resolved targets, returns the rendered Playwright locator
    /// (which contains no source-only identifiers). For other actions, returns original sourceText.
    /// </summary>
    string GetCheckableSourceText(TestAction action, string sourceText)
    {
        return action switch
        {
            ClickAction c when c.Target.Kind != TargetKind.Unresolved => RenderTargetExpression(c.Target),
            SendKeysAction s when s.Target.Kind != TargetKind.Unresolved => $"{RenderTargetExpression(s.Target)} {s.TextExpression}",
            PressAction p when p.Target.Kind != TargetKind.Unresolved => RenderTargetExpression(p.Target),
            WaitForAction w when w.Target.Kind != TargetKind.Unresolved => RenderTargetExpression(w.Target),
            TextAssertionAction t when t.Target.Kind != TargetKind.Unresolved => $"{RenderTargetExpression(t.Target)} {t.ExpectedValue}",
            VisibilityAssertionAction v when v.Target.Kind != TargetKind.Unresolved => RenderTargetExpression(v.Target),
            TableCountAssertionAction t when t.Target.Kind != TargetKind.Unresolved => $"{RenderTargetExpression(t.Target)} {t.ExpectedCount}",
            TableRowAccessAction t when t.Target.Kind != TargetKind.Unresolved => $"{RenderTargetExpression(t.Target)} {t.IndexExpression}",
            TableRowTextAccessAction t when t.Target.Kind != TargetKind.Unresolved => $"{RenderTargetExpression(t.Target)} {t.IndexExpression}",
            _ => sourceText
        };
    }

    void RenderBlockedActionAsComment(StringBuilder sb, TestAction action, string reason, string sourceText)
    {
        AppendSmartTodo(
            sb,
            reason,
            ClassifyBlockedTodoCode(reason),
            ExplainBlockedTodo(reason),
            NextActionForBlockedTodo(reason),
            sourceText);
        AppendCommentBlock(sb, _indent + _indent, sourceText, "  ");
    }

    void RenderUnresolvedTargetComment(StringBuilder sb, TargetExpression target, string actionDescription, int sourceLine)
    {
        var escaped = EscapeComment(target.SourceExpression);
        AppendSmartTodo(
            sb,
            $"map source expression to Playwright locator: {escaped}",
            "MISSING_MAPPING",
            "Source UI target has no adapter mapping yet.",
            "Find PageObject/source truth and add UiTarget/Table/Pagination mapping to adapter-config.");
        sb.AppendLine($"{_indent}{_indent}// {actionDescription} // line {sourceLine}");
    }

    void AppendSmartTodo(StringBuilder sb, string message, string code, string? reason = null, string? nextAction = null, string? source = null)
    {
        sb.AppendLine($"{_indent}{_indent}// TODO: {message} [MIGRATOR:{code}]");

        if (!string.IsNullOrWhiteSpace(reason))
            sb.AppendLine($"{_indent}{_indent}//   Reason: {EscapeComment(reason)}");

        if (!string.IsNullOrWhiteSpace(nextAction))
            sb.AppendLine($"{_indent}{_indent}//   Next: {EscapeComment(nextAction)}");

        if (!string.IsNullOrWhiteSpace(source))
            sb.AppendLine($"{_indent}{_indent}//   Source: {EscapeComment(source)}");
    }

    static string ClassifyBlockedTodoCode(string reason)
    {
        if (reason.StartsWith("uses source-only identifier", StringComparison.Ordinal))
            return "SOURCE_ONLY_IDENTIFIER";
        if (reason.StartsWith("depends on unresolved symbol", StringComparison.Ordinal))
            return "UNRESOLVED_SYMBOL";
        return "BLOCKED_ACTION";
    }

    static string ExplainBlockedTodo(string reason)
    {
        if (reason.StartsWith("uses source-only identifier", StringComparison.Ordinal))
            return "The statement references a Selenium/source-side symbol that must not be emitted as active Playwright code.";
        if (reason.StartsWith("depends on unresolved symbol", StringComparison.Ordinal))
            return "A previously unresolved or blocked symbol is required by this statement, so rendering it active would hide a migration problem.";
        return "Safety checks blocked this statement from active rendering.";
    }

    static string NextActionForBlockedTodo(string reason)
    {
        if (reason.StartsWith("uses source-only identifier", StringComparison.Ordinal))
            return "Map the whole source expression through adapter-config or leave it as TODO; do not mark source-only roots as target-known.";
        if (reason.StartsWith("depends on unresolved symbol", StringComparison.Ordinal))
            return "Find the first TODO that blocks this symbol, then add a source-backed mapping or escalate if it is a generic migrator issue.";
        return "Inspect source truth and decide whether this is a missing mapping, source-only code, or unsupported semantics.";
    }

    void RenderClick(StringBuilder sb, ClickAction action)
    {
        var target = action.Target;
        if (target.Kind != TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.ClickAsync(); // line {action.SourceLine}");
        }
        else
        {
            RenderUnresolvedTargetComment(sb, target, "await (locator).ClickAsync()", action.SourceLine);
        }
    }

    void RenderSendKeys(StringBuilder sb, SendKeysAction action)
    {
        var target = action.Target;
        var text = ConvertExpression(action.TextExpression);
        // Ensure text is a valid C# string expression — bare values should be quoted
        text = EnsureStringExpression(text);
        var escaped = EscapeComment(target.SourceExpression);

        if (target.Kind != TargetKind.Unresolved)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                sb.AppendLine($"{_indent}{_indent}// TODO: source input call has no value argument: {escaped}");
                sb.AppendLine($"{_indent}{_indent}// await {RenderTargetExpression(target)}.FillAsync(/* TODO */); // line {action.SourceLine}");
            }
            else
            {
                sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.FillAsync({text}); // line {action.SourceLine}");
            }
        }
        else
        {
            if (string.IsNullOrWhiteSpace(text))
                RenderUnresolvedTargetComment(sb, target, "await (locator).FillAsync(/* TODO */)", action.SourceLine);
            else
                RenderUnresolvedTargetComment(sb, target, $"await (locator).FillAsync({text})", action.SourceLine);
        }
    }

    /// <summary>
    /// Ensures the expression is a valid C# string argument.
    /// Already-quoted strings pass through. Numeric literals are left as-is.
    /// Bare identifiers are wrapped in quotes since SendKeys text is always a literal.
    /// </summary>
    static string EnsureStringExpression(string expr)
    {
        var trimmed = expr.Trim();
        if (trimmed.StartsWith('"'))
            return trimmed;
        if (trimmed.All(char.IsDigit) || trimmed.All(c => c == '.' || char.IsDigit(c)))
            return trimmed;
        // Bare identifier — treat as string literal
        return $"\"{trimmed.Replace("\\", "\\\\").Replace("\"", "\\\"")}\"";
    }

    void RenderPress(StringBuilder sb, PressAction action)
    {
        var target = action.Target;
        var keyName = ExtractKeyName(action.KeyName);

        if (target.Kind != TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.PressAsync(\"{keyName}\"); // line {action.SourceLine}");
        }
        else
        {
            RenderUnresolvedTargetComment(sb, target, $"await (locator).PressAsync(\"{keyName}\")", action.SourceLine);
        }
    }

    void RenderTextAssertion(StringBuilder sb, TextAssertionAction action)
    {
        var target = action.Target;
        var locator = target.Kind != TargetKind.Unresolved
            ? RenderTargetExpression(target)
            : "(locator)";

        if (target.Kind == TargetKind.Unresolved)
        {
            string methodLine;
            switch (action.Kind)
            {
                case TextAssertionKind.TextEquals:
                    methodLine = $"await {ExpectCall()}({locator}).ToHaveTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}";
                    break;
                case TextAssertionKind.TextNotEquals:
                    methodLine = $"Assert.That(await {locator}.InnerTextAsync(), Is.Not.EqualTo({ConvertExpression(action.ExpectedValue!)})); // line {action.SourceLine}";
                    break;
                case TextAssertionKind.TextNotEmpty:
                    methodLine = $"Assert.That(await {locator}.InnerTextAsync(), Is.Not.Empty); // line {action.SourceLine}";
                    break;
                case TextAssertionKind.TextEmpty:
                    methodLine = $"Assert.That(await {locator}.InnerTextAsync(), Is.Empty); // line {action.SourceLine}";
                    break;
                case TextAssertionKind.TextContains:
                    methodLine = $"await {ExpectCall()}({locator}).ToContainTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}";
                    break;
                default:
                    methodLine = $"// TODO: unsupported text assertion kind {action.Kind}";
                    break;
            }
            sb.AppendLine($"{_indent}{_indent}// {methodLine}");
            AppendSmartTodo(
                sb,
                $"map source expression to Playwright locator: {EscapeComment(target.SourceExpression)}",
                "MISSING_MAPPING",
                "Source UI target has no adapter mapping yet.",
                "Find PageObject/source truth and add UiTarget/Table/Pagination mapping to adapter-config.");
            return;
        }

        switch (action.Kind)
        {
            case TextAssertionKind.TextEquals:
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToHaveTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}");
                break;
            case TextAssertionKind.TextNotEquals:
                {
                    var nv = NextTempVar("textResult");
                    sb.AppendLine($"{_indent}{_indent}var {nv} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                    sb.AppendLine($"{_indent}{_indent}Assert.That({nv}, Is.Not.EqualTo({ConvertExpression(action.ExpectedValue!)}));");
                    break;
                }
            case TextAssertionKind.TextNotEmpty:
                {
                    var nv2 = NextTempVar("textResult");
                    sb.AppendLine($"{_indent}{_indent}var {nv2} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                    sb.AppendLine($"{_indent}{_indent}Assert.That({nv2}, Is.Not.Empty);");
                    break;
                }
            case TextAssertionKind.TextEmpty:
                {
                    var nv3 = NextTempVar("textResult");
                    sb.AppendLine($"{_indent}{_indent}var {nv3} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                    sb.AppendLine($"{_indent}{_indent}Assert.That({nv3}, Is.Empty);");
                    break;
                }
            case TextAssertionKind.TextContains:
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToContainTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}");
                break;
        }
    }

    void RenderVisibilityAssertion(StringBuilder sb, VisibilityAssertionAction action)
    {
        var target = action.Target;

        if (target.Kind == TargetKind.Unresolved)
        {
            var method = action.Kind == VisibilityKind.Visible ? "ToBeVisibleAsync" : "ToBeHiddenAsync";
            sb.AppendLine($"{_indent}{_indent}// await {ExpectCall()}((locator)).{method}(); // line {action.SourceLine}");
            AppendSmartTodo(
                sb,
                $"map source expression to Playwright locator: {EscapeComment(target.SourceExpression)}",
                "MISSING_MAPPING",
                "Source UI target has no adapter mapping yet.",
                "Find PageObject/source truth and add UiTarget/Table/Pagination mapping to adapter-config.");
        }
        else
        {
            var locator = RenderTargetExpression(target);
            if (action.Kind == VisibilityKind.Visible)
            {
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToBeVisibleAsync(); // line {action.SourceLine}");
            }
            else
            {
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToBeHiddenAsync(); // line {action.SourceLine}");
            }
        }
    }

    bool TryRenderWaitPolicyBeforeSafety(StringBuilder sb, WaitForAction action, string sourceText)
    {
        RenderWaitFor(sb, action, sourceText);
        return true;
    }

    void RenderWaitFor(StringBuilder sb, WaitForAction action) =>
        RenderWaitFor(sb, action, action.FullSourceText);

    void RenderWaitFor(StringBuilder sb, WaitForAction action, string sourceText)
    {
        var target = action.Target;

        if (action.Kind == WaitForKind.ActionabilityElided)
        {
            sb.AppendLine($"{_indent}{_indent}// source wait elided: {EscapeComment(sourceText)} // line {action.SourceLine}");
            sb.AppendLine($"{_indent}{_indent}//   Reason: Playwright actions and web-first assertions auto-wait for actionability.");
            return;
        }

        if (target.Kind == TargetKind.Unresolved)
        {
            RenderWaitMappingRequired(sb, action, sourceText);
            return;
        }

        var locator = RenderTargetExpression(target);
        switch (action.Kind)
        {
            case WaitForKind.ProductStateHidden:
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToBeHiddenAsync(); // line {action.SourceLine}");
                break;
            case WaitForKind.ProductStateVisible:
                sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}({locator}).ToBeVisibleAsync(); // line {action.SourceLine}");
                break;
            case WaitForKind.ReviewRequired:
                AppendSmartTodo(
                    sb,
                    $"custom wait requires state assertion: {EscapeComment(action.SourceMethod)}",
                    "WAIT_REQUIRES_STATE_ASSERTION",
                    "The source wait is custom/ambiguous. Do not migrate it as a fixed timeout without identifying the product state it waits for.",
                    "Replace with loader/table/modal/toast/url/download assertion or add a project Method/ParameterizedMethod mapping.",
                    sourceText);
                sb.AppendLine($"{_indent}{_indent}// await {locator}.WaitForAsync(); // line {action.SourceLine}");
                break;
            default:
                sb.AppendLine($"{_indent}{_indent}await {locator}.WaitForAsync(); // line {action.SourceLine}");
                break;
        }
    }

    void RenderWaitMappingRequired(StringBuilder sb, WaitForAction action, string sourceText)
    {
        string suggested = action.Kind switch
        {
            WaitForKind.ProductStateHidden => $"await {ExpectCall()}((locator)).ToBeHiddenAsync()",
            WaitForKind.ProductStateVisible => $"await {ExpectCall()}((locator)).ToBeVisibleAsync()",
            WaitForKind.ReviewRequired => "await (locator/state assertion)",
            _ => "await (locator).WaitForAsync()"
        };

        AppendSmartTodo(
            sb,
            $"map product-state wait target: {EscapeComment(action.Target.SourceExpression)}",
            action.Kind == WaitForKind.ReviewRequired ? "WAIT_REQUIRES_STATE_ASSERTION" : "WAIT_MAPPING_REQUIRED",
            "This is a Selenium wait. Playwright auto-wait covers actionability, but product-state waits such as loader/table/modal synchronization still need a concrete target assertion.",
            "Map the waited control through UiTargets/Tables or add a Method/ParameterizedMethod mapping. Do not mark source-only roots as target-known.",
            sourceText);
        sb.AppendLine($"{_indent}{_indent}// {suggested}; // line {action.SourceLine}");
    }

    void RenderUrlAssertion(StringBuilder sb, UrlAssertionAction action)
    {
        var expected = ConvertExpression(action.ExpectedValue);
        var isLiteral = expected.StartsWith("\"") && expected.EndsWith("\"");

        switch (action.Kind)
        {
            case UrlAssertionKind.UrlEquals:
                if (isLiteral)
                {
                    sb.AppendLine($"{_indent}{_indent}await {ExpectCall()}(Page).ToHaveURLAsync({expected}); // line {action.SourceLine}");
                }
                else
                {
                    sb.AppendLine($"{_indent}{_indent}// await {ExpectCall()}(Page).ToHaveURLAsync({expected}); // line {action.SourceLine}");
                    AppendSmartTodo(
                        sb,
                        "URL assertion uses external variable — verify and uncomment",
                        "EXTERNAL_URL_VARIABLE",
                        "Expected URL depends on a variable that may need target-project setup/context.",
                        "Ensure the variable is available in target code or map it via adapter-config.");
                }
                break;
            case UrlAssertionKind.UrlContains:
                if (isLiteral)
                {
                    sb.AppendLine($"{_indent}{_indent}Assert.That(Page.Url, Does.Contain({expected})); // line {action.SourceLine}");
                }
                else
                {
                    sb.AppendLine($"{_indent}{_indent}// Assert.That(Page.Url, Does.Contain({expected})); // line {action.SourceLine}");
                    AppendSmartTodo(
                        sb,
                        "URL assertion uses external variable — verify and uncomment",
                        "EXTERNAL_URL_VARIABLE",
                        "Expected URL depends on a variable that may need target-project setup/context.",
                        "Ensure the variable is available in target code or map it via adapter-config.");
                }
                break;
        }
    }

    void RenderMappedMethodInvocation(StringBuilder sb, MappedMethodInvocationAction action)
    {
        // TargetStatements may contain newline-separated statements in a single array
        // element, e.g. "await click();\nvar {result} = await Navigation.GoToAsync<T>();".
        // Split before {result} substitution and deduplication so each C# statement is
        // processed independently for rendering, variable extraction, and symbol registration.
        var originalStatements = action.TargetStatements
            .SelectMany(SplitMappedTargetStatements)
            .ToArray();

        // Substitute {result} before local-variable deduplication.
        //
        // Why: assignment-pattern mappings commonly emit declarations such as
        //   var {result} = await Navigation.GoToPageAsync<T>(...);
        // If deduplication runs first, it sees the literal placeholder as a variable
        // name and can lose the relationship between the declaration and later
        // statements. Replacing {result} up front lets the normal local alias logic
        // work with the real generated variable name and still rename it safely when
        // needed. Other placeholders, such as {TARGET}, are intentionally resolved
        // later because they depend on rendered target expressions.
        var resultPreprocessed = originalStatements
            .Select(stmt => SubstituteResultPlaceholderBeforeDedup(stmt, action))
            .ToArray();
        var processed = DeduplicateInvocationVariables(resultPreprocessed);

        for (var i = 0; i < processed.Length; i++)
        {
            var originalStatement = originalStatements[i];
            var stmt = processed[i];
            var (substituted, hasUnresolved) = SubstituteTargetPlaceholder(stmt, action);

            if (_useAssertionsExpect && substituted.Contains("Expect("))
            {
                substituted = substituted.Replace("Expect(", "Assertions.Expect(");
            }

            if (hasUnresolved)
            {
                RenderMappedTargetStatementAsComment(sb, substituted, action.SourceMethod, action.SourceLine);
            }
            else
            {
                sb.AppendLine($"{_indent}{_indent}{substituted} // line {action.SourceLine}");
                RegisterTargetLocalsFromMappedActiveStatement(substituted, originalStatement, action);
            }
        }
        if (action.RequiresReview)
        {
            AppendSmartTodo(
                sb,
                $"mapped method requires manual review — {EscapeComment(action.FullSourceText)}",
                "MAPPED_REQUIRES_REVIEW",
                "Adapter config explicitly marked this mapping as requiring review.",
                "Verify target semantics; remove RequiresReview only when the mapping is proven safe.");
        }
    }


    void RegisterTargetLocalsFromMappedActiveStatement(string statement, string originalStatement, MappedMethodInvocationAction action)
    {
        var declaredVariables = ExtractDeclaredVariableNames(statement).ToArray();
        foreach (var variable in declaredVariables)
            RegisterTargetLocal(variable);

        if (string.IsNullOrWhiteSpace(action.ResultVariable) || declaredVariables.Length == 0)
            return;

        var originalUsesResultPlaceholder = originalStatement.Contains("{result}", StringComparison.Ordinal);
        var originalDeclaredVariables = ExtractDeclaredVariableNames(originalStatement);
        var originalDeclaresResultVariable = originalDeclaredVariables.Any(v => v == action.ResultVariable);
        var declaredResultVariable = declaredVariables.FirstOrDefault(v => v == action.ResultVariable);
        if (!originalUsesResultPlaceholder && !originalDeclaresResultVariable && declaredResultVariable == null)
            return;

        RegisterSourceVar(action.ResultVariable!, declaredResultVariable ?? declaredVariables[0]);
    }


    static IEnumerable<string> SplitMappedTargetStatements(string statement)
    {
        return statement
            .Replace("\r\n", "\n")
            .Replace('\r', '\n')
            .Split('\n', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries)
            .Where(s => s.Length > 0);
    }


    static string SubstituteResultPlaceholderBeforeDedup(string statement, MappedMethodInvocationAction action)
    {
        if (!statement.Contains("{result}", StringComparison.Ordinal))
            return statement;

        if (string.IsNullOrWhiteSpace(action.ResultVariable))
            return statement;

        return statement.Replace("{result}", action.ResultVariable!, StringComparison.Ordinal);
    }

    /// <summary>
    /// Substitutes {TARGET} in a target statement with the resolved target expression.
    /// Also detects unknown placeholders (e.g. {UNKNOWN}) that cannot be resolved.
    /// Returns (substitutedStatement, hasUnresolvedPlaceholders).
    /// </summary>
    (string substituted, bool hasUnresolved) SubstituteTargetPlaceholder(string statement, MappedMethodInvocationAction action)
    {
        var substituted = statement;
        var hasUnresolved = false;

        // Resolve {result} from assignment-pattern mappings, e.g.
        // var page = Browser.GoToPage<Page>(...);
        if (substituted.Contains("{result}"))
        {
            if (!string.IsNullOrWhiteSpace(action.ResultVariable))
            {
                substituted = substituted.Replace("{result}", action.ResultVariable);
            }
            else
            {
                hasUnresolved = true;
            }
        }

        // Resolve {TARGET} if target expression is available
        if (substituted.Contains("{TARGET}"))
        {
            if (action.TargetExpr != null && action.TargetExpr.Kind != TargetKind.Unresolved)
            {
                var targetExpr = RenderTargetExpression(action.TargetExpr);
                substituted = substituted.Replace("{TARGET}", targetExpr);
            }
            else
            {
                hasUnresolved = true;
            }
        }

        // Check for any remaining unknown placeholders
        if (!hasUnresolved)
        {
            var remaining = FindRemainingPlaceholders(substituted);
            if (remaining.Length > 0)
            {
                hasUnresolved = true;
            }
        }

        return (substituted, hasUnresolved);
    }

    /// <summary>
    /// Finds remaining {PLACEHOLDER} tokens in a statement after substitution.
    /// </summary>
    static string[] FindRemainingPlaceholders(string statement)
    {
        var result = new List<string>();
        var inQuote = false;
        var quoteChar = '\0';

        for (int i = 0; i < statement.Length; i++)
        {
            var c = statement[i];

            if (inQuote)
            {
                if (c == quoteChar && statement[i - 1] != '\\')
                    inQuote = false;
                continue;
            }

            if (c == '"' || c == '\'')
            {
                inQuote = true;
                quoteChar = c;
                continue;
            }

            if (c == '{' && i + 1 < statement.Length)
            {
                int start = i;
                int j = i + 1;
                while (j < statement.Length && char.IsLetterOrDigit(statement[j]))
                    j++;
                if (j < statement.Length && statement[j] == '}')
                {
                    var name = statement.Substring(start + 1, j - start - 1);
                    if (!string.IsNullOrEmpty(name))
                        result.Add("{" + name + "}");
                    i = j;
                }
            }
        }

        return result.ToArray();
    }

    /// <summary>
    /// Renders a target statement as a safe TODO comment when placeholder substitution failed.
    /// </summary>
    void RenderMappedTargetStatementAsComment(StringBuilder sb, string statement, string? sourceMethod, int sourceLine)
    {
        var methodInfo = !string.IsNullOrEmpty(sourceMethod) ? $" sourceMethod: {sourceMethod}" : string.Empty;
        AppendSmartTodo(
            sb,
            $"unresolved MethodMapping placeholder{methodInfo} (line {sourceLine})",
            "UNRESOLVED_PLACEHOLDER",
            "A TargetStatement placeholder could not be substituted from the matched source method.",
            "Fix SourceMethodPattern placeholders or TargetStatements in adapter-config.");
        AppendCommentBlock(sb, _indent + _indent, $"Original: {statement}", "  ");
    }

    string[] DeduplicateInvocationVariables(IReadOnlyList<string> statements)
    {
        var result = new string[statements.Count];
        var seenInInvocation = new Dictionary<string, string>();

        for (var i = 0; i < statements.Count; i++)
        {
            var stmt = statements[i].Trim();
            if (stmt.StartsWith("var "))
            {
                var eqIdx = stmt.IndexOf('=');
                if (eqIdx > 0)
                {
                    var varName = stmt.Substring(4, eqIdx - 4).Trim();
                    string finalName;

                    if (_methodScopeVars.Contains(varName) || seenInInvocation.ContainsValue(varName))
                    {
                        var newVar = NextTempVar(varName);
                        while (_methodScopeVars.Contains(newVar) || seenInInvocation.ContainsValue(newVar))
                            newVar = NextTempVar(varName);
                        finalName = newVar;
                    }
                    else
                    {
                        finalName = varName;
                    }

                    seenInInvocation[varName] = finalName;
                    result[i] = $"var {finalName}{stmt.Substring(eqIdx)}";
                    continue;
                }
            }

            var resolved = ProtectPlaceholders(stmt, out var placeholders);
            foreach (var (orig, renamed) in seenInInvocation)
                resolved = Regex.Replace(resolved, $@"\b{Regex.Escape(orig)}\b", renamed);
            result[i] = RestorePlaceholders(resolved, placeholders);
        }

        return result;
    }

    /// <summary>
    /// Temporarily replaces {PLACEHOLDER} tokens with unique markers to prevent
    /// DeduplicateInvocationVariables from treating placeholder names as variable references.
    /// </summary>
    static string ProtectPlaceholders(string stmt, out string[] placeholders)
    {
        var matches = Regex.Matches(stmt, @"\{(\w+)\}");
        placeholders = new string[matches.Count];
        var protectedStmt = stmt;
        for (int i = 0; i < matches.Count; i++)
        {
            var ph = matches[i].Value;
            placeholders[i] = ph;
            protectedStmt = protectedStmt.Replace(ph, $"__PH_{i}__");
        }
        return protectedStmt;
    }

    /// <summary>
    /// Restores placeholder tokens after deduplication.
    /// </summary>
    static string RestorePlaceholders(string stmt, string[] placeholders)
    {
        for (int i = 0; i < placeholders.Length; i++)
        {
            stmt = stmt.Replace($"__PH_{i}__", placeholders[i]);
        }
        return stmt;
    }

    void RenderAssertThat(StringBuilder sb, AssertThatAction action)
    {
        var actual = ConvertExpression(action.ActualExpression);
        var constraint = ConvertConstraint(action.ConstraintExpression);
        var sourceLine = action.SourceLine;

        var commentBody = $"Assert.That({actual}, {constraint}); // line {sourceLine}";
        AppendCommentBlock(sb, _indent + _indent, commentBody);

        AppendSmartTodo(
            sb,
            "convert constraint to Playwright assertion",
            "ASSERTION_CONSTRAINT",
            "The NUnit/Fluent assertion constraint was preserved as a comment because no equivalent Playwright assertion was inferred.",
            "Add a parameterized assertion mapping if this pattern is common.");
    }

    void RenderAssertAreEqual(StringBuilder sb, AssertAreEqualAction action)
    {
        var expected = ConvertExpression(action.ExpectedExpression);
        var actual = ConvertExpression(action.ActualExpression);
        sb.AppendLine(
            $"{_indent}{_indent}Assert.That({actual}, Is.EqualTo({expected})); // line {action.SourceLine}");
    }

    void RenderMethodInvocation(StringBuilder sb, MethodInvocationAction action)
    {
        AppendCommentBlock(sb, _indent + _indent, $"[{action.MethodName}] {action.FullSourceText} // line {action.SourceLine}");
        if (!IsLowPriorityMethod(action.MethodName, action.FullSourceText))
        {
            AppendSmartTodo(
                sb,
                "manual review needed",
                "MANUAL_REVIEW",
                "Method invocation was recognized only at a generic level and may have side effects.",
                "Add Method/ParameterizedMethod mapping when source truth confirms deterministic target behavior.");
        }
    }

    void RenderUnsupported(StringBuilder sb, UnsupportedAction action)
    {
        var reason = EscapeComment(action.Reason);
        AppendSmartTodo(
            sb,
            $"UNSUPPORTED [{reason}]",
            "UNSUPPORTED_ACTION",
            "The source action is not supported by the current recognizers/adapter mappings.",
            "Classify it as missing mapping, unsupported business semantics, or a generic migrator gap.");
        AppendCommentBlock(sb, _indent + _indent, action.SourceText, "  ");
    }

    void RenderRawStatement(StringBuilder sb, RawStatementAction action)
    {
        if (HasLineBreak(action.SourceText))
        {
            if (IsTrivialRawStatement(action.SourceText))
            {
                AppendCommentBlock(sb, _indent + _indent, $"source: {action.SourceText} // line {action.SourceLine}");
            }
            else
            {
                AppendSmartTodo(
                sb,
                "raw statement requires manual review:",
                "RAW_STATEMENT",
                "The source statement was not recognized semantically and may contain Selenium-specific or business-specific logic.",
                "Prefer adapter-config Method/ParameterizedMethod mapping if the pattern is reusable; otherwise keep TODO for manual migration.");
                AppendCommentBlock(sb, _indent + _indent, action.SourceText, "  ");
            }

            return;
        }

        if (IsTrivialRawStatement(action.SourceText))
        {
            sb.AppendLine($"{_indent}{_indent}// source: {EscapeComment(action.SourceText)} // line {action.SourceLine}");
        }
        else
        {
            AppendSmartTodo(
                sb,
                $"raw statement — review: {EscapeComment(action.SourceText)}",
                "RAW_STATEMENT",
                "The source statement was emitted as a safe comment because no reliable target mapping exists yet.",
                "Find source truth and add a mapping only if the translation is deterministic.");
        }
    }

    void RenderTargetSafeDeclaration(StringBuilder sb, RawStatementAction action)
    {
        var source = action.SourceText.Trim();
        var line = source.EndsWith(";", StringComparison.Ordinal)
            ? $"{source} // line {action.SourceLine}"
            : $"{source}; // line {action.SourceLine}";
        sb.AppendLine($"{_indent}{_indent}{line}");
        RegisterTargetLocalsFromActiveStatement(source);
    }

    /// <summary>
    /// Returns true for methods proven to have no runtime side effects.
    /// Currently conservative — no methods are suppressed globally.
    /// Use adapter config MethodMapping instead of adding entries here.
    /// </summary>
    static bool IsLowPriorityMethod(string methodName, string? fullSourceText)
    {
        // Reject patterns that always have side effects — never suppress.
        if (methodName.StartsWith("ClickAndOpen", StringComparison.Ordinal))
            return false;
        if (methodName.StartsWith("Open", StringComparison.Ordinal))
            return false;
        if (fullSourceText is not null && fullSourceText.Contains("Navigation.", StringComparison.Ordinal))
            return false;

        // No methods currently suppressed globally.
        // Methods like ValidateLoading, ExecuteScript, Window, SettingPeriod may have side effects
        // and should be handled via adapter config MethodMapping per-project.
        return false;
    }

    /// <summary>
    /// Returns true for raw statements that are provably trivial (no variable capture, no side effects).
    /// Does NOT suppress variable declarations — they may be used later.
    /// </summary>
    static bool IsTrivialRawStatement(string sourceText)
    {
        var text = sourceText.Trim().TrimEnd(';');

        // Variable declarations are NOT trivial — the variable may be used later.
        if (text.StartsWith("var ", StringComparison.Ordinal))
            return false;

        // Standalone property access on known read-only patterns — no assignment, no side effect.
        // These are visibility/text checks that returned a value not used elsewhere in this statement.
        if (text.EndsWith(".Visible.Get()", StringComparison.Ordinal))
            return true;
        if (text.EndsWith(".Text.Get()", StringComparison.Ordinal))
            return true;

        return false;
    }

    void RenderLocalDeclaration(StringBuilder sb, LocalDeclarationAction action)
    {
        if (ContainsUnresolvedSourceObjectAccess(action.InitializationValue) && HasLineBreak(action.InitializationValue))
        {
            AppendSmartTodo(
                sb,
                "raw local declaration requires manual review:",
                "RAW_LOCAL_DECLARATION",
                "The declaration initializer contains unresolved/source-side logic.",
                "Map the initializer or keep the declaration commented until target semantics are known.");
            AppendCommentBlock(sb, _indent + _indent, $"{action.VariableType} {action.VariableName} = {action.InitializationValue}", "  ");
            return;
        }

        if (ContainsUnresolvedSourceObjectAccess(action.InitializationValue))
        {
            AppendSmartTodo(
                sb,
                $"raw local declaration — review: {EscapeComment(action.VariableType)} {EscapeComment(action.VariableName)} = {EscapeComment(action.InitializationValue)}",
                "RAW_LOCAL_DECLARATION",
                "The declaration depends on source-side object access and cannot be safely emitted active.",
                "Map the source expression through adapter-config or leave it for manual migration.");
            return;
        }

        RegisterSourceVar(action.VariableName, action.VariableName);
        RegisterTargetLocal(action.VariableName);
        sb.AppendLine($"{_indent}{_indent}{action.VariableType} {action.VariableName} = {ConvertExpression(action.InitializationValue)}; // line {action.SourceLine}");
    }

    static bool ContainsUnresolvedSourceObjectAccess(string expr)
    {
        return Regex.IsMatch(expr, @"\bpage\.");
    }

    void RenderLocatorDeclaration(StringBuilder sb, LocatorDeclarationAction action)
    {
        RegisterSourceVar(action.VariableName, action.LocatorExpression);
        RegisterTargetLocal(action.VariableName);
        _localAliases.Add(action.VariableName);
        sb.AppendLine($"{_indent}{_indent}var {action.VariableName} = {action.LocatorExpression}; // line {action.SourceLine}");
    }

    void RenderNavigation(StringBuilder sb, NavigationAction action)
    {
        sb.AppendLine($"{_indent}{_indent}await Page.GotoAsync({action.UrlExpression}); // line {action.SourceLine}");
        if (!string.IsNullOrEmpty(action.PageVariableName))
        {
            RegisterSourceVar(action.PageVariableName, "Page");
        }
    }

    void RenderConditionalBlock(StringBuilder sb, ConditionalBlockAction action)
    {
        sb.AppendLine($"{_indent}{_indent}if ({action.ConditionExpression})");
        sb.AppendLine($"{_indent}{_indent}{{");
        foreach (var a in action.IfActions)
            RenderActionWithSafety(sb, a);

        foreach (var elseIf in action.ElseIfActions)
        {
            sb.AppendLine($"{_indent}{_indent}}} else if ({elseIf.Condition})");
            sb.AppendLine($"{_indent}{_indent}{{");
            foreach (var a in elseIf.Actions)
                RenderActionWithSafety(sb, a);
        }

        if (action.ElseActions.Any())
        {
            sb.AppendLine($"{_indent}{_indent}}} else");
            sb.AppendLine($"{_indent}{_indent}{{");
            foreach (var a in action.ElseActions)
                RenderActionWithSafety(sb, a);
        }

        sb.AppendLine($"{_indent}{_indent}}}");
    }

    string ExtractKeyName(string keyExpression)
    {
        var expr = keyExpression.Trim();
        if (expr.StartsWith("Keys.", System.StringComparison.Ordinal))
            return expr.Substring("Keys.".Length);
        if (expr.StartsWith('"') && expr.EndsWith('"'))
            return expr.Substring(1, expr.Length - 2);
        return expr;
    }

    string NormalizeAttribute(string rawAttribute)
    {
        var raw = rawAttribute.Trim();
        if (raw.StartsWith("[") && raw.EndsWith("]"))
            return raw;

        if (raw.StartsWith("["))
            return raw + "]";

        return $"[{raw}]";
    }

    string RenderTargetExpression(TargetExpression target)
    {
        if (target is MappedTarget mapped && mapped.TestIdAttribute != null && target.Kind == TargetKind.PlaywrightLocator)
        {
            var attr = EscapeAttribute(mapped.TestIdAttribute);
            var value = EscapeString(mapped.TargetExpression);
            var expr = $"Page.Locator(\"[{attr}='{value}']\")";
            return ApplyMatchStrategy(expr, mapped);
        }

        var rendered = target.RenderLocator();
        return target.Kind switch
        {
            TargetKind.PlaywrightLocator => RenderPlaywrightLocator(mapped: target as MappedTarget, rendered),
            TargetKind.CssSelector => RenderCssSelectorLocator(mapped: target as MappedTarget),
            TargetKind.TestIdBeginning => RenderTestIdBeginningLocator(mapped: target as MappedTarget),
            TargetKind.ClassNameBeginning => RenderClassNameBeginningLocator(mapped: target as MappedTarget),
            TargetKind.Text => RenderTextLocator(mapped: target as MappedTarget),
            TargetKind.PageObjectProperty => rendered,
            TargetKind.RawExpression => rendered,
            _ => $"Page.Locator(\"TODO: {target.SourceExpression}\")"
        };
    }

    string RenderCssSelectorLocator(MappedTarget? mapped)
    {
        var selector = EscapeStringLiteral(mapped?.TargetExpression ?? "TODO");
        return ApplyMatchStrategy($"Page.Locator(\"{selector}\")", mapped);
    }

    string RenderTestIdBeginningLocator(MappedTarget? mapped)
    {
        var attr = EscapeAttribute(mapped?.TestIdAttribute ?? "data-testid");
        var prefix = EscapeAttributeValue(mapped?.TargetExpression ?? "TODO");
        return ApplyMatchStrategy($"Page.Locator(\"[{attr}^='{prefix}']\")", mapped);
    }

    string RenderClassNameBeginningLocator(MappedTarget? mapped)
    {
        var prefix = EscapeAttributeValue(mapped?.TargetExpression ?? "TODO");
        return ApplyMatchStrategy($"Page.Locator(\"[class^='{prefix}']\")", mapped);
    }

    string RenderPlaywrightLocator(MappedTarget? mapped, string rendered)
    {
        if (rendered.StartsWith("Page."))
            return ApplyMatchStrategy(rendered, mapped);

        // Legacy: TargetExpression already contains Playwright call like GetByTestId("x")
        if (IsLegacyPlaywrightFragment(rendered))
        {
            var expr = $"Page.{rendered}";
            return ApplyMatchStrategy(expr, mapped);
        }

        // Semantic: TargetExpression is a raw test-id value like "submit"
        if (mapped != null)
        {
            var expr = $"Page.GetByTestId(\"{mapped.TargetExpression}\")";
            return ApplyMatchStrategy(expr, mapped);
        }

        return $"Page.{rendered}";
    }

    string RenderTextLocator(MappedTarget? mapped)
    {
        if (mapped == null)
            return "Page.GetByText(\"TODO\")";

        var expr = $"Page.GetByText(\"{EscapeString(mapped.TargetExpression)}\")";
        return ApplyMatchStrategy(expr, mapped);
    }

    string ApplyMatchStrategy(string locatorExpr, MappedTarget? mapped)
    {
        if (mapped == null || string.IsNullOrEmpty(mapped.Match))
            return locatorExpr;

        return mapped.Match switch
        {
            "First" => $"{locatorExpr}.First",
            "Nth" when mapped.NthIndex.HasValue => $"{locatorExpr}.Nth({mapped.NthIndex.Value})",
            "Nth" when IsSafeIndexExpression(mapped.NthIndexExpression) => $"{locatorExpr}.Nth({mapped.NthIndexExpression})",
            "Nth" => locatorExpr,
            _ => locatorExpr
        };
    }

    static bool IsLegacyPlaywrightFragment(string expr)
    {
        var trimmed = expr.Trim();
        return trimmed.StartsWith("GetByTestId(") ||
               trimmed.StartsWith("Locator(") ||
               trimmed.StartsWith("GetByText(") ||
               trimmed.StartsWith("GetByRole(") ||
               trimmed.StartsWith("GetByLabel(") ||
               trimmed.StartsWith("GetByPlaceholder(") ||
               trimmed.StartsWith("GetByAltText(");
    }

    string EscapeAttribute(string attr)
    {
        return attr.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    string EscapeAttributeValue(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("'", "\\'");
    }

    string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("'", "&#39;");
    }

    string ConvertExpression(string expr)
    {
        if (expr.StartsWith('"') && expr.EndsWith('"'))
            return expr;

        var trimmed = expr.Trim();
        if (_sourceVarMap.TryGetValue(trimmed, out var mapped))
            return mapped;

        return ConvertHoursExtensions(expr);
    }

    static string ConvertHoursExtensions(string expr)
    {
        return Regex.Replace(
            expr,
            @"(?<![\w.])(?<value>\d+|[A-Za-z_]\w*)\s*\.\s*Hours\s*\(\s*\)",
            "TimeSpan.FromHours(${value})");
    }

    string ConvertConstraint(string constraint)
    {
        return constraint;
    }

    void AppendCommentBlock(StringBuilder sb, string indent, string? text, string prefix = "")
    {
        if (string.IsNullOrEmpty(text))
        {
            AppendCommentLine(sb, indent, prefix);
            return;
        }

        var normalized = text.Replace("\r\n", "\n").Replace('\r', '\n');
        foreach (var line in normalized.Split('\n'))
            AppendCommentLine(sb, indent, prefix + EscapeComment(line));
    }

    void AppendCommentLine(StringBuilder sb, string indent, string? text)
    {
        sb.AppendLine($"{indent}// {EscapeComment(text)}".TrimEnd());
    }

    static bool HasLineBreak(string? text)
    {
        return text?.IndexOfAny(new[] { '\r', '\n' }) >= 0;
    }

    static string EscapeComment(string? text)
    {
        if (string.IsNullOrEmpty(text))
            return string.Empty;

        return text
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("\r", " ")
            .Replace("\t", " ");
    }

    static bool IsSafeIndexExpression(string? indexExpression)
    {
        if (string.IsNullOrWhiteSpace(indexExpression))
            return false;

        return !indexExpression.Any(c => c is '\r' or '\n' or ';' or '{' or '}');
    }

    static string EscapeStringLiteral(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;

        return value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r\n", " ")
            .Replace("\n", " ")
            .Replace("\r", " ");
    }

    string ExpectCall() => _useAssertionsExpect ? "Assertions.Expect" : "Expect";

    void RenderTableRowTextAccess(StringBuilder sb, TableRowTextAccessAction action)
    {
        var target = action.Target;
        var indexExpr = action.IndexExpression;
        var locator = RenderTableRowLocator(target, indexExpr);

        if (target.Kind == TargetKind.Unresolved)
        {
            var escapedComment = EscapeComment(action.SourceText);
            var escapedLocator = EscapeStringLiteral(action.SourceText);
            AppendSmartTodo(
            sb,
            $"table row text access — map source expression: {escapedComment}",
            "TABLE_MAPPING_REQUIRED",
            "The table/list source expression is not mapped to a Playwright row target.",
            "Add a Tables mapping with RowTarget based on POM/source truth.");
            sb.AppendLine($"{_indent}{_indent}// var {NextTempVar("rowText")} = await Page.Locator(\"TODO: {escapedLocator}\").TextContentAsync();");
        }
        else
        {
            var varName = NextTempVar("rowText");
            var originalVarName = ExtractVariableName(action.SourceText);
            if (!string.IsNullOrEmpty(originalVarName))
            {
                RegisterSourceVar(originalVarName, varName);
            }
            sb.AppendLine($"{_indent}{_indent}var {varName} = await {locator}.TextContentAsync(); // line {action.SourceLine}");
        }
    }

    void ResetMethodScope()
    {
        _tempVarCounter = 0;
        _methodScopeVars.Clear();
        _sourceVarMap.Clear();
        _blockedSymbols.Clear();
        _localAliases.Clear();
        _targetLocals.Clear();
    }

    void RegisterSourceVar(string originalName, string generatedName)
    {
        originalName = originalName.Trim();
        if (!string.IsNullOrEmpty(originalName))
        {
            _sourceVarMap[originalName] = generatedName;
            _blockedSymbols.Remove(originalName);
        }
    }

    void RegisterTargetLocalsFromActiveStatement(string statement)
    {
        foreach (var variable in ExtractDeclaredVariableNames(statement))
            RegisterTargetLocal(variable);
    }

    void RegisterTargetLocal(string variableName)
    {
        variableName = variableName.Trim().TrimStart('@');
        if (string.IsNullOrEmpty(variableName) || variableName == "_")
            return;

        _targetLocals.Add(variableName);
        _methodScopeVars.Add(variableName);
        _blockedSymbols.Remove(variableName);
    }

    void BlockSymbol(string symbol)
    {
        symbol = symbol.Trim();
        if (string.IsNullOrEmpty(symbol) || symbol == "_")
            return;

        _sourceVarMap.Remove(symbol);
        _blockedSymbols.Add(symbol);
    }

    string? ExtractVariableName(string sourceText)
    {
        return ExtractVariableNames(sourceText).FirstOrDefault();
    }

    static IReadOnlyList<string> ExtractVariableNames(string? sourceText)
    {
        if (string.IsNullOrWhiteSpace(sourceText))
            return Array.Empty<string>();

        var text = StripLeadingCommentPrefix(sourceText.Trim()).Trim().TrimEnd(';');
        var result = ExtractDeclaredVariableNames(text).ToList();
        if (result.Count > 0)
            return result;

        var assignment = Regex.Match(text, @"^\s*(@?\w+)\s*=");
        if (assignment.Success && !text.StartsWith("==", StringComparison.Ordinal))
        {
            AddName(result, assignment.Groups[1].Value);
            return result;
        }

        return result;
    }

    static IReadOnlyList<string> ExtractDeclaredVariableNames(string? sourceText)
    {
        if (string.IsNullOrWhiteSpace(sourceText))
            return Array.Empty<string>();

        var text = StripLeadingCommentPrefix(sourceText.Trim()).Trim().TrimEnd(';');
        var result = new List<string>();

        var deconstruction = Regex.Match(text, @"^\s*(?:var\s*)?\(([^)]+)\)\s*=");
        if (deconstruction.Success)
        {
            AddDeconstructionNames(result, deconstruction.Groups[1].Value);
            return result;
        }

        var simpleDeclaration = Regex.Match(
            text,
            @"^\s*(?:(?:const|readonly)\s+)?(?:var|[A-Za-z_]\w*(?:\s*\.\s*[A-Za-z_]\w*)*(?:\s*<[^=;]+>)?(?:\s*\[\s*\])?\??)\s+(@?[A-Za-z_]\w*)\s*=");
        if (simpleDeclaration.Success)
            AddName(result, simpleDeclaration.Groups[1].Value);

        return result;
    }

    static void AddDeconstructionNames(List<string> result, string namesText)
    {
        foreach (var part in namesText.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            var name = part.Trim();
            if (name.StartsWith("var ", StringComparison.Ordinal))
                name = name.Substring("var ".Length).Trim();

            AddName(result, name);
        }
    }

    static void AddName(List<string> result, string name)
    {
        name = name.Trim().TrimStart('@');
        if (string.IsNullOrEmpty(name) || name == "_")
            return;

        if (Regex.IsMatch(name, @"^[A-Za-z_]\w*$") && !result.Contains(name))
            result.Add(name);
    }

    static string StripLeadingCommentPrefix(string text)
    {
        var trimmed = text.TrimStart();
        return trimmed.StartsWith("//", StringComparison.Ordinal)
            ? trimmed.Substring(2).TrimStart()
            : text;
    }

    /// <summary>
    /// Extracts the root symbol from a source expression.
    /// "page.Button.Click()" → "page"
    /// "promoCodeSidePage.PromoCodeBlocks.First()" → "promoCodeSidePage"
    /// "Assert.That(x)" → "Assert"
    /// "var code = page.Table.Text.Get()" → "page" (from RHS of assignment)
    /// Returns null if no identifiable root symbol found.
    /// </summary>
    static string? ExtractRootSymbol(string sourceText)
    {
        if (string.IsNullOrWhiteSpace(sourceText))
            return null;

        var text = StripLeadingCommentPrefix(sourceText.Trim()).Trim().TrimEnd(';');

        // Handle assignments: extract root from RHS
        var assignMatch = Regex.Match(text, @"^\s*(?:var\s+|[\w<>\[\].?]+\s+)?(@?\w+)\s*=\s*(.+)$");
        if (assignMatch.Success)
        {
            var rhs = assignMatch.Groups[2].Value.Trim();
            return ExtractRootFromExpression(rhs);
        }

        // Handle deconstruction: "var (a, b) = Parse(x)" — root is from RHS
        var deconMatch = Regex.Match(text, @"^\s*(?:var\s*)?\([^)]+\)\s*=\s*(.+)$");
        if (deconMatch.Success)
        {
            var rhs = deconMatch.Groups[1].Value.Trim();
            return ExtractRootFromExpression(rhs);
        }

        return ExtractRootFromExpression(text);
    }

    static string? ExtractRootFromExpression(string text)
    {
        if (string.IsNullOrWhiteSpace(text))
            return null;

        // Skip leading keywords/var/typeof etc.
        var skipKeywords = new[] { "var ", "typeof(", "nameof(", "default(", "new " };
        foreach (var kw in skipKeywords)
        {
            if (text.StartsWith(kw, StringComparison.Ordinal))
            {
                text = text.Substring(kw.Length).Trim();
                break;
            }
        }

        // Match leading identifier, possibly followed by . or [
        var rootMatch = Regex.Match(text, @"^(@?[A-Za-z_]\w*)");
        if (!rootMatch.Success)
            return null;

        return rootMatch.Groups[1].Value.TrimStart('@');
    }

    string GetActionSourceText(TestAction action)
    {
        return action switch
        {
            ClickAction a => $"{a.Target.SourceExpression}.Click()",
            SendKeysAction a => $"{a.Target.SourceExpression}.SendKeys({a.TextExpression})",
            PressAction a => $"{a.Target.SourceExpression}.Press({a.KeyName})",
            AssertThatAction a => $"Assert.That({a.ActualExpression}, {a.ConstraintExpression})",
            AssertAreEqualAction a => $"Assert.AreEqual({a.ExpectedExpression}, {a.ActualExpression})",
            TextAssertionAction a => $"{a.Target.SourceExpression}.Text.Should({a.ExpectedValue})",
            VisibilityAssertionAction a => $"{a.Target.SourceExpression}.Visible.Should()",
            WaitForAction a => a.FullSourceText,
            UrlAssertionAction a => $"UrlAssertion({a.ExpectedValue})",
            MethodInvocationAction a => a.FullSourceText,
            MappedMethodInvocationAction a => a.FullSourceText,
            UnsupportedAction a => a.SourceText,
            RawStatementAction a => a.SourceText,
            LocalDeclarationAction a => $"{a.VariableType} {a.VariableName} = {a.InitializationValue}",
            LocatorDeclarationAction a => $"var {a.VariableName} = {a.SourceText}",
            NavigationAction a => a.SourceText ?? $"Navigation.OpenPage({a.UrlExpression})",
            ConditionalBlockAction a => a.ConditionExpression,
            TableRowTextAccessAction a => a.SourceText,
            TableRowAccessAction a => a.SourceText,
            TableCountAssertionAction a => a.SourceText,
            _ => string.Empty
        };
    }

    static string? FindReferencedSymbol(string sourceText, IEnumerable<string> symbols)
    {
        // Strip string literals to avoid false matches inside string content
        var stripped = StripStringLiterals(sourceText);
        foreach (var symbol in symbols.Where(s => !string.IsNullOrWhiteSpace(s)).OrderByDescending(s => s.Length))
        {
            if (Regex.IsMatch(stripped, $@"(?<![\w@]){Regex.Escape(symbol)}(?!\w)"))
                return symbol;
        }

        return null;
    }

    /// <summary>
    /// For supported action types, finds identifiers in sourceText that are unavailable in the target context.
    /// Only checks RawStatementAction, MethodInvocationAction, MappedMethodInvocationAction,
    /// LocalDeclarationAction, and NavigationAction — where sourceText carries real identifiers.
    /// Semantic actions (ClickAction, SendKeysAction, etc.) use synthetic sourceText and are excluded.
    /// </summary>
    HashSet<string> FindUnavailableSymbolsForAction(TestAction action, string sourceText, IReadOnlyList<string> declaredVariables)
    {
        // Only check actions that carry real source identifiers and generate active C# from them.
        // MappedMethodInvocationAction is excluded — its target statements are already processed
        // with placeholder substitution and safety checks. NavigationAction is excluded — URL
        // expressions are handled by their own logic. LocalDeclarationAction is excluded — it
        // has its own ContainsUnresolvedSourceObjectAccess check in RenderLocalDeclaration.
        if (action is RawStatementAction or MethodInvocationAction)
        {
            return FindUnavailableSymbols(sourceText, declaredVariables);
        }

        return new HashSet<string>();
    }

    /// <summary>
    /// Finds root identifiers in sourceText that are unavailable in the target context:
    /// not declared in current scope, not known types, not framework built-ins,
    /// and not source-only identifiers (already handled separately).
    /// Member names after '.' are ignored (e.g. Trim, Substring, ClickAsync).
    /// Returns unique set of unavailable symbol names.
    /// </summary>
    HashSet<string> FindUnavailableSymbols(string sourceText, IReadOnlyList<string> declaredVariables)
    {
        var unavailable = new HashSet<string>();

        // Build set of known symbols: declared vars, method scope vars, source var map keys, local aliases
        var knownSymbols = new HashSet<string>(StringComparer.Ordinal);
        foreach (var v in declaredVariables) knownSymbols.Add(v);
        foreach (var v in _methodScopeVars) knownSymbols.Add(v);
        foreach (var v in _sourceVarMap.Keys) knownSymbols.Add(v);
        foreach (var v in _localAliases) knownSymbols.Add(v);
        foreach (var v in _targetLocals) knownSymbols.Add(v);
        foreach (var v in _targetKnownIdentifiers) knownSymbols.Add(v);

        // Extract only root identifiers — member names after '.' are ignored
        var identifiers = ExtractRootIdentifiers(sourceText);
        foreach (var id in identifiers)
        {
            if (IsKnownType(id)) continue;
            if (IsFrameworkKeyword(id)) continue;
            if (IsFrameworkBuiltIn(id)) continue;
            if (knownSymbols.Contains(id)) continue;

            // Check if it's a property/method chain on a known receiver
            // e.g. "Page.Locator(...)" — "Page" is known (Playwright Page property, uppercase only)
            if (id == "Page") continue;

            unavailable.Add(id);
        }

        return unavailable;
    }

    static HashSet<string> ExtractIdentifiers(string text)
    {
        // Strip string literals (regular, verbatim, interpolated) before extracting identifiers.
        // This prevents false positives like "data", "test", "table" from CSS selectors
        // and "https", "arbilling3", "testkontur", "ru" from URLs.
        var stripped = StripStringLiterals(text);
        return new HashSet<string>(
            Regex.Matches(stripped, @"(?<![\w@])[A-Za-z_]\w*").Select(m => m.Value));
    }

    /// <summary>
    /// Removes C# string literals from source text to prevent identifier extraction from string content.
    /// Handles: regular strings ("..."), verbatim strings (@""...""), and interpolated strings ($"..." / @$"...").
    /// Interpolation expressions (${...}) are preserved for analysis.
    /// </summary>
    static string StripStringLiterals(string text)
    {
        var sb = new StringBuilder();
        var i = 0;
        while (i < text.Length)
        {
            // Verbatim string: @"..." or @$"..." or $"...
            if (i < text.Length && text[i] == '"')
            {
                var prefixStart = i;
                var isVerbatim = false;

                // Check for @ prefix
                if (i > 0 && text[i - 1] == '@')
                    isVerbatim = true;

                if (isVerbatim)
                {
                    // Verbatim string — find closing @"" (escaped as """)
                    i++; // skip opening "
                    while (i < text.Length)
                    {
                        if (text[i] == '"')
                        {
                            if (i + 1 < text.Length && text[i + 1] == '"')
                            {
                                // Escaped quote ""
                                sb.Append("  ");
                                i += 2;
                            }
                            else
                            {
                                // End of string
                                i++;
                                break;
                            }
                        }
                        else
                        {
                            sb.Append(' ');
                            i++;
                        }
                    }
                }
                else
                {
                    // Regular or interpolated string
                    i++; // skip opening "
                    while (i < text.Length)
                    {
                        if (text[i] == '\\' && i + 1 < text.Length)
                        {
                            // Escaped character — skip both
                            sb.Append("  ");
                            i += 2;
                        }
                        else if (text[i] == '{')
                        {
                            // Interpolation ${...} — preserve the expression inside
                            var depth = 1;
                            sb.Append('{');
                            i++;
                            while (i < text.Length && depth > 0)
                            {
                                if (text[i] == '{') depth++;
                                else if (text[i] == '}') depth--;
                                sb.Append(text[i]);
                                i++;
                            }
                        }
                        else if (text[i] == '"')
                        {
                            // End of string
                            i++;
                            break;
                        }
                        else
                        {
                            sb.Append(' ');
                            i++;
                        }
                    }
                }
            }
            // Character literal: '...'
            else if (i < text.Length && text[i] == '\'')
            {
                i++; // skip opening '
                while (i < text.Length)
                {
                    if (text[i] == '\\' && i + 1 < text.Length)
                    {
                        sb.Append("  ");
                        i += 2;
                    }
                    else if (text[i] == '\'')
                    {
                        i++;
                        break;
                    }
                    else
                    {
                        sb.Append(' ');
                        i++;
                    }
                }
            }
            else
            {
                sb.Append(text[i]);
                i++;
            }
        }

        return sb.ToString();
    }

    /// <summary>
    /// Returns true if all identifiers in the source text are resolved:
    /// known types, framework keywords, framework built-ins, local aliases,
    /// declared variables, method scope variables, or source var map entries.
    /// String literal content is stripped before analysis.
    /// Only checks root identifiers — member names after '.' are ignored
    /// (e.g. ToBeHiddenAsync, ClickAsync, GotoAsync are not checked).
    /// </summary>
    bool AllSymbolsResolved(string sourceText, IReadOnlyList<string> declaredVariables)
    {
        // ExtractRootIdentifiers already strips string literals internally
        var identifiers = ExtractRootIdentifiers(sourceText);

        foreach (var id in identifiers)
        {
            if (IsKnownType(id)) continue;
            if (IsFrameworkKeyword(id)) continue;
            if (IsFrameworkBuiltIn(id)) continue;
            if (id == "Page") continue; // Playwright Page property (uppercase only)
            if (declaredVariables.Contains(id)) continue;
            if (_localAliases.Contains(id)) continue;
            if (_targetLocals.Contains(id)) continue;
            if (_targetKnownIdentifiers.Contains(id)) continue;
            if (_methodScopeVars.Contains(id)) continue;
            if (_sourceVarMap.ContainsKey(id)) continue;

            // Found an unresolved symbol
            return false;
        }

        return true;
    }

    /// <summary>
    /// Extracts root identifiers from source text, ignoring member names after '.'.
    /// String literals are stripped before analysis to avoid false positives.
    /// "await Expect(loader).ToBeHiddenAsync()" → {Expect, loader}
    /// "await button.ClickAsync()" → {button}
    /// "SomeUnknownBuilder.Create()" → {SomeUnknownBuilder}
    /// "var x = Page.Locator(\"tr\").First" → {x, Page}
    /// </summary>
    static HashSet<string> ExtractRootIdentifiers(string text)
    {
        var stripped = StripStringLiterals(text);
        var roots = new HashSet<string>();
        var i = 0;
        while (i < stripped.Length)
        {
            // Find an identifier start
            if (char.IsLetter(stripped[i]) || stripped[i] == '_')
            {
                bool precededByDot = false;
                // Look backward to find if preceded by '.'
                int j = i - 1;
                while (j >= 0 && char.IsWhiteSpace(stripped[j])) j--;
                if (j >= 0 && stripped[j] == '.')
                    precededByDot = true;

                // Extract identifier
                int start = i;
                while (i < stripped.Length && (char.IsLetterOrDigit(stripped[i]) || stripped[i] == '_'))
                    i++;
                var id = stripped.Substring(start, i - start);

                if (!precededByDot)
                    roots.Add(id);
            }
            else
            {
                i++;
            }
        }
        return roots;
    }

    void RenderResolvedRawStatement(StringBuilder sb, RawStatementAction action)
    {
        var source = action.SourceText.Trim();
        var line = source.EndsWith(";", StringComparison.Ordinal)
            ? $"{source} // line {action.SourceLine}"
            : $"{source}; // line {action.SourceLine}";
        sb.AppendLine($"{_indent}{_indent}{line}");
        RegisterTargetLocalsFromActiveStatement(source);
    }

    static HashSet<string> KnownTypes = new(StringComparer.Ordinal)
    {
        // BCL types
        "string", "int", "long", "double", "float", "bool", "byte", "char", "short", "uint",
        "decimal", "object", "var", "void", "sbyte", "ushort", "ulong", "nint", "nuint",
        "DateTime", "DateTimeOffset", "TimeSpan", "Guid", "Uri",
        "Array", "List", "Dictionary", "HashSet", "KeyValuePair",
        "Action", "Func", "Predicate", "EventHandler",
        "Task", "ValueTask", "CancellationToken", "IQueryable", "IEnumerable",
        "Exception", "NullReferenceException", "InvalidOperationException",
        "ArgumentException", "ArgumentNullException", "ArgumentOutOfRangeException",
        "IndexOutOfRangeException", "FormatException", "IOException",
        "Type", "Assembly", "MemberInfo",
        "Console", "Math", "Convert", "Enum", "Delegate",
        "Environment", "AppDomain", "Process", "Thread",
        "StringBuilder", "StringComparer", "StringSplitOptions",
        "Regex", "Match", "MatchCollection", "Groups",
        "Enumerable", "Queryable",
        // Common test types
        "Assert", "Is", "Does", "Contains",
        "Expect", "Assertions",
        "Keys",
    };

    static HashSet<string> FrameworkKeywords = new(StringComparer.Ordinal)
    {
        "await", "async", "if", "else", "for", "foreach", "while", "do", "switch", "case",
        "break", "continue", "return", "throw", "try", "catch", "finally", "using",
        "new", "this", "base", "typeof", "nameof", "default", "checked", "unchecked",
        "is", "as", "in", "out", "ref", "params", "yield", "from", "where", "select",
        "let", "group", "orderby", "join", "into",
        "true", "false", "null",
        "public", "private", "protected", "internal", "static", "virtual", "override",
        "sealed", "abstract", "readonly", "const", "volatile", "unsafe",
        "class", "interface", "struct", "enum", "namespace", "delegate", "event",
        "get", "set", "add", "remove",
    };

    bool IsKnownType(string id) => KnownTypes.Contains(id) || _targetKnownTypes.Contains(id);
    static bool IsFrameworkKeyword(string id) => FrameworkKeywords.Contains(id);

    static HashSet<string> FrameworkBuiltIns = new(StringComparer.Ordinal)
    {
        // Playwright / NUnit / common runtime
        "Page", "Locator", "ILocator", "APIResponse", "Browser", "BrowserContext",
        "TestContext", "Assert",
        "AriaRole",
    };

    bool IsFrameworkBuiltIn(string id) => FrameworkBuiltIns.Contains(id) || _targetKnownIdentifiers.Contains(id);

    static bool IsResolvedRawLocatorAssignment(string sourceText)
    {
        var text = sourceText.Trim().TrimEnd(';');
        return Regex.IsMatch(
            text,
            @"^\s*@?\w+\s*=\s*WebDriver\s*\.\s*FindElement\s*\(\s*By\s*\.\s*(XPath|CssSelector)\s*\(\s*""[^""]*""\s*\)\s*\)\s*$");
    }

    /// <summary>
    /// Returns true if the statement is a variable declaration that assigns a Playwright locator.
    /// These are target-safe: the RHS uses Page.Locator, Page.GetByTestId, etc. or chains off
    /// a known resolved locator. Such declarations should be rendered as active code, their
    /// declared variables registered as local aliases, and NOT blocked.
    /// </summary>
    static bool IsTargetSafeDeclaration(string sourceText)
    {
        var text = sourceText.Trim().TrimEnd(';');

        // Match: var name = Page.Locator("...");
        //        var name = Page.GetByTestId("...");
        //        var name = Page.GetByText("...");
        //        var name = Page.GetByRole(AriaRole.Button);
        //        ILocator name = Page.Locator("...");
        //        Locator name = Page.Locator("...");
        if (Regex.IsMatch(text, @"^\s*(?:var|(?:I)?Locator)\s+\w+\s*=\s*Page\s*\.\s*(?:Locator|GetByTestId|GetByText|GetByRole)\s*\("))
            return true;

        // Match: var name = knownAlias.Locator("...") — where knownAlias will be checked separately
        if (Regex.IsMatch(text, @"^\s*var\s+\w+\s*=\s*(\w+)\s*\.\s*Locator\s*\("))
            return true;

        // Match: var name = knownAlias.GetByTestId("...")
        if (Regex.IsMatch(text, @"^\s*var\s+\w+\s*=\s*(\w+)\s*\.\s*GetByTestId\s*\("))
            return true;

        // Match: var name = knownAlias.GetByText("...")
        if (Regex.IsMatch(text, @"^\s*var\s+\w+\s*=\s*(\w+)\s*\.\s*GetByText\s*\("))
            return true;

        // Match: ILocator name = knownAlias.Locator("...")
        if (Regex.IsMatch(text, @"^\s*(?:I)?Locator\s+\w+\s*=\s*(\w+)\s*\.\s*Locator\s*\("))
            return true;

        return false;
    }

    /// <summary>
    /// For a target-safe declaration, extracts the root symbol from the RHS
    /// (e.g. "Page" from "Page.Locator(...)" or "table" from "table.Locator(...)").
    /// Returns null if the declaration does not use a known receiver.
    /// </summary>
    static string? ExtractTargetSafeRootSymbol(string sourceText)
    {
        var text = sourceText.Trim().TrimEnd(';');

        // Direct Page.* call
        if (Regex.IsMatch(text, @"^\s*(?:var|(?:I)?Locator)\s+\w+\s*=\s*Page\s*\.\s*(?:Locator|GetByTestId|GetByText|GetByRole)\s*\("))
            return "Page";

        // Alias.* call — extract the alias identifier
        var aliasMatch = Regex.Match(text, @"^\s*(?:var|(?:I)?Locator)\s+\w+\s*=\s*(\w+)\s*\.\s*(?:Locator|GetByTestId|GetByText)\s*\(");
        if (aliasMatch.Success)
            return aliasMatch.Groups[1].Value;

        return null;
    }

    void RenderTableCountAssertion(StringBuilder sb, TableCountAssertionAction action)
    {
        var target = action.Target;
        var locator = target.Kind != TargetKind.Unresolved
            ? RenderTargetExpression(target)
            : "(locator)";

        var expectCall = ExpectCall();
        var countExpr = action.ExpectedCount ?? "0";
        var prefix = target.Kind == TargetKind.Unresolved ? "// " : "";

        switch (action.Kind)
        {
            case TableCountKind.CountEquals:
                sb.AppendLine($"{_indent}{_indent}{prefix}await {expectCall}({locator}).ToHaveCountAsync({countExpr}); // line {action.SourceLine}");
                break;
            case TableCountKind.CountGreaterThanZero:
                var nv = NextTempVar("tableCount");
                sb.AppendLine($"{_indent}{_indent}{prefix}var {nv} = await {locator}.CountAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}{prefix}Assert.That({nv}, Is.GreaterThan(0));");
                break;
            case TableCountKind.CountLessThanOne:
                var nv2 = NextTempVar("tableCount");
                sb.AppendLine($"{_indent}{_indent}{prefix}var {nv2} = await {locator}.CountAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}{prefix}Assert.That({nv2}, Is.LessThan(1));");
                break;
            case TableCountKind.CountGreaterThanOrEqualTo:
                var nv3 = NextTempVar("tableCount");
                sb.AppendLine($"{_indent}{_indent}{prefix}var {nv3} = await {locator}.CountAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}{prefix}Assert.That({nv3}, Is.GreaterThanOrEqualTo({countExpr}));");
                break;
            default:
                AppendSmartTodo(
                    sb,
                    $"table count assertion — {action.Kind}",
                    "TABLE_ASSERTION_UNSUPPORTED",
                    "This table count assertion kind is not translated yet.",
                    "Add mapping/support for the assertion kind or keep it for manual migration.");
                sb.AppendLine($"{_indent}{_indent}//   {EscapeComment(action.SourceText)}");
                break;
        }

        if (target.Kind == TargetKind.Unresolved)
        {
            RenderUnresolvedTargetComment(sb, target, "table count assertion", action.SourceLine);

        }
    }

    void RenderTableRowAccess(StringBuilder sb, TableRowAccessAction action)
    {
        // This action represents a table row access that wasn't resolved to a specific operation
        // (click, text, etc). Render as TODO for manual review.
        var target = action.Target;
        var locator = RenderTableRowLocator(target, action.IndexExpression);

        if (target.Kind == TargetKind.Unresolved)
        {
            AppendSmartTodo(
                sb,
                $"table row access — map source expression: {EscapeComment(action.SourceText)}",
                "TABLE_MAPPING_REQUIRED",
                "The table/list access pattern is not mapped to a Playwright row target.",
                "Add a Tables mapping with RowTarget based on POM/source truth.");
            sb.AppendLine($"{_indent}{_indent}// var {NextTempVar("row")} = Page.Locator(\"TODO: {action.SourceText}\").Nth({action.IndexExpression});");
        }
        else
        {
            var varName = NextTempVar("row");
            sb.AppendLine($"{_indent}{_indent}var {varName} = {locator}; // line {action.SourceLine}");
        }
    }

    string RenderTableRowLocator(TargetExpression target, string indexExpr)
    {
        var rowIdx = 0;
        var hasIndex = int.TryParse(indexExpr, out rowIdx);

        if (target is MappedTarget mapped)
        {
            var locator = RenderTargetExpression(target);
            if (hasIndex)
            {
                if (string.IsNullOrEmpty(mapped.Match) || mapped.Match != "Nth")
                {
                    locator += $".Nth({rowIdx})";
                }
            }
            return locator;
        }

        if (hasIndex)
            return $"Page.Locator(\"TODO: {target.SourceExpression}\").Nth({rowIdx})";

        return $"Page.Locator(\"TODO: {target.SourceExpression}\")";
    }
}
