using System.Collections.Generic;
using System.Linq;
using System.Text;
using Migrator.Core;
using Migrator.Core.Models;

namespace Migrator.PlaywrightDotNet;

public class PlaywrightDotNetRenderer : IRenderer
{
    readonly string _indent;
    int _tempVarCounter = 0;

    public PlaywrightDotNetRenderer(string indent = "\t")
    {
        _indent = indent;
    }

    public string Render(TestFileModel model)
    {
        _tempVarCounter = 0;
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Migrator — Selenium C# → Playwright .NET");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine("using Microsoft.Playwright.NUnit;");
            sb.AppendLine("using NUnit.Framework;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine($"namespace {model.Namespace}.Playwright;");
            sb.AppendLine();
        }

        var className = model.ClassName + "Playwright";
        var hasTodoActions = model.Tests.SelectMany(t => t.BodyActions)
            .Concat(model.SetUpActions)
            .Any(a => a is UnsupportedAction or RawStatementAction or (MappedMethodInvocationAction { RequiresReview: true }));

        if (hasTodoActions)
        {
            sb.AppendLine("// WARNING: some actions need manual review. See TODO comments below.");
            sb.AppendLine();
        }

        sb.AppendLine($"public class {className} : PageTest");
        sb.AppendLine("{");
        sb.AppendLine();

        if (model.SetUpActions.Any())
        {
            RenderSetUp(sb, model.SetUpActions);
            sb.AppendLine();
        }

        foreach (var test in model.Tests)
        {
            RenderTest(sb, test);
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    void RenderSetUp(StringBuilder sb, IEnumerable<TestAction> actions)
    {
        sb.AppendLine($"{_indent}[SetUp]");
        sb.AppendLine($"{_indent}public async Task SetUp()");
        sb.AppendLine($"{_indent}{{");

        foreach (var action in actions)
            RenderAction(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    void RenderTest(StringBuilder sb, TestModel test)
    {
        if (!string.IsNullOrEmpty(test.Category))
            sb.AppendLine($"{_indent}[Category(\"{test.Category}\")]");

        foreach (var caseData in test.CaseData)
        {
            if (!string.IsNullOrEmpty(caseData.RawSourceText))
            {
                var raw = NormalizeAttribute(caseData.RawSourceText);
                sb.AppendLine($"{_indent}{raw}");
            }
            else
            {
                var args = string.Join(", ", caseData.Arguments.Select(a =>
                {
                    if (a.All(char.IsDigit) || (a.Contains('.') && a.Replace(".", "").Replace("-", "").All(char.IsDigit)))
                        return a;

                    return $"\"{a}\"";
                }));
                sb.AppendLine($"{_indent}[TestCase({args})]");
            }
        }

        if (!test.CaseData.Any())
            sb.AppendLine($"{_indent}[Test]");

        var paramList = RenderParameters(test.Parameters);
        sb.AppendLine($"{_indent}public async Task {test.Name}({paramList})");
        sb.AppendLine($"{_indent}{{");

        foreach (var action in test.BodyActions)
            RenderAction(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    string RenderParameters(IEnumerable<MethodParameterModel> parameters)
    {
        if (parameters == null || !parameters.Any())
            return string.Empty;

        return string.Join(", ", parameters.Select(p =>
        {
            var param = $"{p.Type} {p.Name}";
            if (p.DefaultValue != null)
                param += $" = {p.DefaultValue}";
            return param;
        }));
    }

    string NextTempVar(string hint)
    {
        return $"{hint}_{_tempVarCounter++}";
    }

    void RenderAction(StringBuilder sb, TestAction action)
    {
        switch (action)
        {
            case ClickAction click:
                RenderClick(sb, click);
                break;
            case SendKeysAction sendKeys:
                RenderSendKeys(sb, sendKeys);
                break;
            case PressAction press:
                RenderPress(sb, press);
                break;
            case AssertThatAction assertThat:
                RenderAssertThat(sb, assertThat);
                break;
            case AssertAreEqualAction assertEqual:
                RenderAssertAreEqual(sb, assertEqual);
                break;
            case TextAssertionAction textAssert:
                RenderTextAssertion(sb, textAssert);
                break;
            case VisibilityAssertionAction visAssert:
                RenderVisibilityAssertion(sb, visAssert);
                break;
            case WaitForAction wait:
                RenderWaitFor(sb, wait);
                break;
            case UrlAssertionAction urlAssert:
                RenderUrlAssertion(sb, urlAssert);
                break;
            case MethodInvocationAction methodInv:
                RenderMethodInvocation(sb, methodInv);
                break;
            case MappedMethodInvocationAction mappedInv:
                RenderMappedMethodInvocation(sb, mappedInv);
                break;
            case UnsupportedAction unsupported:
                RenderUnsupported(sb, unsupported);
                break;
            case RawStatementAction raw:
                RenderRawStatement(sb, raw);
                break;
            case LocalDeclarationAction localDecl:
                RenderLocalDeclaration(sb, localDecl);
                break;
            default:
                sb.AppendLine($"{_indent}{_indent}// [unknown action: {action.GetType().Name}]");
                break;
        }
    }

    void RenderClick(StringBuilder sb, ClickAction action)
    {
        var target = action.Target;
        if (target.Kind != TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.ClickAsync(); // line {action.SourceLine}");
        }
        else
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
            sb.AppendLine($"{_indent}{_indent}await Page.Locator(\"TODO: {target.SourceExpression}\").ClickAsync(); // line {action.SourceLine}");
        }
    }

    void RenderSendKeys(StringBuilder sb, SendKeysAction action)
    {
        var target = action.Target;
        var text = ConvertExpression(action.TextExpression);

        if (target.Kind != TargetKind.Unresolved)
        {
            if (string.IsNullOrWhiteSpace(text))
            {
                sb.AppendLine($"{_indent}{_indent}// TODO: source input call has no value argument: {target.SourceExpression}");
                sb.AppendLine($"{_indent}{_indent}// await {RenderTargetExpression(target)}.FillAsync(/* TODO */); // line {action.SourceLine}");
            }
            else
            {
                sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.FillAsync({text}); // line {action.SourceLine}");
            }
        }
        else
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
            if (string.IsNullOrWhiteSpace(text))
                sb.AppendLine($"{_indent}{_indent}// await Page.Locator(\"TODO: {target.SourceExpression}\").FillAsync(/* TODO */); // line {action.SourceLine}");
            else
                sb.AppendLine($"{_indent}{_indent}await Page.Locator(\"TODO: {target.SourceExpression}\").FillAsync({text}); // line {action.SourceLine}");
        }
    }

    void RenderPress(StringBuilder sb, PressAction action)
    {
        var target = action.Target;
        var keyName = ExtractKeyName(action.KeyName);

        if (target.Kind != TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.PressAsync(\"{keyName}\"); // line {action.SourceLine}");
        }
        else
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
            sb.AppendLine($"{_indent}{_indent}await Page.Locator(\"TODO: {target.SourceExpression}\").PressAsync(\"{keyName}\"); // line {action.SourceLine}");
        }
    }

    void RenderTextAssertion(StringBuilder sb, TextAssertionAction action)
    {
        var target = action.Target;
        var locator = target.Kind != TargetKind.Unresolved
            ? RenderTargetExpression(target)
            : $"Page.Locator(\"TODO: {target.SourceExpression}\")";

        switch (action.Kind)
        {
            case TextAssertionKind.TextEquals:
                sb.AppendLine($"{_indent}{_indent}await Expect({locator}).ToHaveTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}");
                break;
            case TextAssertionKind.TextNotEquals:
                var nv = NextTempVar("textResult");
                sb.AppendLine($"{_indent}{_indent}var {nv} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}Assert.That({nv}, Is.Not.EqualTo({ConvertExpression(action.ExpectedValue!)}));");
                break;
            case TextAssertionKind.TextNotEmpty:
                var nv2 = NextTempVar("textResult");
                sb.AppendLine($"{_indent}{_indent}var {nv2} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}Assert.That({nv2}, Is.Not.Empty);");
                break;
            case TextAssertionKind.TextEmpty:
                var nv3 = NextTempVar("textResult");
                sb.AppendLine($"{_indent}{_indent}var {nv3} = await {locator}.InnerTextAsync(); // line {action.SourceLine}");
                sb.AppendLine($"{_indent}{_indent}Assert.That({nv3}, Is.Empty);");
                break;
            case TextAssertionKind.TextContains:
                sb.AppendLine($"{_indent}{_indent}await Expect({locator}).ToContainTextAsync({ConvertExpression(action.ExpectedValue!)}); // line {action.SourceLine}");
                break;
        }

        if (target.Kind == TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
        }
    }

    void RenderVisibilityAssertion(StringBuilder sb, VisibilityAssertionAction action)
    {
        var target = action.Target;
        var locator = target.Kind != TargetKind.Unresolved
            ? RenderTargetExpression(target)
            : $"Page.Locator(\"TODO: {target.SourceExpression}\")";

        if (action.Kind == VisibilityKind.Visible)
        {
            sb.AppendLine($"{_indent}{_indent}await Expect({locator}).ToBeVisibleAsync(); // line {action.SourceLine}");
        }
        else
        {
            sb.AppendLine($"{_indent}{_indent}await Expect({locator}).ToBeHiddenAsync(); // line {action.SourceLine}");
        }

        if (target.Kind == TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
        }
    }

    void RenderWaitFor(StringBuilder sb, WaitForAction action)
    {
        var target = action.Target;
        if (target.Kind != TargetKind.Unresolved)
        {
            sb.AppendLine($"{_indent}{_indent}await {RenderTargetExpression(target)}.WaitForAsync(); // line {action.SourceLine}");
        }
        else
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: map source expression to Playwright locator: {target.SourceExpression}");
            sb.AppendLine($"{_indent}{_indent}await Page.Locator(\"TODO: {target.SourceExpression}\").WaitForAsync(); // line {action.SourceLine}");
        }
    }

    void RenderUrlAssertion(StringBuilder sb, UrlAssertionAction action)
    {
        var expected = ConvertExpression(action.ExpectedValue);
        var isLiteral = expected.StartsWith("\"") && expected.EndsWith("\"");

        switch (action.Kind)
        {
            case UrlAssertionKind.UrlEquals:
                if (isLiteral)
                {
                    sb.AppendLine($"{_indent}{_indent}await Expect(Page).ToHaveURLAsync({expected}); // line {action.SourceLine}");
                }
                else
                {
                    sb.AppendLine($"{_indent}{_indent}// await Expect(Page).ToHaveURLAsync({expected}); // line {action.SourceLine}");
                    sb.AppendLine($"{_indent}{_indent}// TODO: URL assertion uses external variable — verify and uncomment");
                }
                break;
            case UrlAssertionKind.UrlContains:
                if (isLiteral)
                {
                    sb.AppendLine($"{_indent}{_indent}Assert.That(Page.Url, Does.Contain({expected})); // line {action.SourceLine}");
                }
                else
                {
                    sb.AppendLine($"{_indent}{_indent}// Assert.That(Page.Url, Does.Contain({expected})); // line {action.SourceLine}");
                    sb.AppendLine($"{_indent}{_indent}// TODO: URL assertion uses external variable — verify and uncomment");
                }
                break;
        }
    }

    void RenderMappedMethodInvocation(StringBuilder sb, MappedMethodInvocationAction action)
    {
        foreach (var stmt in action.TargetStatements)
        {
            sb.AppendLine($"{_indent}{_indent}{stmt} // line {action.SourceLine}");
        }
        if (action.RequiresReview)
        {
            sb.AppendLine($"{_indent}{_indent}// TODO: mapped method requires manual review — {EscapeComment(action.FullSourceText)}");
        }
    }

    void RenderAssertThat(StringBuilder sb, AssertThatAction action)
    {
        var actual = ConvertExpression(action.ActualExpression);
        var constraint = ConvertConstraint(action.ConstraintExpression);
        sb.AppendLine($"{_indent}{_indent}// Assert.That({actual}, {constraint}); // line {action.SourceLine}");
        sb.AppendLine($"{_indent}{_indent}// TODO: convert constraint to Playwright assertion");
    }

    void RenderAssertAreEqual(StringBuilder sb, AssertAreEqualAction action)
    {
        var expected = ConvertExpression(action.ExpectedExpression);
        var actual = ConvertExpression(action.ActualExpression);
        sb.AppendLine(
            $"{_indent}{_indent}Assert.That({actual}, Is.EqualTo({expected})); // line {action.SourceLine}");
    }

    void RenderMethodInvocation(StringBuilder sb, MethodInvocationAction action)
    {
        var converted = ConvertExpression(action.FullSourceText);

        sb.AppendLine($"{_indent}{_indent}// [{action.MethodName}] {converted} // line {action.SourceLine}");
        sb.AppendLine($"{_indent}{_indent}// TODO: manual review needed");
    }

    void RenderUnsupported(StringBuilder sb, UnsupportedAction action)
    {
        sb.AppendLine($"{_indent}{_indent}// TODO: UNSUPPORTED [{action.Reason}]");
        sb.AppendLine($"{_indent}{_indent}//   {EscapeComment(action.SourceText)}");
    }

    void RenderRawStatement(StringBuilder sb, RawStatementAction action)
    {
        sb.AppendLine($"{_indent}{_indent}// TODO: raw statement — review: {EscapeComment(action.SourceText)}");
    }

    void RenderLocalDeclaration(StringBuilder sb, LocalDeclarationAction action)
    {
        sb.AppendLine($"{_indent}{_indent}{action.VariableType} {action.VariableName} = {action.InitializationValue}; // line {action.SourceLine}");
    }

    string ExtractKeyName(string keyExpression)
    {
        var expr = keyExpression.Trim();
        if (expr.StartsWith("Keys.", System.StringComparison.Ordinal))
            return expr.Substring("Keys.".Length);
        if (expr.StartsWith('"') && expr.EndsWith('"'))
            return expr.Substring(1, expr.Length - 2);
        return expr;
    }

    string NormalizeAttribute(string rawAttribute)
    {
        var raw = rawAttribute.Trim();
        if (raw.StartsWith("[") && raw.EndsWith("]"))
            return raw;

        if (raw.StartsWith("["))
            return raw + "]";

        return $"[{raw}]";
    }

    string RenderTargetExpression(TargetExpression target)
    {
        if (target is MappedTarget mapped && mapped.TestIdAttribute != null && target.Kind == TargetKind.PlaywrightLocator)
        {
            var attr = EscapeAttribute(mapped.TestIdAttribute);
            var value = EscapeString(mapped.TargetExpression);
            return $"Page.Locator(\"[{attr}='{value}']\")";
        }

        var rendered = target.RenderLocator();
        return target.Kind switch
        {
            TargetKind.PlaywrightLocator => RenderPlaywrightLocator(mapped: target as MappedTarget, rendered),
            TargetKind.PageObjectProperty => rendered,
            TargetKind.RawExpression => rendered,
            _ => $"Page.Locator(\"TODO: {target.SourceExpression}\")"
        };
    }

    string RenderPlaywrightLocator(MappedTarget? mapped, string rendered)
    {
        if (rendered.StartsWith("Page."))
            return rendered;

        // Legacy: TargetExpression already contains Playwright call like GetByTestId("x")
        if (IsLegacyPlaywrightFragment(rendered))
            return $"Page.{rendered}";

        // Semantic: TargetExpression is a raw test-id value like "submit"
        if (mapped != null)
            return $"Page.GetByTestId(\"{mapped.TargetExpression}\")";

        return $"Page.{rendered}";
    }

    static bool IsLegacyPlaywrightFragment(string expr)
    {
        var trimmed = expr.Trim();
        return trimmed.StartsWith("GetByTestId(") ||
               trimmed.StartsWith("Locator(") ||
               trimmed.StartsWith("GetByText(") ||
               trimmed.StartsWith("GetByRole(") ||
               trimmed.StartsWith("GetByLabel(") ||
               trimmed.StartsWith("GetByPlaceholder(") ||
               trimmed.StartsWith("GetByAltText(");
    }

    string EscapeAttribute(string attr)
    {
        return attr.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\"", "\\\"");
    }

    string ConvertExpression(string expr)
    {
        if (expr.StartsWith('"') && expr.EndsWith('"'))
            return expr;

        return expr;
    }

    string ConvertConstraint(string constraint)
    {
        return constraint;
    }

    string EscapeComment(string text)
    {
        return text.Replace("\n", " ").Replace("//", "/_/");
    }
}
