using System.Text;
using Migrator.Core;
using Migrator.Core.Models;

namespace Migrator.PlaywrightDotNet;

public class PlaywrightDotNetRenderer : IRenderer
{
    readonly string _indent;

    public PlaywrightDotNetRenderer(string indent = "\t")
    {
        _indent = indent;
    }

    public string Render(TestFileModel model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// Generated by Migrator — Selenium C# → Playwright .NET");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(model.Namespace))
        {
            sb.AppendLine($"using Microsoft.Playwright.NUnit;");
            sb.AppendLine("using NUnit.Framework;");
            sb.AppendLine("using System.Threading.Tasks;");
            sb.AppendLine();
            sb.AppendLine($"namespace {model.Namespace}.Playwright;");
            sb.AppendLine();
        }

        var className = model.ClassName + "Playwright";
        var allActions = model.Tests.SelectMany(t => t.BodyActions).ToList();
        var unsupportedCount = allActions.OfType<UnsupportedAction>().Count();

        if (unsupportedCount > 0)
        {
            sb.AppendLine($"// WARNING: {unsupportedCount} unsupported action(s) found. See TODO comments below.");
            sb.AppendLine();
        }

        sb.AppendLine($"public class {className} : PageTest");
        sb.AppendLine("{");
        sb.AppendLine();

        // Render [SetUp] method
        if (model.SetUpActions.Any())
        {
            RenderSetUp(sb, model.SetUpActions);
            sb.AppendLine();
        }

        // Render tests
        foreach (var test in model.Tests)
        {
            RenderTest(sb, test);
            sb.AppendLine();
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    void RenderSetUp(StringBuilder sb, IEnumerable<TestAction> actions)
    {
        sb.AppendLine($"{_indent}[SetUp]");
        sb.AppendLine($"{_indent}public async Task SetUp()");
        sb.AppendLine($"{_indent}{{");

        foreach (var action in actions)
            RenderAction(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    void RenderTest(StringBuilder sb, TestModel test)
    {
        if (!string.IsNullOrEmpty(test.Category))
            sb.AppendLine($"{_indent}[Category(\"{test.Category}\")]");

        foreach (var caseData in test.CaseData)
        {
            if (!string.IsNullOrEmpty(caseData.RawSourceText))
            {
                var raw = caseData.RawSourceText.TrimStart('[');
                sb.AppendLine($"{_indent}{raw}");
            }
            else
            {
                var args = string.Join(", ", caseData.Arguments.Select(a =>
                {
                    if (a.All(char.IsDigit) || (a.Contains('.') && a.Replace(".", "").Replace("-", "").All(char.IsDigit)))
                        return a;

                    return $"\"{a}\"";
                }));
                sb.AppendLine($"{_indent}[TestCase({args})]");
            }
        }

        if (!test.CaseData.Any())
            sb.AppendLine($"{_indent}[Test]");

        var paramList = RenderParameters(test.Parameters);
        sb.AppendLine($"{_indent}public async Task {test.Name}({paramList})");
        sb.AppendLine($"{_indent}{{");

        foreach (var action in test.BodyActions)
            RenderAction(sb, action);

        sb.AppendLine($"{_indent}}}");
    }

    string RenderParameters(IEnumerable<MethodParameterModel> parameters)
    {
        if (parameters == null || !parameters.Any())
            return string.Empty;

        return string.Join(", ", parameters.Select(p =>
        {
            var param = $"{p.Type} {p.Name}";
            if (p.DefaultValue != null)
                param += $" = {p.DefaultValue}";
            return param;
        }));
    }

    void RenderAction(StringBuilder sb, TestAction action)
    {
        switch (action)
        {
            case ClickAction click:
                RenderClick(sb, click);
                break;
            case SendKeysAction sendKeys:
                RenderSendKeys(sb, sendKeys);
                break;
            case AssertThatAction assertThat:
                RenderAssertThat(sb, assertThat);
                break;
            case AssertAreEqualAction assertEqual:
                RenderAssertAreEqual(sb, assertEqual);
                break;
            case MethodInvocationAction methodInv:
                RenderMethodInvocation(sb, methodInv);
                break;
            case UnsupportedAction unsupported:
                RenderUnsupported(sb, unsupported);
                break;
            default:
                sb.AppendLine($"{_indent}{_indent}// [unknown action: {action.GetType().Name}]");
                break;
        }
    }

    void RenderClick(StringBuilder sb, ClickAction action)
    {
        var locator = ConvertToLocator(action.TargetExpression, action.Confidence);
        sb.AppendLine($"{_indent}{_indent}await Page.{locator}.ClickAsync(); // line {action.SourceLine}");
    }

    void RenderSendKeys(StringBuilder sb, SendKeysAction action)
    {
        var locator = ConvertToLocator(action.TargetExpression, action.Confidence);
        var text = ConvertExpression(action.TextExpression);
        sb.AppendLine($"{_indent}{_indent}await Page.{locator}.FillAsync({text}); // line {action.SourceLine}");
    }

    void RenderAssertThat(StringBuilder sb, AssertThatAction action)
    {
        var actual = ConvertExpression(action.ActualExpression);
        var constraint = ConvertConstraint(action.ConstraintExpression);
        sb.AppendLine($"{_indent}{_indent}// Assert.That({actual}, {constraint}); // line {action.SourceLine}");
        sb.AppendLine($"{_indent}{_indent}// TODO: convert constraint to Playwright assertion");
    }

    void RenderAssertAreEqual(StringBuilder sb, AssertAreEqualAction action)
    {
        var expected = ConvertExpression(action.ExpectedExpression);
        var actual = ConvertExpression(action.ActualExpression);
        sb.AppendLine(
            $"{_indent}{_indent}Assert.That({actual}, Is.EqualTo({expected})); // line {action.SourceLine}");
    }

    void RenderMethodInvocation(StringBuilder sb, MethodInvocationAction action)
    {
        var converted = ConvertExpression(action.FullSourceText);
        sb.AppendLine($"{_indent}{_indent}// [{action.MethodName}] {converted} // line {action.SourceLine}");
        sb.AppendLine($"{_indent}{_indent}// TODO: manual review needed");
    }

    void RenderUnsupported(StringBuilder sb, UnsupportedAction action)
    {
        sb.AppendLine($"{_indent}{_indent}// TODO: UNSUPPORTED [{action.Reason}]");
        sb.AppendLine($"{_indent}{_indent}//   {EscapeComment(action.SourceText)}");
    }

    string ConvertToLocator(string expression, RecognitionConfidence confidence)
    {
        if (confidence == RecognitionConfidence.SyntaxFallback)
        {
            return $"Locator(\"TODO: {expression}\")";
        }

        if (expression.Contains("MenuItems."))
        {
            var member = expression.Substring(expression.LastIndexOf('.') + 1);
            return $"GetByText(\"{member}\")";
        }

        return $"Locator(\"{expression}\")";
    }

    string ConvertExpression(string expr)
    {
        if (expr.StartsWith('"') && expr.EndsWith('"'))
            return expr;

        return expr;
    }

    string ConvertConstraint(string constraint)
    {
        return constraint;
    }

    string EscapeComment(string text)
    {
        return text.Replace("\n", " ").Replace("//", "/_/");
    }
}
