param(
    [string]$Workspace = "migration",
    [string]$RunId = "",
    [Parameter(Mandatory = $true)][string[]]$SkillName,
    [string]$Trigger = "manual",
    [string]$Phase = "skills",
    [string]$Decision = "applied",
    [string]$Detail = "",
    [string]$EvidencePath = ""
)

$ErrorActionPreference = "Stop"

function Get-WorkspacePath([string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) { return [System.IO.Path]::GetFullPath($Path) }
    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}

function Read-LatestRunId([string]$WorkspacePath) {
    $agentState = Join-Path $WorkspacePath "agent-state.md"
    if (-not (Test-Path $agentState)) { return "" }
    $text = Get-Content -Raw -Path $agentState
    $m = [regex]::Match($text, '(?im)^\s*Latest run\s*:\s*(run-[0-9A-Za-z][0-9A-Za-z._-]*)\s*$')
    if ($m.Success) { return $m.Groups[1].Value }
    return ""
}

function ConvertTo-Hashtable($Object) {
    if ($null -eq $Object) { return $null }
    if ($Object -is [System.Collections.IDictionary]) { return $Object }

    $table = [ordered]@{}
    foreach ($property in $Object.PSObject.Properties) {
        $table[$property.Name] = $property.Value
    }
    return $table
}

function Append-JsonLine([string]$Path, $Payload) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    $line = $Payload | ConvertTo-Json -Compress -Depth 20
    Add-Content -Path $Path -Encoding UTF8 -Value $line
}

function Update-AppliedSkillsMarkdown([string]$Path, [string]$RunId, $Entries) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Applied Agent Skills")
    $lines.Add("")
    $lines.Add("Run id: $RunId")
    $lines.Add("")
    $lines.Add('This file is generated by `scripts/write-agent-skill-usage.ps1` / `.sh`.')
    $lines.Add("It proves which reusable behavior contracts influenced the run.")
    $lines.Add("")

    foreach ($entry in $Entries) {
        $evidence = if ([string]::IsNullOrWhiteSpace([string]$entry.evidencePath)) { "none" } else { [string]$entry.evidencePath }
        $detail = if ([string]::IsNullOrWhiteSpace([string]$entry.detail)) { "-" } else { [string]$entry.detail }
        $lines.Add(('- {0} — `{1}` — {2} — trigger: {3} — evidence: {4} — {5}' -f $entry.utc, $entry.skillName, $entry.decision, $entry.trigger, $evidence, $detail))
    }

    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    Set-Content -Path $Path -Encoding UTF8 -Value ($lines -join "`n")
}

$workspacePath = Get-WorkspacePath $Workspace
if (-not (Test-Path $workspacePath)) {
    throw "Workspace not found: $workspacePath"
}

if ([string]::IsNullOrWhiteSpace($RunId)) {
    $RunId = Read-LatestRunId $workspacePath
}
if ([string]::IsNullOrWhiteSpace($RunId)) {
    throw "RunId was not provided and could not be read from agent-state.md. Create/resume a harness run first."
}
if ($RunId -notmatch '^run-[0-9A-Za-z][0-9A-Za-z._-]*$') {
    throw "Invalid RunId '$RunId'. Expected run-001 style identifier."
}

$skillRoot = Join-Path $workspacePath "agent-skills"
if (-not (Test-Path $skillRoot)) {
    throw "Agent skills directory not found: $skillRoot. Run kit update/bootstrap first."
}

$runSkillDir = Join-Path $workspacePath "runs/$RunId/skills"
New-Item -ItemType Directory -Force -Path $runSkillDir | Out-Null

$utc = [DateTimeOffset]::UtcNow.ToString("o")
$recorded = New-Object System.Collections.Generic.List[object]

foreach ($name in $SkillName) {
    $normalized = $name.Trim().ToLowerInvariant()
    if ($normalized -notmatch '^[a-z0-9][a-z0-9._-]*$') {
        throw "Invalid skill name '$name'. Use directory names such as plow-ahead or agent-watchdog."
    }

    $skillPath = Join-Path $skillRoot "$normalized/SKILL.md"
    if (-not (Test-Path $skillPath)) {
        throw "Unknown agent skill '$normalized': missing $skillPath"
    }

    $firstLine = (Get-Content -Path $skillPath -TotalCount 1 -ErrorAction Stop)
    if ($firstLine -notmatch '^#\s+Skill:') {
        throw "Invalid skill file for '$normalized': expected '# Skill:' heading in $skillPath"
    }

    $entry = [ordered]@{
        schemaVersion = "agent-skill-usage/v1"
        utc = $utc
        runId = $RunId
        skillName = $normalized
        skillPath = "agent-skills/$normalized/SKILL.md"
        trigger = $Trigger
        phase = $Phase
        decision = $Decision
        detail = $Detail
        evidencePath = $EvidencePath
    }

    Append-JsonLine (Join-Path $workspacePath "state/agent-skill-usage.jsonl") $entry
    Append-JsonLine (Join-Path $runSkillDir "agent-skill-usage.jsonl") $entry
    $recorded.Add([pscustomobject]$entry)
}

$runUsagePath = Join-Path $runSkillDir "agent-skill-usage.jsonl"
$runEntries = New-Object System.Collections.Generic.List[object]
if (Test-Path $runUsagePath) {
    foreach ($line in Get-Content -Path $runUsagePath) {
        if ([string]::IsNullOrWhiteSpace($line)) { continue }
        try {
            $runEntries.Add(($line | ConvertFrom-Json -ErrorAction Stop))
        }
        catch {
            # Keep markdown generation best-effort; final gate owns JSONL validation.
        }
    }
}
Update-AppliedSkillsMarkdown (Join-Path $runSkillDir "applied-skills.md") $RunId $runEntries

$harnessRunPath = Join-Path $workspacePath "state/harness-run.json"
if (Test-Path $harnessRunPath) {
    try {
        $state = ConvertTo-Hashtable (Get-Content -Raw -Path $harnessRunPath | ConvertFrom-Json -ErrorAction Stop)
        if ($state -ne $null) {
            $existing = @()
            if ($state.Contains("appliedSkills") -and $null -ne $state["appliedSkills"]) {
                $existing = @($state["appliedSkills"])
            }
            $state["appliedSkills"] = @($existing) + @($recorded)
            $state["updatedAtUtc"] = $utc
            ($state | ConvertTo-Json -Depth 20) | Set-Content -Path $harnessRunPath -Encoding UTF8
        }
    }
    catch {
        Write-Warning "Could not update harness-run.json with applied skills: $($_.Exception.Message)"
    }
}

$event = [ordered]@{
    utc = $utc
    runId = $RunId
    phase = "skills"
    action = "agent-skill-usage"
    status = "recorded"
    detail = (($recorded | ForEach-Object { $_.skillName }) -join ",")
    data = [ordered]@{
        trigger = $Trigger
        decision = $Decision
        evidencePath = $EvidencePath
        skills = @($recorded)
    }
}
Append-JsonLine (Join-Path $workspacePath "state/harness-events.jsonl") $event
$tracePath = Join-Path $workspacePath "runs/$RunId/trace.jsonl"
if (Test-Path (Split-Path -Parent $tracePath)) {
    Append-JsonLine $tracePath $event
}

$recordedSkillNames = (@($recorded | ForEach-Object { $_.skillName }) -join ',')
$usagePath = Join-Path $runSkillDir 'applied-skills.md'
Write-Host "AGENT_SKILL_USAGE_RECORDED: $RunId $recordedSkillNames"
Write-Host "Usage: $usagePath"
