param(
    [string]$Workspace = "migration",
    [string]$RunId = "",
    [Parameter(Mandatory = $true)][string[]]$SkillName,
    [string]$Trigger = "manual",
    [string]$Phase = "skills",
    [string]$Decision = "applied",
    [string]$Detail = "",
    [string]$EvidencePath = ""
)
$ErrorActionPreference = "Stop"
function Get-WorkspacePath([string]$Path) {
    if ([System.IO.Path]::IsPathRooted($Path)) { return [System.IO.Path]::GetFullPath($Path) }
    return [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $Path))
}
function Append-JsonLine([string]$Path, $Payload) {
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    Add-Content -Path $Path -Encoding UTF8 -Value ($Payload | ConvertTo-Json -Compress -Depth 20)
}
function Find-LatestRunId([string]$WorkspacePath) {
    $latest = Get-ChildItem (Join-Path $WorkspacePath "runs") -Directory -Filter "run-*" -ErrorAction SilentlyContinue | Sort-Object LastWriteTimeUtc -Descending | Select-Object -First 1
    if ($null -ne $latest) { return $latest.Name }
    return ""
}
function Update-AppliedSkillsMarkdown([string]$Path, [string]$CurrentRunId, $Entries) {
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Applied Agent Skills")
    $lines.Add("")
    $lines.Add("Run id: $CurrentRunId")
    $lines.Add("")
    $lines.Add('Generated by `scripts/write-agent-skill-usage.ps1` / `.sh`.')
    $lines.Add("")
    foreach ($entry in $Entries) {
        $evidence = if ([string]::IsNullOrWhiteSpace([string]$entry.evidencePath)) { "none" } else { [string]$entry.evidencePath }
        $detail = if ([string]::IsNullOrWhiteSpace([string]$entry.detail)) { "-" } else { [string]$entry.detail }
        $lines.Add(('- {0} — `{1}` — {2} — trigger: {3} — evidence: {4} — {5}' -f $entry.utc, $entry.skillName, $entry.decision, $entry.trigger, $evidence, $detail))
    }
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $Path) | Out-Null
    Set-Content -Path $Path -Encoding UTF8 -Value ($lines -join "`n")
}
$workspacePath = Get-WorkspacePath $Workspace
if (-not (Test-Path $workspacePath)) { throw "Workspace not found: $workspacePath" }
if ([string]::IsNullOrWhiteSpace($RunId)) { $RunId = Find-LatestRunId $workspacePath }
if ([string]::IsNullOrWhiteSpace($RunId)) { throw "RunId was not provided and no standard run directory exists." }
if ($RunId -notmatch '^run-[0-9A-Za-z][0-9A-Za-z._-]*$') { throw "Invalid RunId '$RunId'." }
$skillRoot = Join-Path $workspacePath "agent-skills"
$runSkillDir = Join-Path $workspacePath "runs/$RunId/skills"
New-Item -ItemType Directory -Force -Path $runSkillDir | Out-Null
$utc = [DateTimeOffset]::UtcNow.ToString("o")
$recorded = @()
foreach ($name in $SkillName) {
    $normalized = $name.Trim().ToLowerInvariant()
    if ($normalized -notmatch '^[a-z0-9][a-z0-9._-]*$') { throw "Invalid skill name '$name'." }
    $skillPath = Join-Path $skillRoot "$normalized/SKILL.md"
    if (-not (Test-Path $skillPath)) { throw "Unknown agent skill '$normalized': missing $skillPath" }
    $entry = [ordered]@{
        schemaVersion = "agent-skill-usage/v1"
        utc = $utc
        runId = $RunId
        skillName = $normalized
        skillPath = "agent-skills/$normalized/SKILL.md"
        trigger = $Trigger
        phase = $Phase
        decision = $Decision
        detail = $Detail
        evidencePath = $EvidencePath
    }
    Append-JsonLine (Join-Path $workspacePath "state/agent-skill-usage.jsonl") $entry
    Append-JsonLine (Join-Path $runSkillDir "agent-skill-usage.jsonl") $entry
    $recorded += [pscustomobject]$entry
}
$entries = @()
foreach ($line in Get-Content -Path (Join-Path $runSkillDir "agent-skill-usage.jsonl") -ErrorAction SilentlyContinue) {
    if ([string]::IsNullOrWhiteSpace($line)) { continue }
    try { $entries += ($line | ConvertFrom-Json -ErrorAction Stop) } catch { }
}
Update-AppliedSkillsMarkdown (Join-Path $runSkillDir "applied-skills.md") $RunId $entries
Write-Host "AGENT_SKILL_USAGE_RECORDED: $RunId $((@($recorded | ForEach-Object { $_.skillName }) -join ','))"
