// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace Example.E2ETests.Tests.Filters.Playwright;

// WARNING: some actions need manual review. See TODO comments below.

public class RegistryFilterPlaywright : PageTest
{

	[SetUp]
	public async Task SetUp()
	{
		// TODO: replace with actual runtime URL from config // line 16
		// TODO: mapped method requires manual review — var pagef = Navigation.OpenRegistryAgentPage()
		var loader= Page.Locator("[data-test='table-loader']"); // line 17
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 17
		// TODO: mapped method requires manual review — pagef.Loader.ValidateLoading()
		// TODO: raw statement — review: page = pagef
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckFilterScToRegistry()
	{
		await Page.Locator("[data-test-id='sc-filter']").FillAsync("1000000001"); // line 25
		await Page.Locator("[data-test-id='sc-filter']").PressAsync("Enter"); // line 25
		// TODO: mapped method requires manual review — page.Sc.InputAndSelect("1000000001")
		var loader= Page.Locator("[data-test='table-loader']"); // line 26
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 26
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		await Expect(Page.Locator("[data-test-id='table-row']").Nth(2)).ToContainTextAsync("0004"); // line 27
	}

	[Category("QuickRunning")]
	[TestCase("Ascending", "0005")]
	[TestCase("Descending", "0346")]
	public async Task CheckFilterScSortAndExcludeToRegistry(string sortOrder, string text)
	{
		// TODO: ExcludeValue for filter — complex interaction, needs manual migration // line 35
		// Original: page.Sc.ExcludeValue("1000000001") // line 35
		// TODO: mapped method requires manual review — page.Sc.ExcludeValue("1000000001")
		var loader= Page.Locator("[data-test='table-loader']"); // line 36
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 36
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		// TODO: SortSc for filter — complex interaction, needs manual migration // line 37
		// Original: page.Sc.SortSc(sortOrder) // line 37
		// TODO: mapped method requires manual review — page.Sc.SortSc(sortOrder)
		var loader_0= Page.Locator("[data-test='table-loader']"); // line 38
		if (await loader_0.CountAsync() > 0) await Expect(loader_0).ToBeHiddenAsync(); // line 38
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		await Expect(Page.Locator("[data-test-id='table-row']").Nth(2)).ToContainTextAsync(text); // line 39
		await Page.Locator("[data-test-id='sc-filter']").ClickAsync(); // line 40
		// TODO: mapped method requires manual review — page.Sc.ClearSort()
		var loader_1= Page.Locator("[data-test='table-loader']"); // line 41
		if (await loader_1.CountAsync() > 0) await Expect(loader_1).ToBeHiddenAsync(); // line 41
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
	}

	[Category("QuickRunning")]
	[TestCase("Ascending", 0)]
	[TestCase("Descending", 1234567.89)]
	public async Task CheckFilterRealizationToRegistry(string sortOrder, decimal text)
	{
		// TODO: Sort for sales amount — complex interaction, needs manual migration // line 49
		// Original: page.SalesAmount.Sort(sortOrder) // line 49
		// TODO: mapped method requires manual review — page.SalesAmount.Sort(sortOrder)
		var loader= Page.Locator("[data-test='table-loader']"); // line 50
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 50
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		// [Be] page.Table.Items.ElementAt(4).Sum.Get().Should().Be(text) // line 51
		// TODO: manual review needed
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckSubtotalToRegistry()
	{
		// [Be] page.ReportsSubtotalSalesAmount.Sum.Get().Should().Be(1000000.00m) // line 58
		// TODO: manual review needed
		// [Be] page.ReportsSubtotalAddCalcAmount.Sum.Get().Should().Be(-1000.00m) // line 59
		// TODO: manual review needed
		// [Be] page.ReportsSubtotalReward.Sum.Get().Should().Be(500000.00m) // line 60
		// TODO: manual review needed
	}

}
