// Generated by Migrator — Selenium C# → Playwright .NET

using Microsoft.Playwright.NUnit;
using NUnit.Framework;
using System.Threading.Tasks;

namespace Example.E2ETests.Tests.Functional.Playwright;

// WARNING: some actions need manual review. See TODO comments below.

public class WidgetPlaywright : PageTest
{

	[SetUp]
	public async Task SetUp()
	{
		// TODO: replace with actual runtime URL from config // line 17
		// TODO: mapped method requires manual review — var pagef = Navigation.OpenSearchPage()
		var loader = Page.Locator("[data-test='table-loader']"); // line 18
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 18
		// TODO: mapped method requires manual review — pagef.Loader.ValidateLoading()
		await Page.Locator("[data-test-id='t-widget-closed']").ClickAsync(); // line 19
		// TODO: mapped method requires manual review — var lightbox = pagef.WidgetButton.ClickAndOpen<WidgetPage>()
		// page variable assigned from ClickAndOpen result — handled by Page context // line 20
		await Expect(Page.Locator("[data-test-id='t_widget_userfilter']")).ToBeVisibleAsync(); // line 21
		await Expect(Page.Locator("[data-test-id='t_process_footer']").First).ToBeVisibleAsync(); // line 22
	}

	[Category("QuickRunning")]
	[Test]
	public async Task CheckUserToWidget()
	{
		await Page.Locator("[data-test-id='t_widget_userfilter']").ClickAsync(); // line 29
		await Page.Locator("[data-test-id='t_widget_searchfilter']").FillAsync("Test User"); // line 30
		await Page.Locator("[data-test-id='t_widget_searchfilter']").PressAsync("Enter"); // line 30
		// TODO: mapped method requires manual review — page.UserInput.InputTextAndSelectValue("Test User")
		await Expect(Page.Locator("[data-test-id='t_process_footer']").First).ToBeVisibleAsync(); // line 31
		var textResult_0 = await Page.Locator("[data-test-id='t_process_footer']").First.InnerTextAsync(); // line 32
		Assert.That(textResult_0, Is.Not.Empty);
	}

	[Test]
	public async Task CheckDateToWidget()
	{
		// TODO: ManualInputValue for date picker — complex interaction, needs manual migration // line 38
		// Original: page.WidgetDate.ManualInputValue("March", "2025", 22) // line 38
		// TODO: mapped method requires manual review — page.WidgetDate.ManualInputValue("March", "2025", 22)
		var loader = Page.Locator("[data-test='table-loader']"); // line 39
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 39
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		await Expect(Page.Locator("[data-test-id='t_process_footer']").First).ToBeVisibleAsync(); // line 40
		var textResult_1 = await Page.Locator("[data-test-id='t_process_footer']").First.InnerTextAsync(); // line 41
		Assert.That(textResult_1, Is.Not.Empty);
	}

	[Test]
	public async Task CheckSearchToWidget()
	{
		await Page.Locator("[data-tid='Input__root']").FillAsync("Example invoice 2024"); // line 47
		await Page.Locator("[data-tid='Input__root']").PressAsync("Enter"); // line 48
		var loader = Page.Locator("[data-test='table-loader']"); // line 49
		if (await loader.CountAsync() > 0) await Expect(loader).ToBeHiddenAsync(); // line 49
		// TODO: mapped method requires manual review — page.Loader.ValidateLoading()
		await Page.Locator("[data-test-id='t_process_footer']").First.WaitForAsync(); // line 50
		var textResult_2 = await Page.Locator("[data-test-id='t_process_footer']").First.InnerTextAsync(); // line 51
		Assert.That(textResult_2, Is.Not.Empty);
	}

}
